CREATE TABLE `discount_package` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `merchant_id` bigint(20) unsigned NOT NULL COMMENT '商家id',
  `merchant_store_id` bigint(20) NOT NULL COMMENT '实体门店id',
  `name` varchar(25) NOT NULL COMMENT '套餐名称',
  `cover_image` varchar(255) NOT NULL COMMENT '封面图片',
  `price` decimal(7,2) unsigned NOT NULL COMMENT '套餐价格',
  `original_price` decimal(7,2) unsigned NOT NULL COMMENT '原价',
  `other_instructions` varchar(250) DEFAULT NULL COMMENT '其他说明',
  `validity_period_begin` datetime NOT NULL COMMENT '有效期-开始(yyyy-MM-dd)',
  `validity_period_end` datetime NOT NULL COMMENT '有效期-结束(yyyy-MM-dd)',
  `use_time_week` varchar(15) NOT NULL COMMENT '使用时间-周一到周日(用1-7表示,并用逗号分隔)',
  `use_time_begin` time NOT NULL COMMENT '使用时间-开始(HH:mm)',
  `use_time_end` time NOT NULL COMMENT '使用时间-结束(HH:mm)',
  `status` tinyint(2) unsigned NOT NULL COMMENT '状态(0-删除|1-上架|2-下架)',
  `is_reservation` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否需要预约(0-免预约|1-需要预约)',
  `use_rules` varchar(550) DEFAULT NULL COMMENT '使用规则',
  `gmt_up` datetime NOT NULL COMMENT '上架时间',
  `gmt_create` datetime NOT NULL COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_merchant_id_status_gmt_up` (`merchant_id`,`status`,`gmt_up`) USING BTREE,
  KEY `idx_merchant_store_id_status_gmt_up` (`merchant_store_id`,`status`,`gmt_up`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='优惠套餐表';