package com.lawu.eshop.ad.srv.mapper;

import com.lawu.eshop.ad.srv.domain.AdRateSettingDO;
import com.lawu.eshop.ad.srv.domain.AdRateSettingDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AdRateSettingDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    long countByExample(AdRateSettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    int deleteByExample(AdRateSettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    int insert(AdRateSettingDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    int insertSelective(AdRateSettingDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    List<AdRateSettingDO> selectByExampleWithRowbounds(AdRateSettingDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    List<AdRateSettingDO> selectByExample(AdRateSettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    AdRateSettingDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdRateSettingDO record, @Param("example") AdRateSettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdRateSettingDO record, @Param("example") AdRateSettingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdRateSettingDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_rate_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdRateSettingDO record);
}