package com.lawu.eshop.ad.srv.mapper;

import com.lawu.eshop.ad.srv.domain.InviterBountyDO;
import com.lawu.eshop.ad.srv.domain.InviterBountyDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InviterBountyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    int countByExample(InviterBountyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    int deleteByExample(InviterBountyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    int insert(InviterBountyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    int insertSelective(InviterBountyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    List<InviterBountyDO> selectByExampleWithRowbounds(InviterBountyDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    List<InviterBountyDO> selectByExample(InviterBountyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    InviterBountyDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InviterBountyDO record, @Param("example") InviterBountyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InviterBountyDO record, @Param("example") InviterBountyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InviterBountyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inviter_bounty
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InviterBountyDO record);
}