package com.lawu.eshop.ad.srv.mapper;

import com.lawu.eshop.ad.srv.domain.PointPoolDO;
import com.lawu.eshop.ad.srv.domain.PointPoolDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PointPoolDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    long countByExample(PointPoolDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    int deleteByExample(PointPoolDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    int insert(PointPoolDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    int insertSelective(PointPoolDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    List<PointPoolDO> selectByExampleWithRowbounds(PointPoolDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    List<PointPoolDO> selectByExample(PointPoolDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    PointPoolDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PointPoolDO record, @Param("example") PointPoolDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PointPoolDO record, @Param("example") PointPoolDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PointPoolDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_pool
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PointPoolDO record);
}