package com.lawu.eshop.ad.srv.mapper;

import com.lawu.eshop.ad.srv.domain.UserTakedRedPacketDO;
import com.lawu.eshop.ad.srv.domain.UserTakedRedPacketDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserTakedRedPacketDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    int countByExample(UserTakedRedPacketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    int deleteByExample(UserTakedRedPacketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    int insert(UserTakedRedPacketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    int insertSelective(UserTakedRedPacketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    List<UserTakedRedPacketDO> selectByExampleWithRowbounds(UserTakedRedPacketDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    List<UserTakedRedPacketDO> selectByExample(UserTakedRedPacketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    UserTakedRedPacketDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserTakedRedPacketDO record, @Param("example") UserTakedRedPacketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserTakedRedPacketDO record, @Param("example") UserTakedRedPacketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserTakedRedPacketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_taked_red_packet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserTakedRedPacketDO record);
}