package com.lawu.eshop.ad.srv.mapper;

import com.lawu.eshop.ad.srv.domain.UserRedPacketDO;
import com.lawu.eshop.ad.srv.domain.UserRedPacketDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserRedPacketDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    int countByExample(UserRedPacketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    int deleteByExample(UserRedPacketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    int insert(UserRedPacketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    int insertSelective(UserRedPacketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    List<UserRedPacketDO> selectByExampleWithRowbounds(UserRedPacketDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    List<UserRedPacketDO> selectByExample(UserRedPacketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    UserRedPacketDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserRedPacketDO record, @Param("example") UserRedPacketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserRedPacketDO record, @Param("example") UserRedPacketDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRedPacketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_red_packet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRedPacketDO record);
}