package com.lawu.eshop.beh.analyze.srv.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InviteAbnormalDecideRecordDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    public InviteAbnormalDecideRecordDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserNumIsNull() {
            addCriterion("user_num is null");
            return (Criteria) this;
        }

        public Criteria andUserNumIsNotNull() {
            addCriterion("user_num is not null");
            return (Criteria) this;
        }

        public Criteria andUserNumEqualTo(String value) {
            addCriterion("user_num =", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotEqualTo(String value) {
            addCriterion("user_num <>", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumGreaterThan(String value) {
            addCriterion("user_num >", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumGreaterThanOrEqualTo(String value) {
            addCriterion("user_num >=", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumLessThan(String value) {
            addCriterion("user_num <", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumLessThanOrEqualTo(String value) {
            addCriterion("user_num <=", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumLike(String value) {
            addCriterion("user_num like", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotLike(String value) {
            addCriterion("user_num not like", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumIn(List<String> values) {
            addCriterion("user_num in", values, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotIn(List<String> values) {
            addCriterion("user_num not in", values, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumBetween(String value1, String value2) {
            addCriterion("user_num between", value1, value2, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotBetween(String value1, String value2) {
            addCriterion("user_num not between", value1, value2, "userNum");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("account is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("account is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("account =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("account <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("account >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("account >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("account <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("account <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("account like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("account not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("account in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("account not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("account between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("account not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andIsShortHfIsNull() {
            addCriterion("is_short_hf is null");
            return (Criteria) this;
        }

        public Criteria andIsShortHfIsNotNull() {
            addCriterion("is_short_hf is not null");
            return (Criteria) this;
        }

        public Criteria andIsShortHfEqualTo(Boolean value) {
            addCriterion("is_short_hf =", value, "isShortHf");
            return (Criteria) this;
        }

        public Criteria andIsShortHfNotEqualTo(Boolean value) {
            addCriterion("is_short_hf <>", value, "isShortHf");
            return (Criteria) this;
        }

        public Criteria andIsShortHfGreaterThan(Boolean value) {
            addCriterion("is_short_hf >", value, "isShortHf");
            return (Criteria) this;
        }

        public Criteria andIsShortHfGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_short_hf >=", value, "isShortHf");
            return (Criteria) this;
        }

        public Criteria andIsShortHfLessThan(Boolean value) {
            addCriterion("is_short_hf <", value, "isShortHf");
            return (Criteria) this;
        }

        public Criteria andIsShortHfLessThanOrEqualTo(Boolean value) {
            addCriterion("is_short_hf <=", value, "isShortHf");
            return (Criteria) this;
        }

        public Criteria andIsShortHfIn(List<Boolean> values) {
            addCriterion("is_short_hf in", values, "isShortHf");
            return (Criteria) this;
        }

        public Criteria andIsShortHfNotIn(List<Boolean> values) {
            addCriterion("is_short_hf not in", values, "isShortHf");
            return (Criteria) this;
        }

        public Criteria andIsShortHfBetween(Boolean value1, Boolean value2) {
            addCriterion("is_short_hf between", value1, value2, "isShortHf");
            return (Criteria) this;
        }

        public Criteria andIsShortHfNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_short_hf not between", value1, value2, "isShortHf");
            return (Criteria) this;
        }

        public Criteria andIsLongHfIsNull() {
            addCriterion("is_long_hf is null");
            return (Criteria) this;
        }

        public Criteria andIsLongHfIsNotNull() {
            addCriterion("is_long_hf is not null");
            return (Criteria) this;
        }

        public Criteria andIsLongHfEqualTo(Boolean value) {
            addCriterion("is_long_hf =", value, "isLongHf");
            return (Criteria) this;
        }

        public Criteria andIsLongHfNotEqualTo(Boolean value) {
            addCriterion("is_long_hf <>", value, "isLongHf");
            return (Criteria) this;
        }

        public Criteria andIsLongHfGreaterThan(Boolean value) {
            addCriterion("is_long_hf >", value, "isLongHf");
            return (Criteria) this;
        }

        public Criteria andIsLongHfGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_long_hf >=", value, "isLongHf");
            return (Criteria) this;
        }

        public Criteria andIsLongHfLessThan(Boolean value) {
            addCriterion("is_long_hf <", value, "isLongHf");
            return (Criteria) this;
        }

        public Criteria andIsLongHfLessThanOrEqualTo(Boolean value) {
            addCriterion("is_long_hf <=", value, "isLongHf");
            return (Criteria) this;
        }

        public Criteria andIsLongHfIn(List<Boolean> values) {
            addCriterion("is_long_hf in", values, "isLongHf");
            return (Criteria) this;
        }

        public Criteria andIsLongHfNotIn(List<Boolean> values) {
            addCriterion("is_long_hf not in", values, "isLongHf");
            return (Criteria) this;
        }

        public Criteria andIsLongHfBetween(Boolean value1, Boolean value2) {
            addCriterion("is_long_hf between", value1, value2, "isLongHf");
            return (Criteria) this;
        }

        public Criteria andIsLongHfNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_long_hf not between", value1, value2, "isLongHf");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfIsNull() {
            addCriterion("is_many_short_hf is null");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfIsNotNull() {
            addCriterion("is_many_short_hf is not null");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfEqualTo(Boolean value) {
            addCriterion("is_many_short_hf =", value, "isManyShortHf");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfNotEqualTo(Boolean value) {
            addCriterion("is_many_short_hf <>", value, "isManyShortHf");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfGreaterThan(Boolean value) {
            addCriterion("is_many_short_hf >", value, "isManyShortHf");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_many_short_hf >=", value, "isManyShortHf");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfLessThan(Boolean value) {
            addCriterion("is_many_short_hf <", value, "isManyShortHf");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfLessThanOrEqualTo(Boolean value) {
            addCriterion("is_many_short_hf <=", value, "isManyShortHf");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfIn(List<Boolean> values) {
            addCriterion("is_many_short_hf in", values, "isManyShortHf");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfNotIn(List<Boolean> values) {
            addCriterion("is_many_short_hf not in", values, "isManyShortHf");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfBetween(Boolean value1, Boolean value2) {
            addCriterion("is_many_short_hf between", value1, value2, "isManyShortHf");
            return (Criteria) this;
        }

        public Criteria andIsManyShortHfNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_many_short_hf not between", value1, value2, "isManyShortHf");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfIsNull() {
            addCriterion("is_many_long_hf is null");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfIsNotNull() {
            addCriterion("is_many_long_hf is not null");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfEqualTo(Boolean value) {
            addCriterion("is_many_long_hf =", value, "isManyLongHf");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfNotEqualTo(Boolean value) {
            addCriterion("is_many_long_hf <>", value, "isManyLongHf");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfGreaterThan(Boolean value) {
            addCriterion("is_many_long_hf >", value, "isManyLongHf");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_many_long_hf >=", value, "isManyLongHf");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfLessThan(Boolean value) {
            addCriterion("is_many_long_hf <", value, "isManyLongHf");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfLessThanOrEqualTo(Boolean value) {
            addCriterion("is_many_long_hf <=", value, "isManyLongHf");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfIn(List<Boolean> values) {
            addCriterion("is_many_long_hf in", values, "isManyLongHf");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfNotIn(List<Boolean> values) {
            addCriterion("is_many_long_hf not in", values, "isManyLongHf");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfBetween(Boolean value1, Boolean value2) {
            addCriterion("is_many_long_hf between", value1, value2, "isManyLongHf");
            return (Criteria) this;
        }

        public Criteria andIsManyLongHfNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_many_long_hf not between", value1, value2, "isManyLongHf");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfIsNull() {
            addCriterion("is_one_day_hf is null");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfIsNotNull() {
            addCriterion("is_one_day_hf is not null");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfEqualTo(Boolean value) {
            addCriterion("is_one_day_hf =", value, "isOneDayHf");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfNotEqualTo(Boolean value) {
            addCriterion("is_one_day_hf <>", value, "isOneDayHf");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfGreaterThan(Boolean value) {
            addCriterion("is_one_day_hf >", value, "isOneDayHf");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_one_day_hf >=", value, "isOneDayHf");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfLessThan(Boolean value) {
            addCriterion("is_one_day_hf <", value, "isOneDayHf");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfLessThanOrEqualTo(Boolean value) {
            addCriterion("is_one_day_hf <=", value, "isOneDayHf");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfIn(List<Boolean> values) {
            addCriterion("is_one_day_hf in", values, "isOneDayHf");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfNotIn(List<Boolean> values) {
            addCriterion("is_one_day_hf not in", values, "isOneDayHf");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfBetween(Boolean value1, Boolean value2) {
            addCriterion("is_one_day_hf between", value1, value2, "isOneDayHf");
            return (Criteria) this;
        }

        public Criteria andIsOneDayHfNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_one_day_hf not between", value1, value2, "isOneDayHf");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfIsNull() {
            addCriterion("is_early_hf is null");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfIsNotNull() {
            addCriterion("is_early_hf is not null");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfEqualTo(Boolean value) {
            addCriterion("is_early_hf =", value, "isEarlyHf");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfNotEqualTo(Boolean value) {
            addCriterion("is_early_hf <>", value, "isEarlyHf");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfGreaterThan(Boolean value) {
            addCriterion("is_early_hf >", value, "isEarlyHf");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_early_hf >=", value, "isEarlyHf");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfLessThan(Boolean value) {
            addCriterion("is_early_hf <", value, "isEarlyHf");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfLessThanOrEqualTo(Boolean value) {
            addCriterion("is_early_hf <=", value, "isEarlyHf");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfIn(List<Boolean> values) {
            addCriterion("is_early_hf in", values, "isEarlyHf");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfNotIn(List<Boolean> values) {
            addCriterion("is_early_hf not in", values, "isEarlyHf");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfBetween(Boolean value1, Boolean value2) {
            addCriterion("is_early_hf between", value1, value2, "isEarlyHf");
            return (Criteria) this;
        }

        public Criteria andIsEarlyHfNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_early_hf not between", value1, value2, "isEarlyHf");
            return (Criteria) this;
        }

        public Criteria andIsIpHfIsNull() {
            addCriterion("is_ip_hf is null");
            return (Criteria) this;
        }

        public Criteria andIsIpHfIsNotNull() {
            addCriterion("is_ip_hf is not null");
            return (Criteria) this;
        }

        public Criteria andIsIpHfEqualTo(Boolean value) {
            addCriterion("is_ip_hf =", value, "isIpHf");
            return (Criteria) this;
        }

        public Criteria andIsIpHfNotEqualTo(Boolean value) {
            addCriterion("is_ip_hf <>", value, "isIpHf");
            return (Criteria) this;
        }

        public Criteria andIsIpHfGreaterThan(Boolean value) {
            addCriterion("is_ip_hf >", value, "isIpHf");
            return (Criteria) this;
        }

        public Criteria andIsIpHfGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_ip_hf >=", value, "isIpHf");
            return (Criteria) this;
        }

        public Criteria andIsIpHfLessThan(Boolean value) {
            addCriterion("is_ip_hf <", value, "isIpHf");
            return (Criteria) this;
        }

        public Criteria andIsIpHfLessThanOrEqualTo(Boolean value) {
            addCriterion("is_ip_hf <=", value, "isIpHf");
            return (Criteria) this;
        }

        public Criteria andIsIpHfIn(List<Boolean> values) {
            addCriterion("is_ip_hf in", values, "isIpHf");
            return (Criteria) this;
        }

        public Criteria andIsIpHfNotIn(List<Boolean> values) {
            addCriterion("is_ip_hf not in", values, "isIpHf");
            return (Criteria) this;
        }

        public Criteria andIsIpHfBetween(Boolean value1, Boolean value2) {
            addCriterion("is_ip_hf between", value1, value2, "isIpHf");
            return (Criteria) this;
        }

        public Criteria andIsIpHfNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_ip_hf not between", value1, value2, "isIpHf");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalIsNull() {
            addCriterion("is_abnormal is null");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalIsNotNull() {
            addCriterion("is_abnormal is not null");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalEqualTo(Boolean value) {
            addCriterion("is_abnormal =", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalNotEqualTo(Boolean value) {
            addCriterion("is_abnormal <>", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalGreaterThan(Boolean value) {
            addCriterion("is_abnormal >", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_abnormal >=", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalLessThan(Boolean value) {
            addCriterion("is_abnormal <", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalLessThanOrEqualTo(Boolean value) {
            addCriterion("is_abnormal <=", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalIn(List<Boolean> values) {
            addCriterion("is_abnormal in", values, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalNotIn(List<Boolean> values) {
            addCriterion("is_abnormal not in", values, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalBetween(Boolean value1, Boolean value2) {
            addCriterion("is_abnormal between", value1, value2, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_abnormal not between", value1, value2, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalIsNull() {
            addCriterion("is_activity_abnormal is null");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalIsNotNull() {
            addCriterion("is_activity_abnormal is not null");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalEqualTo(Boolean value) {
            addCriterion("is_activity_abnormal =", value, "isActivityAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalNotEqualTo(Boolean value) {
            addCriterion("is_activity_abnormal <>", value, "isActivityAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalGreaterThan(Boolean value) {
            addCriterion("is_activity_abnormal >", value, "isActivityAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_activity_abnormal >=", value, "isActivityAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalLessThan(Boolean value) {
            addCriterion("is_activity_abnormal <", value, "isActivityAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalLessThanOrEqualTo(Boolean value) {
            addCriterion("is_activity_abnormal <=", value, "isActivityAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalIn(List<Boolean> values) {
            addCriterion("is_activity_abnormal in", values, "isActivityAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalNotIn(List<Boolean> values) {
            addCriterion("is_activity_abnormal not in", values, "isActivityAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalBetween(Boolean value1, Boolean value2) {
            addCriterion("is_activity_abnormal between", value1, value2, "isActivityAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsActivityAbnormalNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_activity_abnormal not between", value1, value2, "isActivityAbnormal");
            return (Criteria) this;
        }

        public Criteria andProcessTypeIsNull() {
            addCriterion("process_type is null");
            return (Criteria) this;
        }

        public Criteria andProcessTypeIsNotNull() {
            addCriterion("process_type is not null");
            return (Criteria) this;
        }

        public Criteria andProcessTypeEqualTo(Byte value) {
            addCriterion("process_type =", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeNotEqualTo(Byte value) {
            addCriterion("process_type <>", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeGreaterThan(Byte value) {
            addCriterion("process_type >", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("process_type >=", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeLessThan(Byte value) {
            addCriterion("process_type <", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeLessThanOrEqualTo(Byte value) {
            addCriterion("process_type <=", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeIn(List<Byte> values) {
            addCriterion("process_type in", values, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeNotIn(List<Byte> values) {
            addCriterion("process_type not in", values, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeBetween(Byte value1, Byte value2) {
            addCriterion("process_type between", value1, value2, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("process_type not between", value1, value2, "processType");
            return (Criteria) this;
        }

        public Criteria andIsNoticedIsNull() {
            addCriterion("is_noticed is null");
            return (Criteria) this;
        }

        public Criteria andIsNoticedIsNotNull() {
            addCriterion("is_noticed is not null");
            return (Criteria) this;
        }

        public Criteria andIsNoticedEqualTo(Boolean value) {
            addCriterion("is_noticed =", value, "isNoticed");
            return (Criteria) this;
        }

        public Criteria andIsNoticedNotEqualTo(Boolean value) {
            addCriterion("is_noticed <>", value, "isNoticed");
            return (Criteria) this;
        }

        public Criteria andIsNoticedGreaterThan(Boolean value) {
            addCriterion("is_noticed >", value, "isNoticed");
            return (Criteria) this;
        }

        public Criteria andIsNoticedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_noticed >=", value, "isNoticed");
            return (Criteria) this;
        }

        public Criteria andIsNoticedLessThan(Boolean value) {
            addCriterion("is_noticed <", value, "isNoticed");
            return (Criteria) this;
        }

        public Criteria andIsNoticedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_noticed <=", value, "isNoticed");
            return (Criteria) this;
        }

        public Criteria andIsNoticedIn(List<Boolean> values) {
            addCriterion("is_noticed in", values, "isNoticed");
            return (Criteria) this;
        }

        public Criteria andIsNoticedNotIn(List<Boolean> values) {
            addCriterion("is_noticed not in", values, "isNoticed");
            return (Criteria) this;
        }

        public Criteria andIsNoticedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_noticed between", value1, value2, "isNoticed");
            return (Criteria) this;
        }

        public Criteria andIsNoticedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_noticed not between", value1, value2, "isNoticed");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invite_abnormal_decide_record
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}