package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.AppFunctionManageDO;
import com.lawu.eshop.mall.srv.domain.AppFunctionManageDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AppFunctionManageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    long countByExample(AppFunctionManageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    int deleteByExample(AppFunctionManageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    int insert(AppFunctionManageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    int insertSelective(AppFunctionManageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    List<AppFunctionManageDO> selectByExampleWithRowbounds(AppFunctionManageDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    List<AppFunctionManageDO> selectByExample(AppFunctionManageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    AppFunctionManageDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppFunctionManageDO record, @Param("example") AppFunctionManageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppFunctionManageDO record, @Param("example") AppFunctionManageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppFunctionManageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_function_manage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppFunctionManageDO record);
}