package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.IndustryTypeDO;
import com.lawu.eshop.mall.srv.domain.IndustryTypeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IndustryTypeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    int countByExample(IndustryTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    int deleteByExample(IndustryTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    int insert(IndustryTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    int insertSelective(IndustryTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    List<IndustryTypeDO> selectByExampleWithRowbounds(IndustryTypeDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    List<IndustryTypeDO> selectByExample(IndustryTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    IndustryTypeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IndustryTypeDO record, @Param("example") IndustryTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IndustryTypeDO record, @Param("example") IndustryTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IndustryTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IndustryTypeDO record);
}