package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.LotteryActivityDO;
import com.lawu.eshop.mall.srv.domain.LotteryActivityDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LotteryActivityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    int countByExample(LotteryActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    int deleteByExample(LotteryActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    int insert(LotteryActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    int insertSelective(LotteryActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    List<LotteryActivityDO> selectByExampleWithRowbounds(LotteryActivityDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    List<LotteryActivityDO> selectByExample(LotteryActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    LotteryActivityDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LotteryActivityDO record, @Param("example") LotteryActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LotteryActivityDO record, @Param("example") LotteryActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LotteryActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LotteryActivityDO record);
}