package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.SearchWordDO;
import com.lawu.eshop.mall.srv.domain.SearchWordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SearchWordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    int countByExample(SearchWordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    int deleteByExample(SearchWordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    int insert(SearchWordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    int insertSelective(SearchWordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    List<SearchWordDO> selectByExampleWithRowbounds(SearchWordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    List<SearchWordDO> selectByExample(SearchWordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    SearchWordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SearchWordDO record, @Param("example") SearchWordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SearchWordDO record, @Param("example") SearchWordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SearchWordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_word
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SearchWordDO record);
}