package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.SuggestionDO;
import com.lawu.eshop.mall.srv.domain.SuggestionDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SuggestionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    int countByExample(SuggestionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    int deleteByExample(SuggestionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    int insert(SuggestionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    int insertSelective(SuggestionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    List<SuggestionDO> selectByExampleWithRowbounds(SuggestionDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    List<SuggestionDO> selectByExample(SuggestionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    SuggestionDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    int updateByExampleSelective(@Param("record") SuggestionDO record, @Param("example") SuggestionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    int updateByExample(@Param("record") SuggestionDO record, @Param("example") SuggestionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    int updateByPrimaryKeySelective(SuggestionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbg.generated 2017-03-23 17:01:47
     */
    int updateByPrimaryKey(SuggestionDO record);
}