package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.VerifyCodeDO;
import com.lawu.eshop.mall.srv.domain.VerifyCodeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VerifyCodeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int countByExample(VerifyCodeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int deleteByExample(VerifyCodeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int insert(VerifyCodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int insertSelective(VerifyCodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    List<VerifyCodeDO> selectByExampleWithRowbounds(VerifyCodeDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    List<VerifyCodeDO> selectByExample(VerifyCodeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    VerifyCodeDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByExampleSelective(@Param("record") VerifyCodeDO record, @Param("example") VerifyCodeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByExample(@Param("record") VerifyCodeDO record, @Param("example") VerifyCodeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByPrimaryKeySelective(VerifyCodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByPrimaryKey(VerifyCodeDO record);
}