package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.WindowMessageDO;
import com.lawu.eshop.mall.srv.domain.WindowMessageDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WindowMessageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    long countByExample(WindowMessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    int deleteByExample(WindowMessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    int insert(WindowMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    int insertSelective(WindowMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    List<WindowMessageDO> selectByExampleWithRowbounds(WindowMessageDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    List<WindowMessageDO> selectByExample(WindowMessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    WindowMessageDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WindowMessageDO record, @Param("example") WindowMessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WindowMessageDO record, @Param("example") WindowMessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WindowMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table window_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WindowMessageDO record);
}