package com.lawu.eshop.ad.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class AdLexiconDO implements Serializable {
    /**
     *
     * 主键
     * ad_lexicon.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 名称
     * ad_lexicon.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * 创建时间
     * ad_lexicon.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_lexicon
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_lexicon.id
     *
     * @return the value of ad_lexicon.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_lexicon.id
     *
     * @param id the value for ad_lexicon.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_lexicon.title
     *
     * @return the value of ad_lexicon.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_lexicon.title
     *
     * @param title the value for ad_lexicon.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_lexicon.gmt_create
     *
     * @return the value of ad_lexicon.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_lexicon.gmt_create
     *
     * @param gmtCreate the value for ad_lexicon.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}