package com.lawu.eshop.ad.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class AdRegionDO implements Serializable {
    /**
     *
     * 主键
     * ad_region.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 商家ID
     * ad_region.merchant_id
     *
     * @mbg.generated
     */
    private Long merchantId;

    /**
     *
     * 广告ID
     * ad_region.ad_id
     *
     * @mbg.generated
     */
    private Long adId;

    /**
     *
     * 区域
     * ad_region.region_id
     *
     * @mbg.generated
     */
    private String regionId;

    /**
     *
     * 创建时间
     * ad_region.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_region
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_region.id
     *
     * @return the value of ad_region.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_region.id
     *
     * @param id the value for ad_region.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_region.merchant_id
     *
     * @return the value of ad_region.merchant_id
     *
     * @mbg.generated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_region.merchant_id
     *
     * @param merchantId the value for ad_region.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_region.ad_id
     *
     * @return the value of ad_region.ad_id
     *
     * @mbg.generated
     */
    public Long getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_region.ad_id
     *
     * @param adId the value for ad_region.ad_id
     *
     * @mbg.generated
     */
    public void setAdId(Long adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_region.region_id
     *
     * @return the value of ad_region.region_id
     *
     * @mbg.generated
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_region.region_id
     *
     * @param regionId the value for ad_region.region_id
     *
     * @mbg.generated
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_region.gmt_create
     *
     * @return the value of ad_region.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_region.gmt_create
     *
     * @param gmtCreate the value for ad_region.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}