package com.lawu.eshop.ad.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PlatformRedPacketDO implements Serializable {
    /**
     *
     * 
     * platform_red_packet.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 金额
     * platform_red_packet.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     *
     * 发送红包总数
     * platform_red_packet.send_count
     *
     * @mbg.generated
     */
    private Integer sendCount;

    /**
     *
     * 红包状态 0-禁用 1-启用
     * platform_red_packet.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 操作人
     * platform_red_packet.auditor_id
     *
     * @mbg.generated
     */
    private Long auditorId;

    /**
     *
     * 更新时间
     * platform_red_packet.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * platform_red_packet.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_red_packet
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_red_packet.id
     *
     * @return the value of platform_red_packet.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_red_packet.id
     *
     * @param id the value for platform_red_packet.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_red_packet.money
     *
     * @return the value of platform_red_packet.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_red_packet.money
     *
     * @param money the value for platform_red_packet.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_red_packet.send_count
     *
     * @return the value of platform_red_packet.send_count
     *
     * @mbg.generated
     */
    public Integer getSendCount() {
        return sendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_red_packet.send_count
     *
     * @param sendCount the value for platform_red_packet.send_count
     *
     * @mbg.generated
     */
    public void setSendCount(Integer sendCount) {
        this.sendCount = sendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_red_packet.status
     *
     * @return the value of platform_red_packet.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_red_packet.status
     *
     * @param status the value for platform_red_packet.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_red_packet.auditor_id
     *
     * @return the value of platform_red_packet.auditor_id
     *
     * @mbg.generated
     */
    public Long getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_red_packet.auditor_id
     *
     * @param auditorId the value for platform_red_packet.auditor_id
     *
     * @mbg.generated
     */
    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_red_packet.gmt_modified
     *
     * @return the value of platform_red_packet.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_red_packet.gmt_modified
     *
     * @param gmtModified the value for platform_red_packet.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_red_packet.gmt_create
     *
     * @return the value of platform_red_packet.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_red_packet.gmt_create
     *
     * @param gmtCreate the value for platform_red_packet.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}