package com.lawu.eshop.product.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class FavoriteProductDO implements Serializable {
    /**
     *
     * 主键
     * favorite_product.id
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    private Long id;

    /**
     *
     * 会员
     * favorite_product.member_id
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    private Long memberId;

    /**
     *
     * 收藏
     * favorite_product.product_id
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    private Long productId;

    /**
     *
     * 创建日期
     * favorite_product.gmt_create
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table favorite_product
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite_product.id
     *
     * @return the value of favorite_product.id
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite_product.id
     *
     * @param id the value for favorite_product.id
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite_product.member_id
     *
     * @return the value of favorite_product.member_id
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite_product.member_id
     *
     * @param memberId the value for favorite_product.member_id
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite_product.product_id
     *
     * @return the value of favorite_product.product_id
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite_product.product_id
     *
     * @param productId the value for favorite_product.product_id
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite_product.gmt_create
     *
     * @return the value of favorite_product.gmt_create
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite_product.gmt_create
     *
     * @param gmtCreate the value for favorite_product.gmt_create
     *
     * @mbg.generated 2017-03-28 21:47:11
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}