package com.lawu.eshop.product.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class ProductSpecDO implements Serializable {
    /**
     *
     * 主键
     * product_spec.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 商品分类ID
     * product_spec.product_category_id
     *
     * @mbg.generated
     */
    private Integer productCategoryId;

    /**
     *
     * 规格名称
     * product_spec.spec_name
     *
     * @mbg.generated
     */
    private String specName;

    /**
     *
     * 顺序排序
     * product_spec.ordinal
     *
     * @mbg.generated
     */
    private Byte ordinal;

    /**
     *
     * 状态(0-删除1-有效)
     * product_spec.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * 修改时间
     * product_spec.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * product_spec.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_spec
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spec.id
     *
     * @return the value of product_spec.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spec.id
     *
     * @param id the value for product_spec.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spec.product_category_id
     *
     * @return the value of product_spec.product_category_id
     *
     * @mbg.generated
     */
    public Integer getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spec.product_category_id
     *
     * @param productCategoryId the value for product_spec.product_category_id
     *
     * @mbg.generated
     */
    public void setProductCategoryId(Integer productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spec.spec_name
     *
     * @return the value of product_spec.spec_name
     *
     * @mbg.generated
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spec.spec_name
     *
     * @param specName the value for product_spec.spec_name
     *
     * @mbg.generated
     */
    public void setSpecName(String specName) {
        this.specName = specName == null ? null : specName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spec.ordinal
     *
     * @return the value of product_spec.ordinal
     *
     * @mbg.generated
     */
    public Byte getOrdinal() {
        return ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spec.ordinal
     *
     * @param ordinal the value for product_spec.ordinal
     *
     * @mbg.generated
     */
    public void setOrdinal(Byte ordinal) {
        this.ordinal = ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spec.status
     *
     * @return the value of product_spec.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spec.status
     *
     * @param status the value for product_spec.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spec.gmt_modified
     *
     * @return the value of product_spec.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spec.gmt_modified
     *
     * @param gmtModified the value for product_spec.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spec.gmt_create
     *
     * @return the value of product_spec.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spec.gmt_create
     *
     * @param gmtCreate the value for product_spec.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}