package com.lawu.eshop.product.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class ProductCustomSpecDO implements Serializable {
    /**
     *
     * 主键
     * product_custom_spec.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 关联ID：类型/品牌-商品ID，规格项-商品型号ID
     * product_custom_spec.relate_id
     *
     * @mbg.generated
     */
    private Long relateId;

    /**
     *
     * 关联名称，类型-上下级名称，品牌-品牌名称，规格项-上下级类型+规格名称
     * product_custom_spec.relate_name
     *
     * @mbg.generated
     */
    private String relateName;

    /**
     *
     * 自定义规格名称
     * product_custom_spec.spec_name
     *
     * @mbg.generated
     */
    private String specName;

    /**
     *
     * 状态(0-删除1-未处理 2-已处理 3-不处理)
     * product_custom_spec.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 类型（1-类目|2-品牌|3-规格选项）
     * product_custom_spec.custom_type
     *
     * @mbg.generated
     */
    private Byte customType;

    /**
     *
     * 修改时间
     * product_custom_spec.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * product_custom_spec.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_custom_spec.id
     *
     * @return the value of product_custom_spec.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_custom_spec.id
     *
     * @param id the value for product_custom_spec.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_custom_spec.relate_id
     *
     * @return the value of product_custom_spec.relate_id
     *
     * @mbg.generated
     */
    public Long getRelateId() {
        return relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_custom_spec.relate_id
     *
     * @param relateId the value for product_custom_spec.relate_id
     *
     * @mbg.generated
     */
    public void setRelateId(Long relateId) {
        this.relateId = relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_custom_spec.relate_name
     *
     * @return the value of product_custom_spec.relate_name
     *
     * @mbg.generated
     */
    public String getRelateName() {
        return relateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_custom_spec.relate_name
     *
     * @param relateName the value for product_custom_spec.relate_name
     *
     * @mbg.generated
     */
    public void setRelateName(String relateName) {
        this.relateName = relateName == null ? null : relateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_custom_spec.spec_name
     *
     * @return the value of product_custom_spec.spec_name
     *
     * @mbg.generated
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_custom_spec.spec_name
     *
     * @param specName the value for product_custom_spec.spec_name
     *
     * @mbg.generated
     */
    public void setSpecName(String specName) {
        this.specName = specName == null ? null : specName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_custom_spec.status
     *
     * @return the value of product_custom_spec.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_custom_spec.status
     *
     * @param status the value for product_custom_spec.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_custom_spec.custom_type
     *
     * @return the value of product_custom_spec.custom_type
     *
     * @mbg.generated
     */
    public Byte getCustomType() {
        return customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_custom_spec.custom_type
     *
     * @param customType the value for product_custom_spec.custom_type
     *
     * @mbg.generated
     */
    public void setCustomType(Byte customType) {
        this.customType = customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_custom_spec.gmt_modified
     *
     * @return the value of product_custom_spec.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_custom_spec.gmt_modified
     *
     * @param gmtModified the value for product_custom_spec.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_custom_spec.gmt_create
     *
     * @return the value of product_custom_spec.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_custom_spec.gmt_create
     *
     * @param gmtCreate the value for product_custom_spec.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}