package com.lawu.eshop.product.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class ProductModelInventoryDO implements Serializable {
    /**
     *
     * 主键
     * product_model_inventory.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 商品型号id
     * product_model_inventory.product_model_id
     *
     * @mbg.generated
     */
    private Long productModelId;

    /**
     *
     * 数量
     * product_model_inventory.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * 购物订单id(在创建订单和取消订单会保存)
     * product_model_inventory.shopping_order_id
     *
     * @mbg.generated
     */
    private Long shoppingOrderId;

    /**
     *
     * 更新类型(0-加库存|1-减库存|2-创建订单|3-取消订单)
     * product_model_inventory.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * 创建时间
     * product_model_inventory.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * 更新时间
     * product_model_inventory.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_model_inventory
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_inventory.id
     *
     * @return the value of product_model_inventory.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_inventory.id
     *
     * @param id the value for product_model_inventory.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_inventory.product_model_id
     *
     * @return the value of product_model_inventory.product_model_id
     *
     * @mbg.generated
     */
    public Long getProductModelId() {
        return productModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_inventory.product_model_id
     *
     * @param productModelId the value for product_model_inventory.product_model_id
     *
     * @mbg.generated
     */
    public void setProductModelId(Long productModelId) {
        this.productModelId = productModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_inventory.quantity
     *
     * @return the value of product_model_inventory.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_inventory.quantity
     *
     * @param quantity the value for product_model_inventory.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_inventory.shopping_order_id
     *
     * @return the value of product_model_inventory.shopping_order_id
     *
     * @mbg.generated
     */
    public Long getShoppingOrderId() {
        return shoppingOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_inventory.shopping_order_id
     *
     * @param shoppingOrderId the value for product_model_inventory.shopping_order_id
     *
     * @mbg.generated
     */
    public void setShoppingOrderId(Long shoppingOrderId) {
        this.shoppingOrderId = shoppingOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_inventory.type
     *
     * @return the value of product_model_inventory.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_inventory.type
     *
     * @param type the value for product_model_inventory.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_inventory.gmt_create
     *
     * @return the value of product_model_inventory.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_inventory.gmt_create
     *
     * @param gmtCreate the value for product_model_inventory.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_inventory.gmt_modified
     *
     * @return the value of product_model_inventory.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_inventory.gmt_modified
     *
     * @param gmtModified the value for product_model_inventory.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}