package com.lawu.eshop.product.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SeckillActivityProductDO implements Serializable {
    /**
     *
     * 主键
     * seckill_activity_product.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 抢购活动id
     * seckill_activity_product.activity_id
     *
     * @mbg.generated
     */
    private Long activityId;

    /**
     *
     * 商家id
     * seckill_activity_product.merchant_id
     *
     * @mbg.generated
     */
    private Long merchantId;

    /**
     *
     * 商品id
     * seckill_activity_product.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * 商品图片
     * seckill_activity_product.product_picture
     *
     * @mbg.generated
     */
    private String productPicture;

    /**
     *
     * 商品名称
     * seckill_activity_product.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * 商品原价
     * seckill_activity_product.original_price
     *
     * @mbg.generated
     */
    private BigDecimal originalPrice;

    /**
     *
     * 抢购价格
     * seckill_activity_product.sale_money
     *
     * @mbg.generated
     */
    private BigDecimal saleMoney;

    /**
     *
     * 商品型号总数量
     * seckill_activity_product.product_model_count
     *
     * @mbg.generated
     */
    private Integer productModelCount;

    /**
     *
     * 剩余数量
     * seckill_activity_product.left_count
     *
     * @mbg.generated
     */
    private Integer leftCount;

    /**
     *
     * 成交额
     * seckill_activity_product.turnover
     *
     * @mbg.generated
     */
    private BigDecimal turnover;

    /**
     *
     * 排序优先级
     * seckill_activity_product.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * 反馈原因
     * seckill_activity_product.reasons
     *
     * @mbg.generated
     */
    private String reasons;

    /**
     *
     * 审核人员
     * seckill_activity_product.auditor_account
     *
     * @mbg.generated
     */
    private String auditorAccount;

    /**
     *
     * 审核时间
     * seckill_activity_product.audit_time
     *
     * @mbg.generated
     */
    private Date auditTime;

    /**
     *
     * 关注人数
     * seckill_activity_product.attention_count
     *
     * @mbg.generated
     */
    private Integer attentionCount;

    /**
     *
     * 状态(1-未审核|2-已审核|3-未通过|)
     * seckill_activity_product.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 修改时间
     * seckill_activity_product.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * seckill_activity_product.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seckill_activity_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.id
     *
     * @return the value of seckill_activity_product.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.id
     *
     * @param id the value for seckill_activity_product.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.activity_id
     *
     * @return the value of seckill_activity_product.activity_id
     *
     * @mbg.generated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.activity_id
     *
     * @param activityId the value for seckill_activity_product.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.merchant_id
     *
     * @return the value of seckill_activity_product.merchant_id
     *
     * @mbg.generated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.merchant_id
     *
     * @param merchantId the value for seckill_activity_product.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.product_id
     *
     * @return the value of seckill_activity_product.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.product_id
     *
     * @param productId the value for seckill_activity_product.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.product_picture
     *
     * @return the value of seckill_activity_product.product_picture
     *
     * @mbg.generated
     */
    public String getProductPicture() {
        return productPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.product_picture
     *
     * @param productPicture the value for seckill_activity_product.product_picture
     *
     * @mbg.generated
     */
    public void setProductPicture(String productPicture) {
        this.productPicture = productPicture == null ? null : productPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.product_name
     *
     * @return the value of seckill_activity_product.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.product_name
     *
     * @param productName the value for seckill_activity_product.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.original_price
     *
     * @return the value of seckill_activity_product.original_price
     *
     * @mbg.generated
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.original_price
     *
     * @param originalPrice the value for seckill_activity_product.original_price
     *
     * @mbg.generated
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.sale_money
     *
     * @return the value of seckill_activity_product.sale_money
     *
     * @mbg.generated
     */
    public BigDecimal getSaleMoney() {
        return saleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.sale_money
     *
     * @param saleMoney the value for seckill_activity_product.sale_money
     *
     * @mbg.generated
     */
    public void setSaleMoney(BigDecimal saleMoney) {
        this.saleMoney = saleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.product_model_count
     *
     * @return the value of seckill_activity_product.product_model_count
     *
     * @mbg.generated
     */
    public Integer getProductModelCount() {
        return productModelCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.product_model_count
     *
     * @param productModelCount the value for seckill_activity_product.product_model_count
     *
     * @mbg.generated
     */
    public void setProductModelCount(Integer productModelCount) {
        this.productModelCount = productModelCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.left_count
     *
     * @return the value of seckill_activity_product.left_count
     *
     * @mbg.generated
     */
    public Integer getLeftCount() {
        return leftCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.left_count
     *
     * @param leftCount the value for seckill_activity_product.left_count
     *
     * @mbg.generated
     */
    public void setLeftCount(Integer leftCount) {
        this.leftCount = leftCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.turnover
     *
     * @return the value of seckill_activity_product.turnover
     *
     * @mbg.generated
     */
    public BigDecimal getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.turnover
     *
     * @param turnover the value for seckill_activity_product.turnover
     *
     * @mbg.generated
     */
    public void setTurnover(BigDecimal turnover) {
        this.turnover = turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.priority
     *
     * @return the value of seckill_activity_product.priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.priority
     *
     * @param priority the value for seckill_activity_product.priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.reasons
     *
     * @return the value of seckill_activity_product.reasons
     *
     * @mbg.generated
     */
    public String getReasons() {
        return reasons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.reasons
     *
     * @param reasons the value for seckill_activity_product.reasons
     *
     * @mbg.generated
     */
    public void setReasons(String reasons) {
        this.reasons = reasons == null ? null : reasons.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.auditor_account
     *
     * @return the value of seckill_activity_product.auditor_account
     *
     * @mbg.generated
     */
    public String getAuditorAccount() {
        return auditorAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.auditor_account
     *
     * @param auditorAccount the value for seckill_activity_product.auditor_account
     *
     * @mbg.generated
     */
    public void setAuditorAccount(String auditorAccount) {
        this.auditorAccount = auditorAccount == null ? null : auditorAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.audit_time
     *
     * @return the value of seckill_activity_product.audit_time
     *
     * @mbg.generated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.audit_time
     *
     * @param auditTime the value for seckill_activity_product.audit_time
     *
     * @mbg.generated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.attention_count
     *
     * @return the value of seckill_activity_product.attention_count
     *
     * @mbg.generated
     */
    public Integer getAttentionCount() {
        return attentionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.attention_count
     *
     * @param attentionCount the value for seckill_activity_product.attention_count
     *
     * @mbg.generated
     */
    public void setAttentionCount(Integer attentionCount) {
        this.attentionCount = attentionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.status
     *
     * @return the value of seckill_activity_product.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.status
     *
     * @param status the value for seckill_activity_product.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.gmt_modified
     *
     * @return the value of seckill_activity_product.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.gmt_modified
     *
     * @param gmtModified the value for seckill_activity_product.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_activity_product.gmt_create
     *
     * @return the value of seckill_activity_product.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_activity_product.gmt_create
     *
     * @param gmtCreate the value for seckill_activity_product.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}