package com.lawu.eshop.statistics.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ReportSalesDailyDO implements Serializable {
    /**
     *
     * 主键
     * report_sales_daily.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 买单金额
     * report_sales_daily.pay_order_amount
     *
     * @mbg.generated
     */
    private BigDecimal payOrderAmount;

    /**
     *
     * 购物订单金额
     * report_sales_daily.shopping_order_amount
     *
     * @mbg.generated
     */
    private BigDecimal shoppingOrderAmount;

    /**
     *
     * 总金额
     * report_sales_daily.total_amount
     *
     * @mbg.generated
     */
    private BigDecimal totalAmount;

    /**
     *
     * 统计时间
     * report_sales_daily.gmt_report
     *
     * @mbg.generated
     */
    private Date gmtReport;

    /**
     *
     * 创建时间
     * report_sales_daily.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_sales_daily
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_sales_daily.id
     *
     * @return the value of report_sales_daily.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_sales_daily.id
     *
     * @param id the value for report_sales_daily.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_sales_daily.pay_order_amount
     *
     * @return the value of report_sales_daily.pay_order_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPayOrderAmount() {
        return payOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_sales_daily.pay_order_amount
     *
     * @param payOrderAmount the value for report_sales_daily.pay_order_amount
     *
     * @mbg.generated
     */
    public void setPayOrderAmount(BigDecimal payOrderAmount) {
        this.payOrderAmount = payOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_sales_daily.shopping_order_amount
     *
     * @return the value of report_sales_daily.shopping_order_amount
     *
     * @mbg.generated
     */
    public BigDecimal getShoppingOrderAmount() {
        return shoppingOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_sales_daily.shopping_order_amount
     *
     * @param shoppingOrderAmount the value for report_sales_daily.shopping_order_amount
     *
     * @mbg.generated
     */
    public void setShoppingOrderAmount(BigDecimal shoppingOrderAmount) {
        this.shoppingOrderAmount = shoppingOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_sales_daily.total_amount
     *
     * @return the value of report_sales_daily.total_amount
     *
     * @mbg.generated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_sales_daily.total_amount
     *
     * @param totalAmount the value for report_sales_daily.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_sales_daily.gmt_report
     *
     * @return the value of report_sales_daily.gmt_report
     *
     * @mbg.generated
     */
    public Date getGmtReport() {
        return gmtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_sales_daily.gmt_report
     *
     * @param gmtReport the value for report_sales_daily.gmt_report
     *
     * @mbg.generated
     */
    public void setGmtReport(Date gmtReport) {
        this.gmtReport = gmtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_sales_daily.gmt_create
     *
     * @return the value of report_sales_daily.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_sales_daily.gmt_create
     *
     * @param gmtCreate the value for report_sales_daily.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}