package com.lawu.eshop.statistics.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class ReportUserRegMonthDO implements Serializable {
    /**
     *
     * 主键
     * report_user_reg_month.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 注册会员数
     * report_user_reg_month.member_count
     *
     * @mbg.generated
     */
    private Integer memberCount;

    /**
     *
     * 注册商家数
     * report_user_reg_month.merchant_count
     *
     * @mbg.generated
     */
    private Integer merchantCount;

    /**
     *
     * 统计数据所属日期
     * report_user_reg_month.gmt_report
     *
     * @mbg.generated
     */
    private Date gmtReport;

    /**
     *
     * 统计时间
     * report_user_reg_month.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_user_reg_month
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_reg_month.id
     *
     * @return the value of report_user_reg_month.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_reg_month.id
     *
     * @param id the value for report_user_reg_month.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_reg_month.member_count
     *
     * @return the value of report_user_reg_month.member_count
     *
     * @mbg.generated
     */
    public Integer getMemberCount() {
        return memberCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_reg_month.member_count
     *
     * @param memberCount the value for report_user_reg_month.member_count
     *
     * @mbg.generated
     */
    public void setMemberCount(Integer memberCount) {
        this.memberCount = memberCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_reg_month.merchant_count
     *
     * @return the value of report_user_reg_month.merchant_count
     *
     * @mbg.generated
     */
    public Integer getMerchantCount() {
        return merchantCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_reg_month.merchant_count
     *
     * @param merchantCount the value for report_user_reg_month.merchant_count
     *
     * @mbg.generated
     */
    public void setMerchantCount(Integer merchantCount) {
        this.merchantCount = merchantCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_reg_month.gmt_report
     *
     * @return the value of report_user_reg_month.gmt_report
     *
     * @mbg.generated
     */
    public Date getGmtReport() {
        return gmtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_reg_month.gmt_report
     *
     * @param gmtReport the value for report_user_reg_month.gmt_report
     *
     * @mbg.generated
     */
    public void setGmtReport(Date gmtReport) {
        this.gmtReport = gmtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_reg_month.gmt_create
     *
     * @return the value of report_user_reg_month.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_reg_month.gmt_create
     *
     * @param gmtCreate the value for report_user_reg_month.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}