package com.lawu.eshop.statistics.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ReportAdEarningsDO implements Serializable {
    /**
     *
     * 主键
     * report_ad_earnings.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 广告id
     * report_ad_earnings.ad_id
     *
     * @mbg.generated
     */
    private Long adId;

    /**
     *
     * 商家编号
     * report_ad_earnings.merchant_num
     *
     * @mbg.generated
     */
    private String merchantNum;

    /**
     *
     * 商家名
     * report_ad_earnings.merchant_name
     *
     * @mbg.generated
     */
    private String merchantName;

    /**
     *
     * 广告名
     * report_ad_earnings.ad_title
     *
     * @mbg.generated
     */
    private String adTitle;

    /**
     *
     * 广告类型(1-平面2-视频3-抢赞4-红包)
     * report_ad_earnings.ad_type
     *
     * @mbg.generated
     */
    private Byte adType;

    /**
     *
     * 广告创建时间
     * report_ad_earnings.ad_create_time
     *
     * @mbg.generated
     */
    private Date adCreateTime;

    /**
     *
     * 状态(1-上架2-投放中3-投放结束)
     * report_ad_earnings.ad_status
     *
     * @mbg.generated
     */
    private Byte adStatus;

    /**
     *
     * 广告总投放积分
     * report_ad_earnings.ad_total_point
     *
     * @mbg.generated
     */
    private BigDecimal adTotalPoint;

    /**
     *
     * 用户总收益
     * report_ad_earnings.user_total_point
     *
     * @mbg.generated
     */
    private BigDecimal userTotalPoint;

    /**
     *
     * 爱心账户收益
     * report_ad_earnings.love_total_point
     *
     * @mbg.generated
     */
    private BigDecimal loveTotalPoint;

    /**
     *
     * 状态(0异常1正常)
     * report_ad_earnings.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 是否处理
     * report_ad_earnings.is_processed
     *
     * @mbg.generated
     */
    private Boolean isProcessed;

    /**
     *
     * 操作人员ID
     * report_ad_earnings.auditor_id
     *
     * @mbg.generated
     */
    private Long auditorId;

    /**
     *
     * 操作人员用户名
     * report_ad_earnings.auditor_account
     *
     * @mbg.generated
     */
    private String auditorAccount;

    /**
     *
     * 操作备注
     * report_ad_earnings.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * 操作时间
     * report_ad_earnings.audit_time
     *
     * @mbg.generated
     */
    private Date auditTime;

    /**
     *
     * 修改时间
     * report_ad_earnings.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * report_ad_earnings.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_ad_earnings
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.id
     *
     * @return the value of report_ad_earnings.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.id
     *
     * @param id the value for report_ad_earnings.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.ad_id
     *
     * @return the value of report_ad_earnings.ad_id
     *
     * @mbg.generated
     */
    public Long getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.ad_id
     *
     * @param adId the value for report_ad_earnings.ad_id
     *
     * @mbg.generated
     */
    public void setAdId(Long adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.merchant_num
     *
     * @return the value of report_ad_earnings.merchant_num
     *
     * @mbg.generated
     */
    public String getMerchantNum() {
        return merchantNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.merchant_num
     *
     * @param merchantNum the value for report_ad_earnings.merchant_num
     *
     * @mbg.generated
     */
    public void setMerchantNum(String merchantNum) {
        this.merchantNum = merchantNum == null ? null : merchantNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.merchant_name
     *
     * @return the value of report_ad_earnings.merchant_name
     *
     * @mbg.generated
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.merchant_name
     *
     * @param merchantName the value for report_ad_earnings.merchant_name
     *
     * @mbg.generated
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.ad_title
     *
     * @return the value of report_ad_earnings.ad_title
     *
     * @mbg.generated
     */
    public String getAdTitle() {
        return adTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.ad_title
     *
     * @param adTitle the value for report_ad_earnings.ad_title
     *
     * @mbg.generated
     */
    public void setAdTitle(String adTitle) {
        this.adTitle = adTitle == null ? null : adTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.ad_type
     *
     * @return the value of report_ad_earnings.ad_type
     *
     * @mbg.generated
     */
    public Byte getAdType() {
        return adType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.ad_type
     *
     * @param adType the value for report_ad_earnings.ad_type
     *
     * @mbg.generated
     */
    public void setAdType(Byte adType) {
        this.adType = adType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.ad_create_time
     *
     * @return the value of report_ad_earnings.ad_create_time
     *
     * @mbg.generated
     */
    public Date getAdCreateTime() {
        return adCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.ad_create_time
     *
     * @param adCreateTime the value for report_ad_earnings.ad_create_time
     *
     * @mbg.generated
     */
    public void setAdCreateTime(Date adCreateTime) {
        this.adCreateTime = adCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.ad_status
     *
     * @return the value of report_ad_earnings.ad_status
     *
     * @mbg.generated
     */
    public Byte getAdStatus() {
        return adStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.ad_status
     *
     * @param adStatus the value for report_ad_earnings.ad_status
     *
     * @mbg.generated
     */
    public void setAdStatus(Byte adStatus) {
        this.adStatus = adStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.ad_total_point
     *
     * @return the value of report_ad_earnings.ad_total_point
     *
     * @mbg.generated
     */
    public BigDecimal getAdTotalPoint() {
        return adTotalPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.ad_total_point
     *
     * @param adTotalPoint the value for report_ad_earnings.ad_total_point
     *
     * @mbg.generated
     */
    public void setAdTotalPoint(BigDecimal adTotalPoint) {
        this.adTotalPoint = adTotalPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.user_total_point
     *
     * @return the value of report_ad_earnings.user_total_point
     *
     * @mbg.generated
     */
    public BigDecimal getUserTotalPoint() {
        return userTotalPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.user_total_point
     *
     * @param userTotalPoint the value for report_ad_earnings.user_total_point
     *
     * @mbg.generated
     */
    public void setUserTotalPoint(BigDecimal userTotalPoint) {
        this.userTotalPoint = userTotalPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.love_total_point
     *
     * @return the value of report_ad_earnings.love_total_point
     *
     * @mbg.generated
     */
    public BigDecimal getLoveTotalPoint() {
        return loveTotalPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.love_total_point
     *
     * @param loveTotalPoint the value for report_ad_earnings.love_total_point
     *
     * @mbg.generated
     */
    public void setLoveTotalPoint(BigDecimal loveTotalPoint) {
        this.loveTotalPoint = loveTotalPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.status
     *
     * @return the value of report_ad_earnings.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.status
     *
     * @param status the value for report_ad_earnings.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.is_processed
     *
     * @return the value of report_ad_earnings.is_processed
     *
     * @mbg.generated
     */
    public Boolean getIsProcessed() {
        return isProcessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.is_processed
     *
     * @param isProcessed the value for report_ad_earnings.is_processed
     *
     * @mbg.generated
     */
    public void setIsProcessed(Boolean isProcessed) {
        this.isProcessed = isProcessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.auditor_id
     *
     * @return the value of report_ad_earnings.auditor_id
     *
     * @mbg.generated
     */
    public Long getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.auditor_id
     *
     * @param auditorId the value for report_ad_earnings.auditor_id
     *
     * @mbg.generated
     */
    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.auditor_account
     *
     * @return the value of report_ad_earnings.auditor_account
     *
     * @mbg.generated
     */
    public String getAuditorAccount() {
        return auditorAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.auditor_account
     *
     * @param auditorAccount the value for report_ad_earnings.auditor_account
     *
     * @mbg.generated
     */
    public void setAuditorAccount(String auditorAccount) {
        this.auditorAccount = auditorAccount == null ? null : auditorAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.remark
     *
     * @return the value of report_ad_earnings.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.remark
     *
     * @param remark the value for report_ad_earnings.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.audit_time
     *
     * @return the value of report_ad_earnings.audit_time
     *
     * @mbg.generated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.audit_time
     *
     * @param auditTime the value for report_ad_earnings.audit_time
     *
     * @mbg.generated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.gmt_modified
     *
     * @return the value of report_ad_earnings.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.gmt_modified
     *
     * @param gmtModified the value for report_ad_earnings.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_ad_earnings.gmt_create
     *
     * @return the value of report_ad_earnings.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_ad_earnings.gmt_create
     *
     * @param gmtCreate the value for report_ad_earnings.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}