package com.lawu.eshop.statistics.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class ReportUserActiveAreaMonthDO implements Serializable {
    /**
     *
     * 主键
     * report_user_active_area_month.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 活跃会员数
     * report_user_active_area_month.member_count
     *
     * @mbg.generated
     */
    private Integer memberCount;

    /**
     *
     * 活跃商家数
     * report_user_active_area_month.merchant_count
     *
     * @mbg.generated
     */
    private Integer merchantCount;

    /**
     *
     * 市级区域ID
     * report_user_active_area_month.city_id
     *
     * @mbg.generated
     */
    private Integer cityId;

    /**
     *
     * 市级名称
     * report_user_active_area_month.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * 统计数据所属年月
     * report_user_active_area_month.gmt_report
     *
     * @mbg.generated
     */
    private Date gmtReport;

    /**
     *
     * 统计时间
     * report_user_active_area_month.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_active_area_month.id
     *
     * @return the value of report_user_active_area_month.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_active_area_month.id
     *
     * @param id the value for report_user_active_area_month.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_active_area_month.member_count
     *
     * @return the value of report_user_active_area_month.member_count
     *
     * @mbg.generated
     */
    public Integer getMemberCount() {
        return memberCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_active_area_month.member_count
     *
     * @param memberCount the value for report_user_active_area_month.member_count
     *
     * @mbg.generated
     */
    public void setMemberCount(Integer memberCount) {
        this.memberCount = memberCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_active_area_month.merchant_count
     *
     * @return the value of report_user_active_area_month.merchant_count
     *
     * @mbg.generated
     */
    public Integer getMerchantCount() {
        return merchantCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_active_area_month.merchant_count
     *
     * @param merchantCount the value for report_user_active_area_month.merchant_count
     *
     * @mbg.generated
     */
    public void setMerchantCount(Integer merchantCount) {
        this.merchantCount = merchantCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_active_area_month.city_id
     *
     * @return the value of report_user_active_area_month.city_id
     *
     * @mbg.generated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_active_area_month.city_id
     *
     * @param cityId the value for report_user_active_area_month.city_id
     *
     * @mbg.generated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_active_area_month.city_name
     *
     * @return the value of report_user_active_area_month.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_active_area_month.city_name
     *
     * @param cityName the value for report_user_active_area_month.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_active_area_month.gmt_report
     *
     * @return the value of report_user_active_area_month.gmt_report
     *
     * @mbg.generated
     */
    public Date getGmtReport() {
        return gmtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_active_area_month.gmt_report
     *
     * @param gmtReport the value for report_user_active_area_month.gmt_report
     *
     * @mbg.generated
     */
    public void setGmtReport(Date gmtReport) {
        this.gmtReport = gmtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_user_active_area_month.gmt_create
     *
     * @return the value of report_user_active_area_month.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_user_active_area_month.gmt_create
     *
     * @param gmtCreate the value for report_user_active_area_month.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}