package com.lawu.eshop.operator.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class LogDO implements Serializable {
    /**
     *
     * 主键
     * log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 操作用户账号
     * log.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * 操作类型
     * log.operation_type
     *
     * @mbg.generated
     */
    private Byte operationType;

    /**
     *
     * 模块
     * log.module
     *
     * @mbg.generated
     */
    private Byte module;

    /**
     *
     * 业务id
     * log.business_id
     *
     * @mbg.generated
     */
    private String businessId;

    /**
     *
     * 变更标题
     * log.change_title
     *
     * @mbg.generated
     */
    private String changeTitle;

    /**
     *
     * 变更内容(JSON数据)
     * log.change_content
     *
     * @mbg.generated
     */
    private String changeContent;

    /**
     *
     * 创建时间
     * log.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.account
     *
     * @return the value of log.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.account
     *
     * @param account the value for log.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.operation_type
     *
     * @return the value of log.operation_type
     *
     * @mbg.generated
     */
    public Byte getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.operation_type
     *
     * @param operationType the value for log.operation_type
     *
     * @mbg.generated
     */
    public void setOperationType(Byte operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.module
     *
     * @return the value of log.module
     *
     * @mbg.generated
     */
    public Byte getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.module
     *
     * @param module the value for log.module
     *
     * @mbg.generated
     */
    public void setModule(Byte module) {
        this.module = module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.business_id
     *
     * @return the value of log.business_id
     *
     * @mbg.generated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.business_id
     *
     * @param businessId the value for log.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.change_title
     *
     * @return the value of log.change_title
     *
     * @mbg.generated
     */
    public String getChangeTitle() {
        return changeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.change_title
     *
     * @param changeTitle the value for log.change_title
     *
     * @mbg.generated
     */
    public void setChangeTitle(String changeTitle) {
        this.changeTitle = changeTitle == null ? null : changeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.change_content
     *
     * @return the value of log.change_content
     *
     * @mbg.generated
     */
    public String getChangeContent() {
        return changeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.change_content
     *
     * @param changeContent the value for log.change_content
     *
     * @mbg.generated
     */
    public void setChangeContent(String changeContent) {
        this.changeContent = changeContent == null ? null : changeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.gmt_create
     *
     * @return the value of log.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.gmt_create
     *
     * @param gmtCreate the value for log.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}