package com.lawu.eshop.activity.srv.mapper;

import com.lawu.eshop.activity.srv.domain.DrawLotteryActivityPrizeDO;
import com.lawu.eshop.activity.srv.domain.DrawLotteryActivityPrizeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DrawLotteryActivityPrizeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    long countByExample(DrawLotteryActivityPrizeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    int deleteByExample(DrawLotteryActivityPrizeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    int insert(DrawLotteryActivityPrizeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    int insertSelective(DrawLotteryActivityPrizeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    List<DrawLotteryActivityPrizeDO> selectByExampleWithRowbounds(DrawLotteryActivityPrizeDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    List<DrawLotteryActivityPrizeDO> selectByExample(DrawLotteryActivityPrizeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    DrawLotteryActivityPrizeDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DrawLotteryActivityPrizeDO record, @Param("example") DrawLotteryActivityPrizeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DrawLotteryActivityPrizeDO record, @Param("example") DrawLotteryActivityPrizeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DrawLotteryActivityPrizeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_prize
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DrawLotteryActivityPrizeDO record);
}