package com.lawu.eshop.activity.srv.mapper;

import com.lawu.eshop.activity.srv.domain.DrawLotteryActivityDO;
import com.lawu.eshop.activity.srv.domain.DrawLotteryActivityDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DrawLotteryActivityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    long countByExample(DrawLotteryActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    int deleteByExample(DrawLotteryActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    int insert(DrawLotteryActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    int insertSelective(DrawLotteryActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    List<DrawLotteryActivityDO> selectByExampleWithRowbounds(DrawLotteryActivityDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    List<DrawLotteryActivityDO> selectByExample(DrawLotteryActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    DrawLotteryActivityDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DrawLotteryActivityDO record, @Param("example") DrawLotteryActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DrawLotteryActivityDO record, @Param("example") DrawLotteryActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DrawLotteryActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DrawLotteryActivityDO record);
}