package com.lawu.eshop.activity.srv.mapper;

import com.lawu.eshop.activity.srv.domain.DrawLotteryActivityMonthRecordDO;
import com.lawu.eshop.activity.srv.domain.DrawLotteryActivityMonthRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DrawLotteryActivityMonthRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    long countByExample(DrawLotteryActivityMonthRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    int deleteByExample(DrawLotteryActivityMonthRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    int insert(DrawLotteryActivityMonthRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    int insertSelective(DrawLotteryActivityMonthRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    List<DrawLotteryActivityMonthRecordDO> selectByExampleWithRowbounds(DrawLotteryActivityMonthRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    List<DrawLotteryActivityMonthRecordDO> selectByExample(DrawLotteryActivityMonthRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    DrawLotteryActivityMonthRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DrawLotteryActivityMonthRecordDO record, @Param("example") DrawLotteryActivityMonthRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DrawLotteryActivityMonthRecordDO record, @Param("example") DrawLotteryActivityMonthRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DrawLotteryActivityMonthRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_lottery_activity_month_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DrawLotteryActivityMonthRecordDO record);
}