package com.lawu.eshop.activity.srv.mapper;

import com.lawu.eshop.activity.srv.domain.HelpRedpacketActivityDO;
import com.lawu.eshop.activity.srv.domain.HelpRedpacketActivityDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface HelpRedpacketActivityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    long countByExample(HelpRedpacketActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    int deleteByExample(HelpRedpacketActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    int insert(HelpRedpacketActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    int insertSelective(HelpRedpacketActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    List<HelpRedpacketActivityDO> selectByExampleWithRowbounds(HelpRedpacketActivityDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    List<HelpRedpacketActivityDO> selectByExample(HelpRedpacketActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    HelpRedpacketActivityDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HelpRedpacketActivityDO record, @Param("example") HelpRedpacketActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HelpRedpacketActivityDO record, @Param("example") HelpRedpacketActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HelpRedpacketActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_redpacket_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HelpRedpacketActivityDO record);
}