package com.lawu.eshop.activity.srv.mapper;

import com.lawu.eshop.activity.srv.domain.RedpacketSendRecordDO;
import com.lawu.eshop.activity.srv.domain.RedpacketSendRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RedpacketSendRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    int countByExample(RedpacketSendRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    int deleteByExample(RedpacketSendRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    int insert(RedpacketSendRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    int insertSelective(RedpacketSendRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    List<RedpacketSendRecordDO> selectByExampleWithRowbounds(RedpacketSendRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    List<RedpacketSendRecordDO> selectByExample(RedpacketSendRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    RedpacketSendRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RedpacketSendRecordDO record, @Param("example") RedpacketSendRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RedpacketSendRecordDO record, @Param("example") RedpacketSendRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RedpacketSendRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket_send_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RedpacketSendRecordDO record);
}