package com.lawu.eshop.activity.srv.mapper;

import com.lawu.eshop.activity.srv.domain.RichDiamondInfoDO;
import com.lawu.eshop.activity.srv.domain.RichDiamondInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RichDiamondInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    long countByExample(RichDiamondInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    int deleteByExample(RichDiamondInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    int insert(RichDiamondInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    int insertSelective(RichDiamondInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    List<RichDiamondInfoDO> selectByExampleWithRowbounds(RichDiamondInfoDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    List<RichDiamondInfoDO> selectByExample(RichDiamondInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    RichDiamondInfoDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RichDiamondInfoDO record, @Param("example") RichDiamondInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RichDiamondInfoDO record, @Param("example") RichDiamondInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RichDiamondInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RichDiamondInfoDO record);
}