package com.lawu.eshop.property.srv.mapper;

import com.lawu.eshop.property.srv.domain.PayPlatformLogDO;
import com.lawu.eshop.property.srv.domain.PayPlatformLogDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PayPlatformLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    long countByExample(PayPlatformLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    int deleteByExample(PayPlatformLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    int insert(PayPlatformLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    int insertSelective(PayPlatformLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    List<PayPlatformLogDO> selectByExampleWithBLOBsWithRowbounds(PayPlatformLogDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    List<PayPlatformLogDO> selectByExampleWithBLOBs(PayPlatformLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    List<PayPlatformLogDO> selectByExampleWithRowbounds(PayPlatformLogDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    List<PayPlatformLogDO> selectByExample(PayPlatformLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    PayPlatformLogDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PayPlatformLogDO record, @Param("example") PayPlatformLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PayPlatformLogDO record, @Param("example") PayPlatformLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PayPlatformLogDO record, @Param("example") PayPlatformLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayPlatformLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PayPlatformLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayPlatformLogDO record);
}