package com.lawu.eshop.property.srv.mapper;

import com.lawu.eshop.property.srv.domain.PropertyInfoDO;
import com.lawu.eshop.property.srv.domain.PropertyInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PropertyInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    int countByExample(PropertyInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    int deleteByExample(PropertyInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    int insert(PropertyInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    int insertSelective(PropertyInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    List<PropertyInfoDO> selectByExampleWithRowbounds(PropertyInfoDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    List<PropertyInfoDO> selectByExample(PropertyInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    PropertyInfoDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PropertyInfoDO record, @Param("example") PropertyInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PropertyInfoDO record, @Param("example") PropertyInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PropertyInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PropertyInfoDO record);
}