package com.lawu.eshop.activity.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class DrawLotteryActivityDO implements Serializable {
    /**
     *
     * 主键
     * draw_lottery_activity.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 活动名称
     * draw_lottery_activity.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * 活动图片
     * draw_lottery_activity.img_path
     *
     * @mbg.generated
     */
    private String imgPath;

    /**
     *
     * 参与等级
     * draw_lottery_activity.grade
     *
     * @mbg.generated
     */
    private Byte grade;

    /**
     *
     * 1--未发布，2--进行中，3--已发布，4--已结束，5--下架
     * draw_lottery_activity.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 活动说明
     * draw_lottery_activity.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * 开始时间
     * draw_lottery_activity.begin_time
     *
     * @mbg.generated
     */
    private Date beginTime;

    /**
     *
     * 结束时间
     * draw_lottery_activity.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * 修改时间
     * draw_lottery_activity.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * draw_lottery_activity.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table draw_lottery_activity
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_lottery_activity.id
     *
     * @return the value of draw_lottery_activity.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_lottery_activity.id
     *
     * @param id the value for draw_lottery_activity.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_lottery_activity.name
     *
     * @return the value of draw_lottery_activity.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_lottery_activity.name
     *
     * @param name the value for draw_lottery_activity.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_lottery_activity.img_path
     *
     * @return the value of draw_lottery_activity.img_path
     *
     * @mbg.generated
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_lottery_activity.img_path
     *
     * @param imgPath the value for draw_lottery_activity.img_path
     *
     * @mbg.generated
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_lottery_activity.grade
     *
     * @return the value of draw_lottery_activity.grade
     *
     * @mbg.generated
     */
    public Byte getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_lottery_activity.grade
     *
     * @param grade the value for draw_lottery_activity.grade
     *
     * @mbg.generated
     */
    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_lottery_activity.status
     *
     * @return the value of draw_lottery_activity.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_lottery_activity.status
     *
     * @param status the value for draw_lottery_activity.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_lottery_activity.remark
     *
     * @return the value of draw_lottery_activity.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_lottery_activity.remark
     *
     * @param remark the value for draw_lottery_activity.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_lottery_activity.begin_time
     *
     * @return the value of draw_lottery_activity.begin_time
     *
     * @mbg.generated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_lottery_activity.begin_time
     *
     * @param beginTime the value for draw_lottery_activity.begin_time
     *
     * @mbg.generated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_lottery_activity.end_time
     *
     * @return the value of draw_lottery_activity.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_lottery_activity.end_time
     *
     * @param endTime the value for draw_lottery_activity.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_lottery_activity.gmt_modified
     *
     * @return the value of draw_lottery_activity.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_lottery_activity.gmt_modified
     *
     * @param gmtModified the value for draw_lottery_activity.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_lottery_activity.gmt_create
     *
     * @return the value of draw_lottery_activity.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_lottery_activity.gmt_create
     *
     * @param gmtCreate the value for draw_lottery_activity.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}