package com.lawu.eshop.activity.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class HelpRedpacketInviteRecordDO implements Serializable {
    /**
     *
     * 主键
     * help_redpacket_invite_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 活动ID
     * help_redpacket_invite_record.activity_id
     *
     * @mbg.generated
     */
    private Integer activityId;

    /**
     *
     * 参与表ID
     * help_redpacket_invite_record.attend_id
     *
     * @mbg.generated
     */
    private Long attendId;

    /**
     *
     * 参与用户编号
     * help_redpacket_invite_record.attend_user_num
     *
     * @mbg.generated
     */
    private String attendUserNum;

    /**
     *
     * 助力用户编号
     * help_redpacket_invite_record.help_user_num
     *
     * @mbg.generated
     */
    private String helpUserNum;

    /**
     *
     * 助力用户账号
     * help_redpacket_invite_record.help_user_account
     *
     * @mbg.generated
     */
    private String helpUserAccount;

    /**
     *
     * 助力用户头像
     * help_redpacket_invite_record.help_user_headimg
     *
     * @mbg.generated
     */
    private String helpUserHeadimg;

    /**
     *
     * 助力方式（1-活动期间分享登陆助力|2-活动期间分享注册助力）
     * help_redpacket_invite_record.help_type
     *
     * @mbg.generated
     */
    private Byte helpType;

    /**
     *
     * 创建时间
     * help_redpacket_invite_record.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table help_redpacket_invite_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_redpacket_invite_record.id
     *
     * @return the value of help_redpacket_invite_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_redpacket_invite_record.id
     *
     * @param id the value for help_redpacket_invite_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_redpacket_invite_record.activity_id
     *
     * @return the value of help_redpacket_invite_record.activity_id
     *
     * @mbg.generated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_redpacket_invite_record.activity_id
     *
     * @param activityId the value for help_redpacket_invite_record.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_redpacket_invite_record.attend_id
     *
     * @return the value of help_redpacket_invite_record.attend_id
     *
     * @mbg.generated
     */
    public Long getAttendId() {
        return attendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_redpacket_invite_record.attend_id
     *
     * @param attendId the value for help_redpacket_invite_record.attend_id
     *
     * @mbg.generated
     */
    public void setAttendId(Long attendId) {
        this.attendId = attendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_redpacket_invite_record.attend_user_num
     *
     * @return the value of help_redpacket_invite_record.attend_user_num
     *
     * @mbg.generated
     */
    public String getAttendUserNum() {
        return attendUserNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_redpacket_invite_record.attend_user_num
     *
     * @param attendUserNum the value for help_redpacket_invite_record.attend_user_num
     *
     * @mbg.generated
     */
    public void setAttendUserNum(String attendUserNum) {
        this.attendUserNum = attendUserNum == null ? null : attendUserNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_redpacket_invite_record.help_user_num
     *
     * @return the value of help_redpacket_invite_record.help_user_num
     *
     * @mbg.generated
     */
    public String getHelpUserNum() {
        return helpUserNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_redpacket_invite_record.help_user_num
     *
     * @param helpUserNum the value for help_redpacket_invite_record.help_user_num
     *
     * @mbg.generated
     */
    public void setHelpUserNum(String helpUserNum) {
        this.helpUserNum = helpUserNum == null ? null : helpUserNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_redpacket_invite_record.help_user_account
     *
     * @return the value of help_redpacket_invite_record.help_user_account
     *
     * @mbg.generated
     */
    public String getHelpUserAccount() {
        return helpUserAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_redpacket_invite_record.help_user_account
     *
     * @param helpUserAccount the value for help_redpacket_invite_record.help_user_account
     *
     * @mbg.generated
     */
    public void setHelpUserAccount(String helpUserAccount) {
        this.helpUserAccount = helpUserAccount == null ? null : helpUserAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_redpacket_invite_record.help_user_headimg
     *
     * @return the value of help_redpacket_invite_record.help_user_headimg
     *
     * @mbg.generated
     */
    public String getHelpUserHeadimg() {
        return helpUserHeadimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_redpacket_invite_record.help_user_headimg
     *
     * @param helpUserHeadimg the value for help_redpacket_invite_record.help_user_headimg
     *
     * @mbg.generated
     */
    public void setHelpUserHeadimg(String helpUserHeadimg) {
        this.helpUserHeadimg = helpUserHeadimg == null ? null : helpUserHeadimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_redpacket_invite_record.help_type
     *
     * @return the value of help_redpacket_invite_record.help_type
     *
     * @mbg.generated
     */
    public Byte getHelpType() {
        return helpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_redpacket_invite_record.help_type
     *
     * @param helpType the value for help_redpacket_invite_record.help_type
     *
     * @mbg.generated
     */
    public void setHelpType(Byte helpType) {
        this.helpType = helpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_redpacket_invite_record.gmt_create
     *
     * @return the value of help_redpacket_invite_record.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_redpacket_invite_record.gmt_create
     *
     * @param gmtCreate the value for help_redpacket_invite_record.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}