package com.lawu.eshop.activity.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RichDiamondInfoDO implements Serializable {
    /**
     *
     * 主键
     * rich_diamond_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 已发放E钻数量
     * rich_diamond_info.diamond_sent
     *
     * @mbg.generated
     */
    private BigDecimal diamondSent;

    /**
     *
     * 已发放幸运钻数量
     * rich_diamond_info.diamond_lucky_sent
     *
     * @mbg.generated
     */
    private BigDecimal diamondLuckySent;

    /**
     *
     * 更新时间
     * rich_diamond_info.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * rich_diamond_info.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rich_diamond_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_diamond_info.id
     *
     * @return the value of rich_diamond_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_diamond_info.id
     *
     * @param id the value for rich_diamond_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_diamond_info.diamond_sent
     *
     * @return the value of rich_diamond_info.diamond_sent
     *
     * @mbg.generated
     */
    public BigDecimal getDiamondSent() {
        return diamondSent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_diamond_info.diamond_sent
     *
     * @param diamondSent the value for rich_diamond_info.diamond_sent
     *
     * @mbg.generated
     */
    public void setDiamondSent(BigDecimal diamondSent) {
        this.diamondSent = diamondSent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_diamond_info.diamond_lucky_sent
     *
     * @return the value of rich_diamond_info.diamond_lucky_sent
     *
     * @mbg.generated
     */
    public BigDecimal getDiamondLuckySent() {
        return diamondLuckySent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_diamond_info.diamond_lucky_sent
     *
     * @param diamondLuckySent the value for rich_diamond_info.diamond_lucky_sent
     *
     * @mbg.generated
     */
    public void setDiamondLuckySent(BigDecimal diamondLuckySent) {
        this.diamondLuckySent = diamondLuckySent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_diamond_info.gmt_modified
     *
     * @return the value of rich_diamond_info.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_diamond_info.gmt_modified
     *
     * @param gmtModified the value for rich_diamond_info.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_diamond_info.gmt_create
     *
     * @return the value of rich_diamond_info.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_diamond_info.gmt_create
     *
     * @param gmtCreate the value for rich_diamond_info.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}