package com.lawu.eshop.activity.srv.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RichDiamondDistributionRecordDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    public RichDiamondDistributionRecordDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andResidentsIsNull() {
            addCriterion("residents is null");
            return (Criteria) this;
        }

        public Criteria andResidentsIsNotNull() {
            addCriterion("residents is not null");
            return (Criteria) this;
        }

        public Criteria andResidentsEqualTo(Long value) {
            addCriterion("residents =", value, "residents");
            return (Criteria) this;
        }

        public Criteria andResidentsNotEqualTo(Long value) {
            addCriterion("residents <>", value, "residents");
            return (Criteria) this;
        }

        public Criteria andResidentsGreaterThan(Long value) {
            addCriterion("residents >", value, "residents");
            return (Criteria) this;
        }

        public Criteria andResidentsGreaterThanOrEqualTo(Long value) {
            addCriterion("residents >=", value, "residents");
            return (Criteria) this;
        }

        public Criteria andResidentsLessThan(Long value) {
            addCriterion("residents <", value, "residents");
            return (Criteria) this;
        }

        public Criteria andResidentsLessThanOrEqualTo(Long value) {
            addCriterion("residents <=", value, "residents");
            return (Criteria) this;
        }

        public Criteria andResidentsIn(List<Long> values) {
            addCriterion("residents in", values, "residents");
            return (Criteria) this;
        }

        public Criteria andResidentsNotIn(List<Long> values) {
            addCriterion("residents not in", values, "residents");
            return (Criteria) this;
        }

        public Criteria andResidentsBetween(Long value1, Long value2) {
            addCriterion("residents between", value1, value2, "residents");
            return (Criteria) this;
        }

        public Criteria andResidentsNotBetween(Long value1, Long value2) {
            addCriterion("residents not between", value1, value2, "residents");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsIsNull() {
            addCriterion("allocated_residents is null");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsIsNotNull() {
            addCriterion("allocated_residents is not null");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsEqualTo(Long value) {
            addCriterion("allocated_residents =", value, "allocatedResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsNotEqualTo(Long value) {
            addCriterion("allocated_residents <>", value, "allocatedResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsGreaterThan(Long value) {
            addCriterion("allocated_residents >", value, "allocatedResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsGreaterThanOrEqualTo(Long value) {
            addCriterion("allocated_residents >=", value, "allocatedResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsLessThan(Long value) {
            addCriterion("allocated_residents <", value, "allocatedResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsLessThanOrEqualTo(Long value) {
            addCriterion("allocated_residents <=", value, "allocatedResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsIn(List<Long> values) {
            addCriterion("allocated_residents in", values, "allocatedResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsNotIn(List<Long> values) {
            addCriterion("allocated_residents not in", values, "allocatedResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsBetween(Long value1, Long value2) {
            addCriterion("allocated_residents between", value1, value2, "allocatedResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedResidentsNotBetween(Long value1, Long value2) {
            addCriterion("allocated_residents not between", value1, value2, "allocatedResidents");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsIsNull() {
            addCriterion("expected_ordinary_allocations is null");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsIsNotNull() {
            addCriterion("expected_ordinary_allocations is not null");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsEqualTo(BigDecimal value) {
            addCriterion("expected_ordinary_allocations =", value, "expectedOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsNotEqualTo(BigDecimal value) {
            addCriterion("expected_ordinary_allocations <>", value, "expectedOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsGreaterThan(BigDecimal value) {
            addCriterion("expected_ordinary_allocations >", value, "expectedOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("expected_ordinary_allocations >=", value, "expectedOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsLessThan(BigDecimal value) {
            addCriterion("expected_ordinary_allocations <", value, "expectedOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("expected_ordinary_allocations <=", value, "expectedOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsIn(List<BigDecimal> values) {
            addCriterion("expected_ordinary_allocations in", values, "expectedOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsNotIn(List<BigDecimal> values) {
            addCriterion("expected_ordinary_allocations not in", values, "expectedOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("expected_ordinary_allocations between", value1, value2, "expectedOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedOrdinaryAllocationsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("expected_ordinary_allocations not between", value1, value2, "expectedOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsIsNull() {
            addCriterion("real_ordinary_allocations is null");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsIsNotNull() {
            addCriterion("real_ordinary_allocations is not null");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsEqualTo(BigDecimal value) {
            addCriterion("real_ordinary_allocations =", value, "realOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsNotEqualTo(BigDecimal value) {
            addCriterion("real_ordinary_allocations <>", value, "realOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsGreaterThan(BigDecimal value) {
            addCriterion("real_ordinary_allocations >", value, "realOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("real_ordinary_allocations >=", value, "realOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsLessThan(BigDecimal value) {
            addCriterion("real_ordinary_allocations <", value, "realOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("real_ordinary_allocations <=", value, "realOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsIn(List<BigDecimal> values) {
            addCriterion("real_ordinary_allocations in", values, "realOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsNotIn(List<BigDecimal> values) {
            addCriterion("real_ordinary_allocations not in", values, "realOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_ordinary_allocations between", value1, value2, "realOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andRealOrdinaryAllocationsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_ordinary_allocations not between", value1, value2, "realOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsIsNull() {
            addCriterion("merchant_real_ordinary_allocations is null");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsIsNotNull() {
            addCriterion("merchant_real_ordinary_allocations is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsEqualTo(BigDecimal value) {
            addCriterion("merchant_real_ordinary_allocations =", value, "merchantRealOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsNotEqualTo(BigDecimal value) {
            addCriterion("merchant_real_ordinary_allocations <>", value, "merchantRealOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsGreaterThan(BigDecimal value) {
            addCriterion("merchant_real_ordinary_allocations >", value, "merchantRealOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("merchant_real_ordinary_allocations >=", value, "merchantRealOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsLessThan(BigDecimal value) {
            addCriterion("merchant_real_ordinary_allocations <", value, "merchantRealOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("merchant_real_ordinary_allocations <=", value, "merchantRealOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsIn(List<BigDecimal> values) {
            addCriterion("merchant_real_ordinary_allocations in", values, "merchantRealOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsNotIn(List<BigDecimal> values) {
            addCriterion("merchant_real_ordinary_allocations not in", values, "merchantRealOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("merchant_real_ordinary_allocations between", value1, value2, "merchantRealOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealOrdinaryAllocationsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("merchant_real_ordinary_allocations not between", value1, value2, "merchantRealOrdinaryAllocations");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsIsNull() {
            addCriterion("lucky_residents is null");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsIsNotNull() {
            addCriterion("lucky_residents is not null");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsEqualTo(Long value) {
            addCriterion("lucky_residents =", value, "luckyResidents");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsNotEqualTo(Long value) {
            addCriterion("lucky_residents <>", value, "luckyResidents");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsGreaterThan(Long value) {
            addCriterion("lucky_residents >", value, "luckyResidents");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsGreaterThanOrEqualTo(Long value) {
            addCriterion("lucky_residents >=", value, "luckyResidents");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsLessThan(Long value) {
            addCriterion("lucky_residents <", value, "luckyResidents");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsLessThanOrEqualTo(Long value) {
            addCriterion("lucky_residents <=", value, "luckyResidents");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsIn(List<Long> values) {
            addCriterion("lucky_residents in", values, "luckyResidents");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsNotIn(List<Long> values) {
            addCriterion("lucky_residents not in", values, "luckyResidents");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsBetween(Long value1, Long value2) {
            addCriterion("lucky_residents between", value1, value2, "luckyResidents");
            return (Criteria) this;
        }

        public Criteria andLuckyResidentsNotBetween(Long value1, Long value2) {
            addCriterion("lucky_residents not between", value1, value2, "luckyResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsIsNull() {
            addCriterion("allocated_lucky_residents is null");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsIsNotNull() {
            addCriterion("allocated_lucky_residents is not null");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsEqualTo(Long value) {
            addCriterion("allocated_lucky_residents =", value, "allocatedLuckyResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsNotEqualTo(Long value) {
            addCriterion("allocated_lucky_residents <>", value, "allocatedLuckyResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsGreaterThan(Long value) {
            addCriterion("allocated_lucky_residents >", value, "allocatedLuckyResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsGreaterThanOrEqualTo(Long value) {
            addCriterion("allocated_lucky_residents >=", value, "allocatedLuckyResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsLessThan(Long value) {
            addCriterion("allocated_lucky_residents <", value, "allocatedLuckyResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsLessThanOrEqualTo(Long value) {
            addCriterion("allocated_lucky_residents <=", value, "allocatedLuckyResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsIn(List<Long> values) {
            addCriterion("allocated_lucky_residents in", values, "allocatedLuckyResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsNotIn(List<Long> values) {
            addCriterion("allocated_lucky_residents not in", values, "allocatedLuckyResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsBetween(Long value1, Long value2) {
            addCriterion("allocated_lucky_residents between", value1, value2, "allocatedLuckyResidents");
            return (Criteria) this;
        }

        public Criteria andAllocatedLuckyResidentsNotBetween(Long value1, Long value2) {
            addCriterion("allocated_lucky_residents not between", value1, value2, "allocatedLuckyResidents");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsIsNull() {
            addCriterion("expected_lucky_allocations is null");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsIsNotNull() {
            addCriterion("expected_lucky_allocations is not null");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsEqualTo(BigDecimal value) {
            addCriterion("expected_lucky_allocations =", value, "expectedLuckyAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsNotEqualTo(BigDecimal value) {
            addCriterion("expected_lucky_allocations <>", value, "expectedLuckyAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsGreaterThan(BigDecimal value) {
            addCriterion("expected_lucky_allocations >", value, "expectedLuckyAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("expected_lucky_allocations >=", value, "expectedLuckyAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsLessThan(BigDecimal value) {
            addCriterion("expected_lucky_allocations <", value, "expectedLuckyAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("expected_lucky_allocations <=", value, "expectedLuckyAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsIn(List<BigDecimal> values) {
            addCriterion("expected_lucky_allocations in", values, "expectedLuckyAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsNotIn(List<BigDecimal> values) {
            addCriterion("expected_lucky_allocations not in", values, "expectedLuckyAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("expected_lucky_allocations between", value1, value2, "expectedLuckyAllocations");
            return (Criteria) this;
        }

        public Criteria andExpectedLuckyAllocationsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("expected_lucky_allocations not between", value1, value2, "expectedLuckyAllocations");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsIsNull() {
            addCriterion("real_luck_allocations is null");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsIsNotNull() {
            addCriterion("real_luck_allocations is not null");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsEqualTo(BigDecimal value) {
            addCriterion("real_luck_allocations =", value, "realLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsNotEqualTo(BigDecimal value) {
            addCriterion("real_luck_allocations <>", value, "realLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsGreaterThan(BigDecimal value) {
            addCriterion("real_luck_allocations >", value, "realLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("real_luck_allocations >=", value, "realLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsLessThan(BigDecimal value) {
            addCriterion("real_luck_allocations <", value, "realLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("real_luck_allocations <=", value, "realLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsIn(List<BigDecimal> values) {
            addCriterion("real_luck_allocations in", values, "realLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsNotIn(List<BigDecimal> values) {
            addCriterion("real_luck_allocations not in", values, "realLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_luck_allocations between", value1, value2, "realLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andRealLuckAllocationsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_luck_allocations not between", value1, value2, "realLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsIsNull() {
            addCriterion("merchant_real_luck_allocations is null");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsIsNotNull() {
            addCriterion("merchant_real_luck_allocations is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsEqualTo(BigDecimal value) {
            addCriterion("merchant_real_luck_allocations =", value, "merchantRealLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsNotEqualTo(BigDecimal value) {
            addCriterion("merchant_real_luck_allocations <>", value, "merchantRealLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsGreaterThan(BigDecimal value) {
            addCriterion("merchant_real_luck_allocations >", value, "merchantRealLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("merchant_real_luck_allocations >=", value, "merchantRealLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsLessThan(BigDecimal value) {
            addCriterion("merchant_real_luck_allocations <", value, "merchantRealLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("merchant_real_luck_allocations <=", value, "merchantRealLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsIn(List<BigDecimal> values) {
            addCriterion("merchant_real_luck_allocations in", values, "merchantRealLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsNotIn(List<BigDecimal> values) {
            addCriterion("merchant_real_luck_allocations not in", values, "merchantRealLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("merchant_real_luck_allocations between", value1, value2, "merchantRealLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andMerchantRealLuckAllocationsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("merchant_real_luck_allocations not between", value1, value2, "merchantRealLuckAllocations");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteIsNull() {
            addCriterion("gmt_allocations_complete is null");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteIsNotNull() {
            addCriterion("gmt_allocations_complete is not null");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteEqualTo(Date value) {
            addCriterion("gmt_allocations_complete =", value, "gmtAllocationsComplete");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteNotEqualTo(Date value) {
            addCriterion("gmt_allocations_complete <>", value, "gmtAllocationsComplete");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteGreaterThan(Date value) {
            addCriterion("gmt_allocations_complete >", value, "gmtAllocationsComplete");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_allocations_complete >=", value, "gmtAllocationsComplete");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteLessThan(Date value) {
            addCriterion("gmt_allocations_complete <", value, "gmtAllocationsComplete");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteLessThanOrEqualTo(Date value) {
            addCriterion("gmt_allocations_complete <=", value, "gmtAllocationsComplete");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteIn(List<Date> values) {
            addCriterion("gmt_allocations_complete in", values, "gmtAllocationsComplete");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteNotIn(List<Date> values) {
            addCriterion("gmt_allocations_complete not in", values, "gmtAllocationsComplete");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteBetween(Date value1, Date value2) {
            addCriterion("gmt_allocations_complete between", value1, value2, "gmtAllocationsComplete");
            return (Criteria) this;
        }

        public Criteria andGmtAllocationsCompleteNotBetween(Date value1, Date value2) {
            addCriterion("gmt_allocations_complete not between", value1, value2, "gmtAllocationsComplete");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteIsNull() {
            addCriterion("gmt_grant_complete is null");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteIsNotNull() {
            addCriterion("gmt_grant_complete is not null");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteEqualTo(Date value) {
            addCriterion("gmt_grant_complete =", value, "gmtGrantComplete");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteNotEqualTo(Date value) {
            addCriterion("gmt_grant_complete <>", value, "gmtGrantComplete");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteGreaterThan(Date value) {
            addCriterion("gmt_grant_complete >", value, "gmtGrantComplete");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_grant_complete >=", value, "gmtGrantComplete");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteLessThan(Date value) {
            addCriterion("gmt_grant_complete <", value, "gmtGrantComplete");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteLessThanOrEqualTo(Date value) {
            addCriterion("gmt_grant_complete <=", value, "gmtGrantComplete");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteIn(List<Date> values) {
            addCriterion("gmt_grant_complete in", values, "gmtGrantComplete");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteNotIn(List<Date> values) {
            addCriterion("gmt_grant_complete not in", values, "gmtGrantComplete");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteBetween(Date value1, Date value2) {
            addCriterion("gmt_grant_complete between", value1, value2, "gmtGrantComplete");
            return (Criteria) this;
        }

        public Criteria andGmtGrantCompleteNotBetween(Date value1, Date value2) {
            addCriterion("gmt_grant_complete not between", value1, value2, "gmtGrantComplete");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rich_diamond_distribution_record
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}