package com.lawu.eshop.activity.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class RichPowerRecordDO implements Serializable {
    /**
     *
     * 主键
     * rich_power_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 用户编号
     * rich_power_record.user_num
     *
     * @mbg.generated
     */
    private String userNum;

    /**
     *
     * 标题
     * rich_power_record.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * 来源 1-登录 2-邀请E友 3-娱乐 4-看广告 5-购物 6-绑定支付宝 7-身份认证 8-幸运钻领取消耗
     * rich_power_record.source
     *
     * @mbg.generated
     */
    private Byte source;

    /**
     *
     * 1-支出 2-收入
     * rich_power_record.direction
     *
     * @mbg.generated
     */
    private Byte direction;

    /**
     *
     * 挖矿动力值
     * rich_power_record.power
     *
     * @mbg.generated
     */
    private Integer power;

    /**
     *
     * 创建时间
     * rich_power_record.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rich_power_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_power_record.id
     *
     * @return the value of rich_power_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_power_record.id
     *
     * @param id the value for rich_power_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_power_record.user_num
     *
     * @return the value of rich_power_record.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_power_record.user_num
     *
     * @param userNum the value for rich_power_record.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_power_record.title
     *
     * @return the value of rich_power_record.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_power_record.title
     *
     * @param title the value for rich_power_record.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_power_record.source
     *
     * @return the value of rich_power_record.source
     *
     * @mbg.generated
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_power_record.source
     *
     * @param source the value for rich_power_record.source
     *
     * @mbg.generated
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_power_record.direction
     *
     * @return the value of rich_power_record.direction
     *
     * @mbg.generated
     */
    public Byte getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_power_record.direction
     *
     * @param direction the value for rich_power_record.direction
     *
     * @mbg.generated
     */
    public void setDirection(Byte direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_power_record.power
     *
     * @return the value of rich_power_record.power
     *
     * @mbg.generated
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_power_record.power
     *
     * @param power the value for rich_power_record.power
     *
     * @mbg.generated
     */
    public void setPower(Integer power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_power_record.gmt_create
     *
     * @return the value of rich_power_record.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_power_record.gmt_create
     *
     * @param gmtCreate the value for rich_power_record.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}