package com.lawu.eshop.activity.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RichAccountDO implements Serializable {
    /**
     *
     * 主键
     * rich_account.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 用户编号
     * rich_account.user_num
     *
     * @mbg.generated
     */
    private String userNum;

    /**
     *
     * 用户类型
     * rich_account.user_type
     *
     * @mbg.generated
     */
    private Byte userType;

    /**
     *
     * 创建序号
     * rich_account.order_num
     *
     * @mbg.generated
     */
    private Integer orderNum;

    /**
     *
     * 姓名
     * rich_account.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * 身份证号码
     * rich_account.id_card_num
     *
     * @mbg.generated
     */
    private String idCardNum;

    /**
     *
     * E钻数量
     * rich_account.diamond
     *
     * @mbg.generated
     */
    private BigDecimal diamond;

    /**
     *
     * 幸运钻数量
     * rich_account.diamond_lucky
     *
     * @mbg.generated
     */
    private BigDecimal diamondLucky;

    /**
     *
     * E钻总量
     * rich_account.diamond_total
     *
     * @mbg.generated
     */
    private BigDecimal diamondTotal;

    /**
     *
     * 挖矿动力值
     * rich_account.power
     *
     * @mbg.generated
     */
    private Integer power;

    /**
     *
     * 挖矿动力值快照
     * rich_account.power_snapshoot
     *
     * @mbg.generated
     */
    private Integer powerSnapshoot;

    /**
     *
     * 支付宝绑定ID
     * rich_account.alipay_user_id
     *
     * @mbg.generated
     */
    private String alipayUserId;

    /**
     *
     * 支付宝绑定时间
     * rich_account.alipay_bind_time
     *
     * @mbg.generated
     */
    private Date alipayBindTime;

    /**
     *
     * 最后领取时间
     * rich_account.last_take_time
     *
     * @mbg.generated
     */
    private Date lastTakeTime;

    /**
     *
     * 更新时间
     * rich_account.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * rich_account.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rich_account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.id
     *
     * @return the value of rich_account.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.id
     *
     * @param id the value for rich_account.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.user_num
     *
     * @return the value of rich_account.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.user_num
     *
     * @param userNum the value for rich_account.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.user_type
     *
     * @return the value of rich_account.user_type
     *
     * @mbg.generated
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.user_type
     *
     * @param userType the value for rich_account.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.order_num
     *
     * @return the value of rich_account.order_num
     *
     * @mbg.generated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.order_num
     *
     * @param orderNum the value for rich_account.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.name
     *
     * @return the value of rich_account.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.name
     *
     * @param name the value for rich_account.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.id_card_num
     *
     * @return the value of rich_account.id_card_num
     *
     * @mbg.generated
     */
    public String getIdCardNum() {
        return idCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.id_card_num
     *
     * @param idCardNum the value for rich_account.id_card_num
     *
     * @mbg.generated
     */
    public void setIdCardNum(String idCardNum) {
        this.idCardNum = idCardNum == null ? null : idCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.diamond
     *
     * @return the value of rich_account.diamond
     *
     * @mbg.generated
     */
    public BigDecimal getDiamond() {
        return diamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.diamond
     *
     * @param diamond the value for rich_account.diamond
     *
     * @mbg.generated
     */
    public void setDiamond(BigDecimal diamond) {
        this.diamond = diamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.diamond_lucky
     *
     * @return the value of rich_account.diamond_lucky
     *
     * @mbg.generated
     */
    public BigDecimal getDiamondLucky() {
        return diamondLucky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.diamond_lucky
     *
     * @param diamondLucky the value for rich_account.diamond_lucky
     *
     * @mbg.generated
     */
    public void setDiamondLucky(BigDecimal diamondLucky) {
        this.diamondLucky = diamondLucky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.diamond_total
     *
     * @return the value of rich_account.diamond_total
     *
     * @mbg.generated
     */
    public BigDecimal getDiamondTotal() {
        return diamondTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.diamond_total
     *
     * @param diamondTotal the value for rich_account.diamond_total
     *
     * @mbg.generated
     */
    public void setDiamondTotal(BigDecimal diamondTotal) {
        this.diamondTotal = diamondTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.power
     *
     * @return the value of rich_account.power
     *
     * @mbg.generated
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.power
     *
     * @param power the value for rich_account.power
     *
     * @mbg.generated
     */
    public void setPower(Integer power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.power_snapshoot
     *
     * @return the value of rich_account.power_snapshoot
     *
     * @mbg.generated
     */
    public Integer getPowerSnapshoot() {
        return powerSnapshoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.power_snapshoot
     *
     * @param powerSnapshoot the value for rich_account.power_snapshoot
     *
     * @mbg.generated
     */
    public void setPowerSnapshoot(Integer powerSnapshoot) {
        this.powerSnapshoot = powerSnapshoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.alipay_user_id
     *
     * @return the value of rich_account.alipay_user_id
     *
     * @mbg.generated
     */
    public String getAlipayUserId() {
        return alipayUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.alipay_user_id
     *
     * @param alipayUserId the value for rich_account.alipay_user_id
     *
     * @mbg.generated
     */
    public void setAlipayUserId(String alipayUserId) {
        this.alipayUserId = alipayUserId == null ? null : alipayUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.alipay_bind_time
     *
     * @return the value of rich_account.alipay_bind_time
     *
     * @mbg.generated
     */
    public Date getAlipayBindTime() {
        return alipayBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.alipay_bind_time
     *
     * @param alipayBindTime the value for rich_account.alipay_bind_time
     *
     * @mbg.generated
     */
    public void setAlipayBindTime(Date alipayBindTime) {
        this.alipayBindTime = alipayBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.last_take_time
     *
     * @return the value of rich_account.last_take_time
     *
     * @mbg.generated
     */
    public Date getLastTakeTime() {
        return lastTakeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.last_take_time
     *
     * @param lastTakeTime the value for rich_account.last_take_time
     *
     * @mbg.generated
     */
    public void setLastTakeTime(Date lastTakeTime) {
        this.lastTakeTime = lastTakeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.gmt_modified
     *
     * @return the value of rich_account.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.gmt_modified
     *
     * @param gmtModified the value for rich_account.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rich_account.gmt_create
     *
     * @return the value of rich_account.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rich_account.gmt_create
     *
     * @param gmtCreate the value for rich_account.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}