package com.lawu.eshop.product.srv.mapper;

import com.lawu.eshop.product.srv.domain.ProductCustomSpecDO;
import com.lawu.eshop.product.srv.domain.ProductCustomSpecDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProductCustomSpecDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    long countByExample(ProductCustomSpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    int deleteByExample(ProductCustomSpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    int insert(ProductCustomSpecDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    int insertSelective(ProductCustomSpecDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    List<ProductCustomSpecDO> selectByExampleWithRowbounds(ProductCustomSpecDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    List<ProductCustomSpecDO> selectByExample(ProductCustomSpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    ProductCustomSpecDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductCustomSpecDO record, @Param("example") ProductCustomSpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductCustomSpecDO record, @Param("example") ProductCustomSpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductCustomSpecDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_custom_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductCustomSpecDO record);
}