package com.lawu.eshop.product.srv.mapper;

import com.lawu.eshop.product.srv.domain.ProductBrandDO;
import com.lawu.eshop.product.srv.domain.ProductBrandDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProductBrandDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    long countByExample(ProductBrandDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    int deleteByExample(ProductBrandDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    int insert(ProductBrandDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    int insertSelective(ProductBrandDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    List<ProductBrandDO> selectByExampleWithRowbounds(ProductBrandDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    List<ProductBrandDO> selectByExample(ProductBrandDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    ProductBrandDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductBrandDO record, @Param("example") ProductBrandDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductBrandDO record, @Param("example") ProductBrandDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductBrandDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductBrandDO record);
}