package com.lawu.eshop.product.srv.mapper;

import com.lawu.eshop.product.srv.domain.SeckillActivityDO;
import com.lawu.eshop.product.srv.domain.SeckillActivityDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SeckillActivityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    long countByExample(SeckillActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    int deleteByExample(SeckillActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    int insert(SeckillActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    int insertSelective(SeckillActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    List<SeckillActivityDO> selectByExampleWithRowbounds(SeckillActivityDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    List<SeckillActivityDO> selectByExample(SeckillActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    SeckillActivityDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SeckillActivityDO record, @Param("example") SeckillActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SeckillActivityDO record, @Param("example") SeckillActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SeckillActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SeckillActivityDO record);
}