package com.lawu.eshop.product.srv.mapper;

import com.lawu.eshop.product.srv.domain.SeckillActivityProductModelDO;
import com.lawu.eshop.product.srv.domain.SeckillActivityProductModelDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SeckillActivityProductModelDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    long countByExample(SeckillActivityProductModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    int deleteByExample(SeckillActivityProductModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    int insert(SeckillActivityProductModelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    int insertSelective(SeckillActivityProductModelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    List<SeckillActivityProductModelDO> selectByExampleWithRowbounds(SeckillActivityProductModelDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    List<SeckillActivityProductModelDO> selectByExample(SeckillActivityProductModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    SeckillActivityProductModelDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SeckillActivityProductModelDO record, @Param("example") SeckillActivityProductModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SeckillActivityProductModelDO record, @Param("example") SeckillActivityProductModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SeckillActivityProductModelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_activity_product_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SeckillActivityProductModelDO record);
}