package com.lawu.eshop.mall.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class CommentProductDO implements Serializable {
    /**
     *
     * 主键
     * comment_product.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 评价内容
     * comment_product.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * 商家回复内容
     * comment_product.reply_content
     *
     * @mbg.generated
     */
    private String replyContent;

    /**
     *
     * 评分1~5星
     * comment_product.grade
     *
     * @mbg.generated
     */
    private Byte grade;

    /**
     *
     * 用户
     * comment_product.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * 商家ID
     * comment_product.merchant_id
     *
     * @mbg.generated
     */
    private Long merchantId;

    /**
     *
     * 商品
     * comment_product.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * 订单项ID
     * comment_product.order_item_id
     *
     * @mbg.generated
     */
    private Long orderItemId;

    /**
     *
     * 商品型号id
     * comment_product.product_model_id
     *
     * @mbg.generated
     */
    private Long productModelId;

    /**
     *
     * 是否匿名（0：否1：是）
     * comment_product.is_anonymous
     *
     * @mbg.generated
     */
    private Boolean isAnonymous;

    /**
     *
     * 状态（1：有效0：无效）
     * comment_product.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 是否存在图片
     * comment_product.is_have_img
     *
     * @mbg.generated
     */
    private Boolean isHaveImg;

    /**
     *
     * 修改时间
     * comment_product.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * comment_product.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * 回复时间
     * comment_product.gmt_reply
     *
     * @mbg.generated
     */
    private Date gmtReply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.id
     *
     * @return the value of comment_product.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.id
     *
     * @param id the value for comment_product.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.content
     *
     * @return the value of comment_product.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.content
     *
     * @param content the value for comment_product.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.reply_content
     *
     * @return the value of comment_product.reply_content
     *
     * @mbg.generated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.reply_content
     *
     * @param replyContent the value for comment_product.reply_content
     *
     * @mbg.generated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.grade
     *
     * @return the value of comment_product.grade
     *
     * @mbg.generated
     */
    public Byte getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.grade
     *
     * @param grade the value for comment_product.grade
     *
     * @mbg.generated
     */
    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.member_id
     *
     * @return the value of comment_product.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.member_id
     *
     * @param memberId the value for comment_product.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.merchant_id
     *
     * @return the value of comment_product.merchant_id
     *
     * @mbg.generated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.merchant_id
     *
     * @param merchantId the value for comment_product.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.product_id
     *
     * @return the value of comment_product.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.product_id
     *
     * @param productId the value for comment_product.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.order_item_id
     *
     * @return the value of comment_product.order_item_id
     *
     * @mbg.generated
     */
    public Long getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.order_item_id
     *
     * @param orderItemId the value for comment_product.order_item_id
     *
     * @mbg.generated
     */
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.product_model_id
     *
     * @return the value of comment_product.product_model_id
     *
     * @mbg.generated
     */
    public Long getProductModelId() {
        return productModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.product_model_id
     *
     * @param productModelId the value for comment_product.product_model_id
     *
     * @mbg.generated
     */
    public void setProductModelId(Long productModelId) {
        this.productModelId = productModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.is_anonymous
     *
     * @return the value of comment_product.is_anonymous
     *
     * @mbg.generated
     */
    public Boolean getIsAnonymous() {
        return isAnonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.is_anonymous
     *
     * @param isAnonymous the value for comment_product.is_anonymous
     *
     * @mbg.generated
     */
    public void setIsAnonymous(Boolean isAnonymous) {
        this.isAnonymous = isAnonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.status
     *
     * @return the value of comment_product.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.status
     *
     * @param status the value for comment_product.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.is_have_img
     *
     * @return the value of comment_product.is_have_img
     *
     * @mbg.generated
     */
    public Boolean getIsHaveImg() {
        return isHaveImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.is_have_img
     *
     * @param isHaveImg the value for comment_product.is_have_img
     *
     * @mbg.generated
     */
    public void setIsHaveImg(Boolean isHaveImg) {
        this.isHaveImg = isHaveImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.gmt_modified
     *
     * @return the value of comment_product.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.gmt_modified
     *
     * @param gmtModified the value for comment_product.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.gmt_create
     *
     * @return the value of comment_product.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.gmt_create
     *
     * @param gmtCreate the value for comment_product.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_product.gmt_reply
     *
     * @return the value of comment_product.gmt_reply
     *
     * @mbg.generated
     */
    public Date getGmtReply() {
        return gmtReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_product.gmt_reply
     *
     * @param gmtReply the value for comment_product.gmt_reply
     *
     * @mbg.generated
     */
    public void setGmtReply(Date gmtReply) {
        this.gmtReply = gmtReply;
    }
}