package com.lawu.eshop.mall.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class MessageDO implements Serializable {
    /**
     *
     * 主键
     * message.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 用户编号
     * message.user_num
     *
     * @mbg.generated
     */
    private String userNum;

    /**
     *
     * 关联主键
     * message.relate_id
     *
     * @mbg.generated
     */
    private Long relateId;

    /**
     *
     * 消息类型 1:推荐店铺2:平台通知3:充值4:提现5:收益6:发货通知7:派送通知8:签收通知
     * message.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * 标题
     * message.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * 消息内容
     * message.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * 图片路径
     * message.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * 状态：0未读，1已读，2删除
     * message.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 是否已推送消息
     * message.is_push
     *
     * @mbg.generated
     */
    private Boolean isPush;

    /**
     *
     * 备注
     * message.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * 修改时间
     * message.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * message.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.user_num
     *
     * @return the value of message.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.user_num
     *
     * @param userNum the value for message.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.relate_id
     *
     * @return the value of message.relate_id
     *
     * @mbg.generated
     */
    public Long getRelateId() {
        return relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.relate_id
     *
     * @param relateId the value for message.relate_id
     *
     * @mbg.generated
     */
    public void setRelateId(Long relateId) {
        this.relateId = relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type
     *
     * @return the value of message.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type
     *
     * @param type the value for message.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.title
     *
     * @return the value of message.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.title
     *
     * @param title the value for message.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.img_url
     *
     * @return the value of message.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.img_url
     *
     * @param imgUrl the value for message.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.status
     *
     * @return the value of message.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.status
     *
     * @param status the value for message.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_push
     *
     * @return the value of message.is_push
     *
     * @mbg.generated
     */
    public Boolean getIsPush() {
        return isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_push
     *
     * @param isPush the value for message.is_push
     *
     * @mbg.generated
     */
    public void setIsPush(Boolean isPush) {
        this.isPush = isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.remark
     *
     * @return the value of message.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.remark
     *
     * @param remark the value for message.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.gmt_modified
     *
     * @return the value of message.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.gmt_modified
     *
     * @param gmtModified the value for message.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.gmt_create
     *
     * @return the value of message.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.gmt_create
     *
     * @param gmtCreate the value for message.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}