package com.lawu.eshop.mall.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class MessageTemplateDO implements Serializable {
    /**
     *
     * 主键
     * message_template.id
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private Integer id;

    /**
     *
     * 标题
     * message_template.title
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private String title;

    /**
     *
     * 模板内容
     * message_template.content
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private String content;

    /**
     *
     * 消息类型
     * message_template.type
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private Byte type;

    /**
     *
     * 修改时间
     * message_template.gmt_modified
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * message_template.gmt_create
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_template
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.id
     *
     * @return the value of message_template.id
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.id
     *
     * @param id the value for message_template.id
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.title
     *
     * @return the value of message_template.title
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.title
     *
     * @param title the value for message_template.title
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.content
     *
     * @return the value of message_template.content
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.content
     *
     * @param content the value for message_template.content
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.type
     *
     * @return the value of message_template.type
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.type
     *
     * @param type the value for message_template.type
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.gmt_modified
     *
     * @return the value of message_template.gmt_modified
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.gmt_modified
     *
     * @param gmtModified the value for message_template.gmt_modified
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.gmt_create
     *
     * @return the value of message_template.gmt_create
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.gmt_create
     *
     * @param gmtCreate the value for message_template.gmt_create
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}