package com.lawu.eshop.game.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class GameRobotAccountDO implements Serializable {
    /**
     *
     * 主键
     * game_robot_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * 机器人账号
     * game_robot_account.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * 用户编号
     * game_robot_account.user_num
     *
     * @mbg.generated
     */
    private String userNum;

    /**
     *
     * 机器人账号密码
     * game_robot_account.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * 机器人昵称(多个昵称用逗号分隔)
     * game_robot_account.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * 机器人头像(多个头像用逗号分隔)
     * game_robot_account.head_img
     *
     * @mbg.generated
     */
    private String headImg;

    /**
     *
     * 机器人区域(多个区域用逗号分隔)
     * game_robot_account.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     *
     * 机器人状态(0-禁用|1-空闲|2-使用中)
     * game_robot_account.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 机器人服务id
     * game_robot_account.server_id
     *
     * @mbg.generated
     */
    private Integer serverId;

    /**
     *
     * 更新时间
     * game_robot_account.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * game_robot_account.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_robot_account.id
     *
     * @return the value of game_robot_account.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_robot_account.id
     *
     * @param id the value for game_robot_account.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_robot_account.account
     *
     * @return the value of game_robot_account.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_robot_account.account
     *
     * @param account the value for game_robot_account.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_robot_account.user_num
     *
     * @return the value of game_robot_account.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_robot_account.user_num
     *
     * @param userNum the value for game_robot_account.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_robot_account.password
     *
     * @return the value of game_robot_account.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_robot_account.password
     *
     * @param password the value for game_robot_account.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_robot_account.nickname
     *
     * @return the value of game_robot_account.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_robot_account.nickname
     *
     * @param nickname the value for game_robot_account.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_robot_account.head_img
     *
     * @return the value of game_robot_account.head_img
     *
     * @mbg.generated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_robot_account.head_img
     *
     * @param headImg the value for game_robot_account.head_img
     *
     * @mbg.generated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_robot_account.region
     *
     * @return the value of game_robot_account.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_robot_account.region
     *
     * @param region the value for game_robot_account.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_robot_account.status
     *
     * @return the value of game_robot_account.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_robot_account.status
     *
     * @param status the value for game_robot_account.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_robot_account.server_id
     *
     * @return the value of game_robot_account.server_id
     *
     * @mbg.generated
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_robot_account.server_id
     *
     * @param serverId the value for game_robot_account.server_id
     *
     * @mbg.generated
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_robot_account.gmt_modified
     *
     * @return the value of game_robot_account.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_robot_account.gmt_modified
     *
     * @param gmtModified the value for game_robot_account.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_robot_account.gmt_create
     *
     * @return the value of game_robot_account.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_robot_account.gmt_create
     *
     * @param gmtCreate the value for game_robot_account.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}