package com.lawu.eshop.game.srv.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GameMindConfigDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    public GameMindConfigDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAttendPointIsNull() {
            addCriterion("attend_point is null");
            return (Criteria) this;
        }

        public Criteria andAttendPointIsNotNull() {
            addCriterion("attend_point is not null");
            return (Criteria) this;
        }

        public Criteria andAttendPointEqualTo(Integer value) {
            addCriterion("attend_point =", value, "attendPoint");
            return (Criteria) this;
        }

        public Criteria andAttendPointNotEqualTo(Integer value) {
            addCriterion("attend_point <>", value, "attendPoint");
            return (Criteria) this;
        }

        public Criteria andAttendPointGreaterThan(Integer value) {
            addCriterion("attend_point >", value, "attendPoint");
            return (Criteria) this;
        }

        public Criteria andAttendPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("attend_point >=", value, "attendPoint");
            return (Criteria) this;
        }

        public Criteria andAttendPointLessThan(Integer value) {
            addCriterion("attend_point <", value, "attendPoint");
            return (Criteria) this;
        }

        public Criteria andAttendPointLessThanOrEqualTo(Integer value) {
            addCriterion("attend_point <=", value, "attendPoint");
            return (Criteria) this;
        }

        public Criteria andAttendPointIn(List<Integer> values) {
            addCriterion("attend_point in", values, "attendPoint");
            return (Criteria) this;
        }

        public Criteria andAttendPointNotIn(List<Integer> values) {
            addCriterion("attend_point not in", values, "attendPoint");
            return (Criteria) this;
        }

        public Criteria andAttendPointBetween(Integer value1, Integer value2) {
            addCriterion("attend_point between", value1, value2, "attendPoint");
            return (Criteria) this;
        }

        public Criteria andAttendPointNotBetween(Integer value1, Integer value2) {
            addCriterion("attend_point not between", value1, value2, "attendPoint");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointIsNull() {
            addCriterion("attend_max_point is null");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointIsNotNull() {
            addCriterion("attend_max_point is not null");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointEqualTo(Integer value) {
            addCriterion("attend_max_point =", value, "attendMaxPoint");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointNotEqualTo(Integer value) {
            addCriterion("attend_max_point <>", value, "attendMaxPoint");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointGreaterThan(Integer value) {
            addCriterion("attend_max_point >", value, "attendMaxPoint");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("attend_max_point >=", value, "attendMaxPoint");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointLessThan(Integer value) {
            addCriterion("attend_max_point <", value, "attendMaxPoint");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointLessThanOrEqualTo(Integer value) {
            addCriterion("attend_max_point <=", value, "attendMaxPoint");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointIn(List<Integer> values) {
            addCriterion("attend_max_point in", values, "attendMaxPoint");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointNotIn(List<Integer> values) {
            addCriterion("attend_max_point not in", values, "attendMaxPoint");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointBetween(Integer value1, Integer value2) {
            addCriterion("attend_max_point between", value1, value2, "attendMaxPoint");
            return (Criteria) this;
        }

        public Criteria andAttendMaxPointNotBetween(Integer value1, Integer value2) {
            addCriterion("attend_max_point not between", value1, value2, "attendMaxPoint");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumIsNull() {
            addCriterion("room_max_num is null");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumIsNotNull() {
            addCriterion("room_max_num is not null");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumEqualTo(Integer value) {
            addCriterion("room_max_num =", value, "roomMaxNum");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumNotEqualTo(Integer value) {
            addCriterion("room_max_num <>", value, "roomMaxNum");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumGreaterThan(Integer value) {
            addCriterion("room_max_num >", value, "roomMaxNum");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_max_num >=", value, "roomMaxNum");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumLessThan(Integer value) {
            addCriterion("room_max_num <", value, "roomMaxNum");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumLessThanOrEqualTo(Integer value) {
            addCriterion("room_max_num <=", value, "roomMaxNum");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumIn(List<Integer> values) {
            addCriterion("room_max_num in", values, "roomMaxNum");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumNotIn(List<Integer> values) {
            addCriterion("room_max_num not in", values, "roomMaxNum");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumBetween(Integer value1, Integer value2) {
            addCriterion("room_max_num between", value1, value2, "roomMaxNum");
            return (Criteria) this;
        }

        public Criteria andRoomMaxNumNotBetween(Integer value1, Integer value2) {
            addCriterion("room_max_num not between", value1, value2, "roomMaxNum");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreIsNull() {
            addCriterion("success_score is null");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreIsNotNull() {
            addCriterion("success_score is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreEqualTo(Integer value) {
            addCriterion("success_score =", value, "successScore");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreNotEqualTo(Integer value) {
            addCriterion("success_score <>", value, "successScore");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreGreaterThan(Integer value) {
            addCriterion("success_score >", value, "successScore");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("success_score >=", value, "successScore");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreLessThan(Integer value) {
            addCriterion("success_score <", value, "successScore");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreLessThanOrEqualTo(Integer value) {
            addCriterion("success_score <=", value, "successScore");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreIn(List<Integer> values) {
            addCriterion("success_score in", values, "successScore");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreNotIn(List<Integer> values) {
            addCriterion("success_score not in", values, "successScore");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreBetween(Integer value1, Integer value2) {
            addCriterion("success_score between", value1, value2, "successScore");
            return (Criteria) this;
        }

        public Criteria andSuccessScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("success_score not between", value1, value2, "successScore");
            return (Criteria) this;
        }

        public Criteria andFreeCountIsNull() {
            addCriterion("free_count is null");
            return (Criteria) this;
        }

        public Criteria andFreeCountIsNotNull() {
            addCriterion("free_count is not null");
            return (Criteria) this;
        }

        public Criteria andFreeCountEqualTo(Integer value) {
            addCriterion("free_count =", value, "freeCount");
            return (Criteria) this;
        }

        public Criteria andFreeCountNotEqualTo(Integer value) {
            addCriterion("free_count <>", value, "freeCount");
            return (Criteria) this;
        }

        public Criteria andFreeCountGreaterThan(Integer value) {
            addCriterion("free_count >", value, "freeCount");
            return (Criteria) this;
        }

        public Criteria andFreeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("free_count >=", value, "freeCount");
            return (Criteria) this;
        }

        public Criteria andFreeCountLessThan(Integer value) {
            addCriterion("free_count <", value, "freeCount");
            return (Criteria) this;
        }

        public Criteria andFreeCountLessThanOrEqualTo(Integer value) {
            addCriterion("free_count <=", value, "freeCount");
            return (Criteria) this;
        }

        public Criteria andFreeCountIn(List<Integer> values) {
            addCriterion("free_count in", values, "freeCount");
            return (Criteria) this;
        }

        public Criteria andFreeCountNotIn(List<Integer> values) {
            addCriterion("free_count not in", values, "freeCount");
            return (Criteria) this;
        }

        public Criteria andFreeCountBetween(Integer value1, Integer value2) {
            addCriterion("free_count between", value1, value2, "freeCount");
            return (Criteria) this;
        }

        public Criteria andFreeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("free_count not between", value1, value2, "freeCount");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountIsNull() {
            addCriterion("share_attend_count is null");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountIsNotNull() {
            addCriterion("share_attend_count is not null");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountEqualTo(Integer value) {
            addCriterion("share_attend_count =", value, "shareAttendCount");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountNotEqualTo(Integer value) {
            addCriterion("share_attend_count <>", value, "shareAttendCount");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountGreaterThan(Integer value) {
            addCriterion("share_attend_count >", value, "shareAttendCount");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("share_attend_count >=", value, "shareAttendCount");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountLessThan(Integer value) {
            addCriterion("share_attend_count <", value, "shareAttendCount");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountLessThanOrEqualTo(Integer value) {
            addCriterion("share_attend_count <=", value, "shareAttendCount");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountIn(List<Integer> values) {
            addCriterion("share_attend_count in", values, "shareAttendCount");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountNotIn(List<Integer> values) {
            addCriterion("share_attend_count not in", values, "shareAttendCount");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountBetween(Integer value1, Integer value2) {
            addCriterion("share_attend_count between", value1, value2, "shareAttendCount");
            return (Criteria) this;
        }

        public Criteria andShareAttendCountNotBetween(Integer value1, Integer value2) {
            addCriterion("share_attend_count not between", value1, value2, "shareAttendCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountIsNull() {
            addCriterion("question_count is null");
            return (Criteria) this;
        }

        public Criteria andQuestionCountIsNotNull() {
            addCriterion("question_count is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionCountEqualTo(Integer value) {
            addCriterion("question_count =", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountNotEqualTo(Integer value) {
            addCriterion("question_count <>", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountGreaterThan(Integer value) {
            addCriterion("question_count >", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("question_count >=", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountLessThan(Integer value) {
            addCriterion("question_count <", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountLessThanOrEqualTo(Integer value) {
            addCriterion("question_count <=", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountIn(List<Integer> values) {
            addCriterion("question_count in", values, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountNotIn(List<Integer> values) {
            addCriterion("question_count not in", values, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountBetween(Integer value1, Integer value2) {
            addCriterion("question_count between", value1, value2, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountNotBetween(Integer value1, Integer value2) {
            addCriterion("question_count not between", value1, value2, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountIsNull() {
            addCriterion("question_simple_count is null");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountIsNotNull() {
            addCriterion("question_simple_count is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountEqualTo(Integer value) {
            addCriterion("question_simple_count =", value, "questionSimpleCount");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountNotEqualTo(Integer value) {
            addCriterion("question_simple_count <>", value, "questionSimpleCount");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountGreaterThan(Integer value) {
            addCriterion("question_simple_count >", value, "questionSimpleCount");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("question_simple_count >=", value, "questionSimpleCount");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountLessThan(Integer value) {
            addCriterion("question_simple_count <", value, "questionSimpleCount");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountLessThanOrEqualTo(Integer value) {
            addCriterion("question_simple_count <=", value, "questionSimpleCount");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountIn(List<Integer> values) {
            addCriterion("question_simple_count in", values, "questionSimpleCount");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountNotIn(List<Integer> values) {
            addCriterion("question_simple_count not in", values, "questionSimpleCount");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountBetween(Integer value1, Integer value2) {
            addCriterion("question_simple_count between", value1, value2, "questionSimpleCount");
            return (Criteria) this;
        }

        public Criteria andQuestionSimpleCountNotBetween(Integer value1, Integer value2) {
            addCriterion("question_simple_count not between", value1, value2, "questionSimpleCount");
            return (Criteria) this;
        }

        public Criteria andCountDownIsNull() {
            addCriterion("count_down is null");
            return (Criteria) this;
        }

        public Criteria andCountDownIsNotNull() {
            addCriterion("count_down is not null");
            return (Criteria) this;
        }

        public Criteria andCountDownEqualTo(Integer value) {
            addCriterion("count_down =", value, "countDown");
            return (Criteria) this;
        }

        public Criteria andCountDownNotEqualTo(Integer value) {
            addCriterion("count_down <>", value, "countDown");
            return (Criteria) this;
        }

        public Criteria andCountDownGreaterThan(Integer value) {
            addCriterion("count_down >", value, "countDown");
            return (Criteria) this;
        }

        public Criteria andCountDownGreaterThanOrEqualTo(Integer value) {
            addCriterion("count_down >=", value, "countDown");
            return (Criteria) this;
        }

        public Criteria andCountDownLessThan(Integer value) {
            addCriterion("count_down <", value, "countDown");
            return (Criteria) this;
        }

        public Criteria andCountDownLessThanOrEqualTo(Integer value) {
            addCriterion("count_down <=", value, "countDown");
            return (Criteria) this;
        }

        public Criteria andCountDownIn(List<Integer> values) {
            addCriterion("count_down in", values, "countDown");
            return (Criteria) this;
        }

        public Criteria andCountDownNotIn(List<Integer> values) {
            addCriterion("count_down not in", values, "countDown");
            return (Criteria) this;
        }

        public Criteria andCountDownBetween(Integer value1, Integer value2) {
            addCriterion("count_down between", value1, value2, "countDown");
            return (Criteria) this;
        }

        public Criteria andCountDownNotBetween(Integer value1, Integer value2) {
            addCriterion("count_down not between", value1, value2, "countDown");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleIsNull() {
            addCriterion("last_score_multiple is null");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleIsNotNull() {
            addCriterion("last_score_multiple is not null");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleEqualTo(Integer value) {
            addCriterion("last_score_multiple =", value, "lastScoreMultiple");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleNotEqualTo(Integer value) {
            addCriterion("last_score_multiple <>", value, "lastScoreMultiple");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleGreaterThan(Integer value) {
            addCriterion("last_score_multiple >", value, "lastScoreMultiple");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_score_multiple >=", value, "lastScoreMultiple");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleLessThan(Integer value) {
            addCriterion("last_score_multiple <", value, "lastScoreMultiple");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleLessThanOrEqualTo(Integer value) {
            addCriterion("last_score_multiple <=", value, "lastScoreMultiple");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleIn(List<Integer> values) {
            addCriterion("last_score_multiple in", values, "lastScoreMultiple");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleNotIn(List<Integer> values) {
            addCriterion("last_score_multiple not in", values, "lastScoreMultiple");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleBetween(Integer value1, Integer value2) {
            addCriterion("last_score_multiple between", value1, value2, "lastScoreMultiple");
            return (Criteria) this;
        }

        public Criteria andLastScoreMultipleNotBetween(Integer value1, Integer value2) {
            addCriterion("last_score_multiple not between", value1, value2, "lastScoreMultiple");
            return (Criteria) this;
        }

        public Criteria andAwardPointIsNull() {
            addCriterion("award_point is null");
            return (Criteria) this;
        }

        public Criteria andAwardPointIsNotNull() {
            addCriterion("award_point is not null");
            return (Criteria) this;
        }

        public Criteria andAwardPointEqualTo(Integer value) {
            addCriterion("award_point =", value, "awardPoint");
            return (Criteria) this;
        }

        public Criteria andAwardPointNotEqualTo(Integer value) {
            addCriterion("award_point <>", value, "awardPoint");
            return (Criteria) this;
        }

        public Criteria andAwardPointGreaterThan(Integer value) {
            addCriterion("award_point >", value, "awardPoint");
            return (Criteria) this;
        }

        public Criteria andAwardPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("award_point >=", value, "awardPoint");
            return (Criteria) this;
        }

        public Criteria andAwardPointLessThan(Integer value) {
            addCriterion("award_point <", value, "awardPoint");
            return (Criteria) this;
        }

        public Criteria andAwardPointLessThanOrEqualTo(Integer value) {
            addCriterion("award_point <=", value, "awardPoint");
            return (Criteria) this;
        }

        public Criteria andAwardPointIn(List<Integer> values) {
            addCriterion("award_point in", values, "awardPoint");
            return (Criteria) this;
        }

        public Criteria andAwardPointNotIn(List<Integer> values) {
            addCriterion("award_point not in", values, "awardPoint");
            return (Criteria) this;
        }

        public Criteria andAwardPointBetween(Integer value1, Integer value2) {
            addCriterion("award_point between", value1, value2, "awardPoint");
            return (Criteria) this;
        }

        public Criteria andAwardPointNotBetween(Integer value1, Integer value2) {
            addCriterion("award_point not between", value1, value2, "awardPoint");
            return (Criteria) this;
        }

        public Criteria andAwardStarIsNull() {
            addCriterion("award_star is null");
            return (Criteria) this;
        }

        public Criteria andAwardStarIsNotNull() {
            addCriterion("award_star is not null");
            return (Criteria) this;
        }

        public Criteria andAwardStarEqualTo(Integer value) {
            addCriterion("award_star =", value, "awardStar");
            return (Criteria) this;
        }

        public Criteria andAwardStarNotEqualTo(Integer value) {
            addCriterion("award_star <>", value, "awardStar");
            return (Criteria) this;
        }

        public Criteria andAwardStarGreaterThan(Integer value) {
            addCriterion("award_star >", value, "awardStar");
            return (Criteria) this;
        }

        public Criteria andAwardStarGreaterThanOrEqualTo(Integer value) {
            addCriterion("award_star >=", value, "awardStar");
            return (Criteria) this;
        }

        public Criteria andAwardStarLessThan(Integer value) {
            addCriterion("award_star <", value, "awardStar");
            return (Criteria) this;
        }

        public Criteria andAwardStarLessThanOrEqualTo(Integer value) {
            addCriterion("award_star <=", value, "awardStar");
            return (Criteria) this;
        }

        public Criteria andAwardStarIn(List<Integer> values) {
            addCriterion("award_star in", values, "awardStar");
            return (Criteria) this;
        }

        public Criteria andAwardStarNotIn(List<Integer> values) {
            addCriterion("award_star not in", values, "awardStar");
            return (Criteria) this;
        }

        public Criteria andAwardStarBetween(Integer value1, Integer value2) {
            addCriterion("award_star between", value1, value2, "awardStar");
            return (Criteria) this;
        }

        public Criteria andAwardStarNotBetween(Integer value1, Integer value2) {
            addCriterion("award_star not between", value1, value2, "awardStar");
            return (Criteria) this;
        }

        public Criteria andDeductStarIsNull() {
            addCriterion("deduct_star is null");
            return (Criteria) this;
        }

        public Criteria andDeductStarIsNotNull() {
            addCriterion("deduct_star is not null");
            return (Criteria) this;
        }

        public Criteria andDeductStarEqualTo(Integer value) {
            addCriterion("deduct_star =", value, "deductStar");
            return (Criteria) this;
        }

        public Criteria andDeductStarNotEqualTo(Integer value) {
            addCriterion("deduct_star <>", value, "deductStar");
            return (Criteria) this;
        }

        public Criteria andDeductStarGreaterThan(Integer value) {
            addCriterion("deduct_star >", value, "deductStar");
            return (Criteria) this;
        }

        public Criteria andDeductStarGreaterThanOrEqualTo(Integer value) {
            addCriterion("deduct_star >=", value, "deductStar");
            return (Criteria) this;
        }

        public Criteria andDeductStarLessThan(Integer value) {
            addCriterion("deduct_star <", value, "deductStar");
            return (Criteria) this;
        }

        public Criteria andDeductStarLessThanOrEqualTo(Integer value) {
            addCriterion("deduct_star <=", value, "deductStar");
            return (Criteria) this;
        }

        public Criteria andDeductStarIn(List<Integer> values) {
            addCriterion("deduct_star in", values, "deductStar");
            return (Criteria) this;
        }

        public Criteria andDeductStarNotIn(List<Integer> values) {
            addCriterion("deduct_star not in", values, "deductStar");
            return (Criteria) this;
        }

        public Criteria andDeductStarBetween(Integer value1, Integer value2) {
            addCriterion("deduct_star between", value1, value2, "deductStar");
            return (Criteria) this;
        }

        public Criteria andDeductStarNotBetween(Integer value1, Integer value2) {
            addCriterion("deduct_star not between", value1, value2, "deductStar");
            return (Criteria) this;
        }

        public Criteria andSecScoreIsNull() {
            addCriterion("sec_score is null");
            return (Criteria) this;
        }

        public Criteria andSecScoreIsNotNull() {
            addCriterion("sec_score is not null");
            return (Criteria) this;
        }

        public Criteria andSecScoreEqualTo(String value) {
            addCriterion("sec_score =", value, "secScore");
            return (Criteria) this;
        }

        public Criteria andSecScoreNotEqualTo(String value) {
            addCriterion("sec_score <>", value, "secScore");
            return (Criteria) this;
        }

        public Criteria andSecScoreGreaterThan(String value) {
            addCriterion("sec_score >", value, "secScore");
            return (Criteria) this;
        }

        public Criteria andSecScoreGreaterThanOrEqualTo(String value) {
            addCriterion("sec_score >=", value, "secScore");
            return (Criteria) this;
        }

        public Criteria andSecScoreLessThan(String value) {
            addCriterion("sec_score <", value, "secScore");
            return (Criteria) this;
        }

        public Criteria andSecScoreLessThanOrEqualTo(String value) {
            addCriterion("sec_score <=", value, "secScore");
            return (Criteria) this;
        }

        public Criteria andSecScoreLike(String value) {
            addCriterion("sec_score like", value, "secScore");
            return (Criteria) this;
        }

        public Criteria andSecScoreNotLike(String value) {
            addCriterion("sec_score not like", value, "secScore");
            return (Criteria) this;
        }

        public Criteria andSecScoreIn(List<String> values) {
            addCriterion("sec_score in", values, "secScore");
            return (Criteria) this;
        }

        public Criteria andSecScoreNotIn(List<String> values) {
            addCriterion("sec_score not in", values, "secScore");
            return (Criteria) this;
        }

        public Criteria andSecScoreBetween(String value1, String value2) {
            addCriterion("sec_score between", value1, value2, "secScore");
            return (Criteria) this;
        }

        public Criteria andSecScoreNotBetween(String value1, String value2) {
            addCriterion("sec_score not between", value1, value2, "secScore");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeIsNull() {
            addCriterion("robot_effective_time is null");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeIsNotNull() {
            addCriterion("robot_effective_time is not null");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeEqualTo(Integer value) {
            addCriterion("robot_effective_time =", value, "robotEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeNotEqualTo(Integer value) {
            addCriterion("robot_effective_time <>", value, "robotEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeGreaterThan(Integer value) {
            addCriterion("robot_effective_time >", value, "robotEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("robot_effective_time >=", value, "robotEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeLessThan(Integer value) {
            addCriterion("robot_effective_time <", value, "robotEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeLessThanOrEqualTo(Integer value) {
            addCriterion("robot_effective_time <=", value, "robotEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeIn(List<Integer> values) {
            addCriterion("robot_effective_time in", values, "robotEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeNotIn(List<Integer> values) {
            addCriterion("robot_effective_time not in", values, "robotEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeBetween(Integer value1, Integer value2) {
            addCriterion("robot_effective_time between", value1, value2, "robotEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRobotEffectiveTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("robot_effective_time not between", value1, value2, "robotEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountIsNull() {
            addCriterion("robot_min_right_count is null");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountIsNotNull() {
            addCriterion("robot_min_right_count is not null");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountEqualTo(Integer value) {
            addCriterion("robot_min_right_count =", value, "robotMinRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountNotEqualTo(Integer value) {
            addCriterion("robot_min_right_count <>", value, "robotMinRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountGreaterThan(Integer value) {
            addCriterion("robot_min_right_count >", value, "robotMinRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("robot_min_right_count >=", value, "robotMinRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountLessThan(Integer value) {
            addCriterion("robot_min_right_count <", value, "robotMinRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountLessThanOrEqualTo(Integer value) {
            addCriterion("robot_min_right_count <=", value, "robotMinRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountIn(List<Integer> values) {
            addCriterion("robot_min_right_count in", values, "robotMinRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountNotIn(List<Integer> values) {
            addCriterion("robot_min_right_count not in", values, "robotMinRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountBetween(Integer value1, Integer value2) {
            addCriterion("robot_min_right_count between", value1, value2, "robotMinRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMinRightCountNotBetween(Integer value1, Integer value2) {
            addCriterion("robot_min_right_count not between", value1, value2, "robotMinRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountIsNull() {
            addCriterion("robot_max_right_count is null");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountIsNotNull() {
            addCriterion("robot_max_right_count is not null");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountEqualTo(Integer value) {
            addCriterion("robot_max_right_count =", value, "robotMaxRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountNotEqualTo(Integer value) {
            addCriterion("robot_max_right_count <>", value, "robotMaxRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountGreaterThan(Integer value) {
            addCriterion("robot_max_right_count >", value, "robotMaxRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("robot_max_right_count >=", value, "robotMaxRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountLessThan(Integer value) {
            addCriterion("robot_max_right_count <", value, "robotMaxRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountLessThanOrEqualTo(Integer value) {
            addCriterion("robot_max_right_count <=", value, "robotMaxRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountIn(List<Integer> values) {
            addCriterion("robot_max_right_count in", values, "robotMaxRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountNotIn(List<Integer> values) {
            addCriterion("robot_max_right_count not in", values, "robotMaxRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountBetween(Integer value1, Integer value2) {
            addCriterion("robot_max_right_count between", value1, value2, "robotMaxRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotMaxRightCountNotBetween(Integer value1, Integer value2) {
            addCriterion("robot_max_right_count not between", value1, value2, "robotMaxRightCount");
            return (Criteria) this;
        }

        public Criteria andRobotStatusIsNull() {
            addCriterion("robot_status is null");
            return (Criteria) this;
        }

        public Criteria andRobotStatusIsNotNull() {
            addCriterion("robot_status is not null");
            return (Criteria) this;
        }

        public Criteria andRobotStatusEqualTo(Byte value) {
            addCriterion("robot_status =", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusNotEqualTo(Byte value) {
            addCriterion("robot_status <>", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusGreaterThan(Byte value) {
            addCriterion("robot_status >", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("robot_status >=", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusLessThan(Byte value) {
            addCriterion("robot_status <", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusLessThanOrEqualTo(Byte value) {
            addCriterion("robot_status <=", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusIn(List<Byte> values) {
            addCriterion("robot_status in", values, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusNotIn(List<Byte> values) {
            addCriterion("robot_status not in", values, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusBetween(Byte value1, Byte value2) {
            addCriterion("robot_status between", value1, value2, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("robot_status not between", value1, value2, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkIsNull() {
            addCriterion("forbidden_remark is null");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkIsNotNull() {
            addCriterion("forbidden_remark is not null");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkEqualTo(String value) {
            addCriterion("forbidden_remark =", value, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkNotEqualTo(String value) {
            addCriterion("forbidden_remark <>", value, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkGreaterThan(String value) {
            addCriterion("forbidden_remark >", value, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("forbidden_remark >=", value, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkLessThan(String value) {
            addCriterion("forbidden_remark <", value, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkLessThanOrEqualTo(String value) {
            addCriterion("forbidden_remark <=", value, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkLike(String value) {
            addCriterion("forbidden_remark like", value, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkNotLike(String value) {
            addCriterion("forbidden_remark not like", value, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkIn(List<String> values) {
            addCriterion("forbidden_remark in", values, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkNotIn(List<String> values) {
            addCriterion("forbidden_remark not in", values, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkBetween(String value1, String value2) {
            addCriterion("forbidden_remark between", value1, value2, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andForbiddenRemarkNotBetween(String value1, String value2) {
            addCriterion("forbidden_remark not between", value1, value2, "forbiddenRemark");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_mind_config
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}