package com.lawu.eshop.game.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class GamePuzzleUserPicDO implements Serializable {
    /**
     *
     * 主键
     * game_puzzle_user_pic.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 用户编号
     * game_puzzle_user_pic.user_num
     *
     * @mbg.generated
     */
    private String userNum;

    /**
     *
     * 用户昵称
     * game_puzzle_user_pic.user_nickname
     *
     * @mbg.generated
     */
    private String userNickname;

    /**
     *
     * 图片路径
     * game_puzzle_user_pic.img_path
     *
     * @mbg.generated
     */
    private String imgPath;

    /**
     *
     * 类型
     * game_puzzle_user_pic.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * 简单
     * game_puzzle_user_pic.is_simple
     *
     * @mbg.generated
     */
    private Boolean isSimple;

    /**
     *
     * 一般
     * game_puzzle_user_pic.is_common
     *
     * @mbg.generated
     */
    private Boolean isCommon;

    /**
     *
     * 困难
     * game_puzzle_user_pic.is_hard
     *
     * @mbg.generated
     */
    private Boolean isHard;

    /**
     *
     * 1--待审核，2--已采用，3--未采用
     * game_puzzle_user_pic.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 修改时间
     * game_puzzle_user_pic.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * game_puzzle_user_pic.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_puzzle_user_pic
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_puzzle_user_pic.id
     *
     * @return the value of game_puzzle_user_pic.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_puzzle_user_pic.id
     *
     * @param id the value for game_puzzle_user_pic.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_puzzle_user_pic.user_num
     *
     * @return the value of game_puzzle_user_pic.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_puzzle_user_pic.user_num
     *
     * @param userNum the value for game_puzzle_user_pic.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_puzzle_user_pic.user_nickname
     *
     * @return the value of game_puzzle_user_pic.user_nickname
     *
     * @mbg.generated
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_puzzle_user_pic.user_nickname
     *
     * @param userNickname the value for game_puzzle_user_pic.user_nickname
     *
     * @mbg.generated
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_puzzle_user_pic.img_path
     *
     * @return the value of game_puzzle_user_pic.img_path
     *
     * @mbg.generated
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_puzzle_user_pic.img_path
     *
     * @param imgPath the value for game_puzzle_user_pic.img_path
     *
     * @mbg.generated
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_puzzle_user_pic.type
     *
     * @return the value of game_puzzle_user_pic.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_puzzle_user_pic.type
     *
     * @param type the value for game_puzzle_user_pic.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_puzzle_user_pic.is_simple
     *
     * @return the value of game_puzzle_user_pic.is_simple
     *
     * @mbg.generated
     */
    public Boolean getIsSimple() {
        return isSimple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_puzzle_user_pic.is_simple
     *
     * @param isSimple the value for game_puzzle_user_pic.is_simple
     *
     * @mbg.generated
     */
    public void setIsSimple(Boolean isSimple) {
        this.isSimple = isSimple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_puzzle_user_pic.is_common
     *
     * @return the value of game_puzzle_user_pic.is_common
     *
     * @mbg.generated
     */
    public Boolean getIsCommon() {
        return isCommon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_puzzle_user_pic.is_common
     *
     * @param isCommon the value for game_puzzle_user_pic.is_common
     *
     * @mbg.generated
     */
    public void setIsCommon(Boolean isCommon) {
        this.isCommon = isCommon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_puzzle_user_pic.is_hard
     *
     * @return the value of game_puzzle_user_pic.is_hard
     *
     * @mbg.generated
     */
    public Boolean getIsHard() {
        return isHard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_puzzle_user_pic.is_hard
     *
     * @param isHard the value for game_puzzle_user_pic.is_hard
     *
     * @mbg.generated
     */
    public void setIsHard(Boolean isHard) {
        this.isHard = isHard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_puzzle_user_pic.status
     *
     * @return the value of game_puzzle_user_pic.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_puzzle_user_pic.status
     *
     * @param status the value for game_puzzle_user_pic.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_puzzle_user_pic.gmt_modified
     *
     * @return the value of game_puzzle_user_pic.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_puzzle_user_pic.gmt_modified
     *
     * @param gmtModified the value for game_puzzle_user_pic.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_puzzle_user_pic.gmt_create
     *
     * @return the value of game_puzzle_user_pic.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_puzzle_user_pic.gmt_create
     *
     * @param gmtCreate the value for game_puzzle_user_pic.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}