package com.lawu.eshop.game.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class GameRoomDO implements Serializable {
    /**
     *
     * 主键
     * game_room.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 房主用户编号
     * game_room.user_num
     *
     * @mbg.generated
     */
    private String userNum;

    /**
     *
     * 房主用户账号
     * game_room.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * 房间号
     * game_room.room_num
     *
     * @mbg.generated
     */
    private String roomNum;

    /**
     *
     * 玩家信息
     * game_room.player_info
     *
     * @mbg.generated
     */
    private String playerInfo;

    /**
     *
     * 入场积分
     * game_room.point
     *
     * @mbg.generated
     */
    private BigDecimal point;

    /**
     *
     * 密码
     * game_room.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     *
     * 类型：1--头脑PK，2--拼图
     * game_room.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * 状态：1--等待中，2--进行中，3--已结束
     * game_room.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 难易程度：1--简单，2--一般，3--困难，4--随机
     * game_room.hard_level
     *
     * @mbg.generated
     */
    private Byte hardLevel;

    /**
     *
     * 修改时间
     * game_room.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * game_room.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_room
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.id
     *
     * @return the value of game_room.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.id
     *
     * @param id the value for game_room.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.user_num
     *
     * @return the value of game_room.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.user_num
     *
     * @param userNum the value for game_room.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.account
     *
     * @return the value of game_room.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.account
     *
     * @param account the value for game_room.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.room_num
     *
     * @return the value of game_room.room_num
     *
     * @mbg.generated
     */
    public String getRoomNum() {
        return roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.room_num
     *
     * @param roomNum the value for game_room.room_num
     *
     * @mbg.generated
     */
    public void setRoomNum(String roomNum) {
        this.roomNum = roomNum == null ? null : roomNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.player_info
     *
     * @return the value of game_room.player_info
     *
     * @mbg.generated
     */
    public String getPlayerInfo() {
        return playerInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.player_info
     *
     * @param playerInfo the value for game_room.player_info
     *
     * @mbg.generated
     */
    public void setPlayerInfo(String playerInfo) {
        this.playerInfo = playerInfo == null ? null : playerInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.point
     *
     * @return the value of game_room.point
     *
     * @mbg.generated
     */
    public BigDecimal getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.point
     *
     * @param point the value for game_room.point
     *
     * @mbg.generated
     */
    public void setPoint(BigDecimal point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.pwd
     *
     * @return the value of game_room.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.pwd
     *
     * @param pwd the value for game_room.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.type
     *
     * @return the value of game_room.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.type
     *
     * @param type the value for game_room.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.status
     *
     * @return the value of game_room.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.status
     *
     * @param status the value for game_room.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.hard_level
     *
     * @return the value of game_room.hard_level
     *
     * @mbg.generated
     */
    public Byte getHardLevel() {
        return hardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.hard_level
     *
     * @param hardLevel the value for game_room.hard_level
     *
     * @mbg.generated
     */
    public void setHardLevel(Byte hardLevel) {
        this.hardLevel = hardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.gmt_modified
     *
     * @return the value of game_room.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.gmt_modified
     *
     * @param gmtModified the value for game_room.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_room.gmt_create
     *
     * @return the value of game_room.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_room.gmt_create
     *
     * @param gmtCreate the value for game_room.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}