package com.lawu.eshop.game.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class UserStarRecordDO implements Serializable {
    /**
     *
     * 
     * user_star_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 用户编号
     * user_star_record.user_num
     *
     * @mbg.generated
     */
    private String userNum;

    /**
     *
     * 用户账号
     * user_star_record.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * 当月星星增加总数
     * user_star_record.month_star_count
     *
     * @mbg.generated
     */
    private Integer monthStarCount;

    /**
     *
     * 记录时间
     * user_star_record.gmt_report
     *
     * @mbg.generated
     */
    private Date gmtReport;

    /**
     *
     * 0:无效1：有效
     * user_star_record.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * 修改时间
     * user_star_record.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * user_star_record.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_star_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_star_record.id
     *
     * @return the value of user_star_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_star_record.id
     *
     * @param id the value for user_star_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_star_record.user_num
     *
     * @return the value of user_star_record.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_star_record.user_num
     *
     * @param userNum the value for user_star_record.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_star_record.account
     *
     * @return the value of user_star_record.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_star_record.account
     *
     * @param account the value for user_star_record.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_star_record.month_star_count
     *
     * @return the value of user_star_record.month_star_count
     *
     * @mbg.generated
     */
    public Integer getMonthStarCount() {
        return monthStarCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_star_record.month_star_count
     *
     * @param monthStarCount the value for user_star_record.month_star_count
     *
     * @mbg.generated
     */
    public void setMonthStarCount(Integer monthStarCount) {
        this.monthStarCount = monthStarCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_star_record.gmt_report
     *
     * @return the value of user_star_record.gmt_report
     *
     * @mbg.generated
     */
    public Date getGmtReport() {
        return gmtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_star_record.gmt_report
     *
     * @param gmtReport the value for user_star_record.gmt_report
     *
     * @mbg.generated
     */
    public void setGmtReport(Date gmtReport) {
        this.gmtReport = gmtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_star_record.status
     *
     * @return the value of user_star_record.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_star_record.status
     *
     * @param status the value for user_star_record.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_star_record.gmt_modified
     *
     * @return the value of user_star_record.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_star_record.gmt_modified
     *
     * @param gmtModified the value for user_star_record.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_star_record.gmt_create
     *
     * @return the value of user_star_record.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_star_record.gmt_create
     *
     * @param gmtCreate the value for user_star_record.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}