package com.lawu.eshop.mall.srv.domain.extend;

import java.io.Serializable;
import java.util.Date;

/**
 * @author zhangyong
 * @date 2017/4/6.
 */
public class CommentProductDOView implements Serializable {
    /**
     * 主键
     * comment_merchant.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * 评价内容
     * comment_merchant.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * 商家回复内容
     * comment_merchant.reply_content
     *
     * @mbg.generated
     */
    private String replyContent;

    /**
     * 评分
     * comment_merchant.grade
     *
     * @mbg.generated
     */
    private Byte grade;

    /**
     * 用户
     * comment_merchant.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     * 商家
     * comment_merchant.merchant_id
     *
     * @mbg.generated
     */
    private Long merchantId;

    /**
     * 是否匿名（0：否1：是）
     * comment_merchant.is_anonymous
     *
     * @mbg.generated
     */
    private Boolean isAnonymous;

    /**
     * 状态（1：有效0：无效）
     * comment_merchant.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * 修改时间
     * comment_merchant.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * 创建时间
     * comment_merchant.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * 回复时间
     * comment_merchant.gmt_reply
     *
     * @mbg.generated
     */
    private Date gmtReply;

    private Long productId;

    private Long productModelId;

    private Long orderItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment_merchant
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getReplyContent() {
        return replyContent;
    }

    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent;
    }

    public Byte getGrade() {
        return grade;
    }

    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    public Long getMemberId() {
        return memberId;
    }

    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    public Long getMerchantId() {
        return merchantId;
    }

    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    public Boolean getAnonymous() {
        return isAnonymous;
    }

    public void setAnonymous(Boolean anonymous) {
        isAnonymous = anonymous;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtReply() {
        return gmtReply;
    }

    public void setGmtReply(Date gmtReply) {
        this.gmtReply = gmtReply;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getProductModelId() {
        return productModelId;
    }

    public void setProductModelId(Long productModelId) {
        this.productModelId = productModelId;
    }

    public Long getOrderItemId() {
        return orderItemId;
    }

    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }
}
