package com.lawu.eshop.property.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class BankAccountDO implements Serializable {
    /**
     *
     * 主键
     * bank_account.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 用户编号
     * bank_account.user_num
     *
     * @mbg.generated
     */
    private String userNum;

    /**
     *
     * 用户名
     * bank_account.account_name
     *
     * @mbg.generated
     */
    private String accountName;

    /**
     *
     * 账号
     * bank_account.account_number
     *
     * @mbg.generated
     */
    private String accountNumber;

    /**
     *
     * 账户类型(1-银行卡2-支付宝3微信)
     * bank_account.account_type
     *
     * @mbg.generated
     */
    private Byte accountType;

    /**
     *
     * 开户行
     * bank_account.bank_id
     *
     * @mbg.generated
     */
    private Integer bankId;

    /**
     *
     * 省市区path
     * bank_account.region_path
     *
     * @mbg.generated
     */
    private String regionPath;

    /**
     *
     * 省市区名称
     * bank_account.region_name
     *
     * @mbg.generated
     */
    private String regionName;

    /**
     *
     * 支行
     * bank_account.sub_branch_name
     *
     * @mbg.generated
     */
    private String subBranchName;

    /**
     *
     * 0删除1正常
     * bank_account.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 备注
     * bank_account.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * 操作时间
     * bank_account.audit_time
     *
     * @mbg.generated
     */
    private Date auditTime;

    /**
     *
     * 操作备注
     * bank_account.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * 操作人员ID
     * bank_account.auditor_id
     *
     * @mbg.generated
     */
    private Integer auditorId;

    /**
     *
     * 1-会员 2-商家
     * bank_account.user_type
     *
     * @mbg.generated
     */
    private Byte userType;

    /**
     *
     * 是否永久绑定
     * bank_account.is_bind_forever
     *
     * @mbg.generated
     */
    private Boolean isBindForever;

    /**
     *
     * 修改时间
     * bank_account.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * bank_account.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bank_account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.id
     *
     * @return the value of bank_account.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.id
     *
     * @param id the value for bank_account.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.user_num
     *
     * @return the value of bank_account.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.user_num
     *
     * @param userNum the value for bank_account.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.account_name
     *
     * @return the value of bank_account.account_name
     *
     * @mbg.generated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.account_name
     *
     * @param accountName the value for bank_account.account_name
     *
     * @mbg.generated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.account_number
     *
     * @return the value of bank_account.account_number
     *
     * @mbg.generated
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.account_number
     *
     * @param accountNumber the value for bank_account.account_number
     *
     * @mbg.generated
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber == null ? null : accountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.account_type
     *
     * @return the value of bank_account.account_type
     *
     * @mbg.generated
     */
    public Byte getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.account_type
     *
     * @param accountType the value for bank_account.account_type
     *
     * @mbg.generated
     */
    public void setAccountType(Byte accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.bank_id
     *
     * @return the value of bank_account.bank_id
     *
     * @mbg.generated
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.bank_id
     *
     * @param bankId the value for bank_account.bank_id
     *
     * @mbg.generated
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.region_path
     *
     * @return the value of bank_account.region_path
     *
     * @mbg.generated
     */
    public String getRegionPath() {
        return regionPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.region_path
     *
     * @param regionPath the value for bank_account.region_path
     *
     * @mbg.generated
     */
    public void setRegionPath(String regionPath) {
        this.regionPath = regionPath == null ? null : regionPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.region_name
     *
     * @return the value of bank_account.region_name
     *
     * @mbg.generated
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.region_name
     *
     * @param regionName the value for bank_account.region_name
     *
     * @mbg.generated
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.sub_branch_name
     *
     * @return the value of bank_account.sub_branch_name
     *
     * @mbg.generated
     */
    public String getSubBranchName() {
        return subBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.sub_branch_name
     *
     * @param subBranchName the value for bank_account.sub_branch_name
     *
     * @mbg.generated
     */
    public void setSubBranchName(String subBranchName) {
        this.subBranchName = subBranchName == null ? null : subBranchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.status
     *
     * @return the value of bank_account.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.status
     *
     * @param status the value for bank_account.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.note
     *
     * @return the value of bank_account.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.note
     *
     * @param note the value for bank_account.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.audit_time
     *
     * @return the value of bank_account.audit_time
     *
     * @mbg.generated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.audit_time
     *
     * @param auditTime the value for bank_account.audit_time
     *
     * @mbg.generated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.remark
     *
     * @return the value of bank_account.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.remark
     *
     * @param remark the value for bank_account.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.auditor_id
     *
     * @return the value of bank_account.auditor_id
     *
     * @mbg.generated
     */
    public Integer getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.auditor_id
     *
     * @param auditorId the value for bank_account.auditor_id
     *
     * @mbg.generated
     */
    public void setAuditorId(Integer auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.user_type
     *
     * @return the value of bank_account.user_type
     *
     * @mbg.generated
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.user_type
     *
     * @param userType the value for bank_account.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.is_bind_forever
     *
     * @return the value of bank_account.is_bind_forever
     *
     * @mbg.generated
     */
    public Boolean getIsBindForever() {
        return isBindForever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.is_bind_forever
     *
     * @param isBindForever the value for bank_account.is_bind_forever
     *
     * @mbg.generated
     */
    public void setIsBindForever(Boolean isBindForever) {
        this.isBindForever = isBindForever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.gmt_modified
     *
     * @return the value of bank_account.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.gmt_modified
     *
     * @param gmtModified the value for bank_account.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.gmt_create
     *
     * @return the value of bank_account.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.gmt_create
     *
     * @param gmtCreate the value for bank_account.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}