package com.lawu.eshop.property.srv.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransactionDetailDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    public TransactionDetailDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTransactionNumIsNull() {
            addCriterion("transaction_num is null");
            return (Criteria) this;
        }

        public Criteria andTransactionNumIsNotNull() {
            addCriterion("transaction_num is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionNumEqualTo(String value) {
            addCriterion("transaction_num =", value, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andTransactionNumNotEqualTo(String value) {
            addCriterion("transaction_num <>", value, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andTransactionNumGreaterThan(String value) {
            addCriterion("transaction_num >", value, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andTransactionNumGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_num >=", value, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andTransactionNumLessThan(String value) {
            addCriterion("transaction_num <", value, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andTransactionNumLessThanOrEqualTo(String value) {
            addCriterion("transaction_num <=", value, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andTransactionNumLike(String value) {
            addCriterion("transaction_num like", value, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andTransactionNumNotLike(String value) {
            addCriterion("transaction_num not like", value, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andTransactionNumIn(List<String> values) {
            addCriterion("transaction_num in", values, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andTransactionNumNotIn(List<String> values) {
            addCriterion("transaction_num not in", values, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andTransactionNumBetween(String value1, String value2) {
            addCriterion("transaction_num between", value1, value2, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andTransactionNumNotBetween(String value1, String value2) {
            addCriterion("transaction_num not between", value1, value2, "transactionNum");
            return (Criteria) this;
        }

        public Criteria andUserNumIsNull() {
            addCriterion("user_num is null");
            return (Criteria) this;
        }

        public Criteria andUserNumIsNotNull() {
            addCriterion("user_num is not null");
            return (Criteria) this;
        }

        public Criteria andUserNumEqualTo(String value) {
            addCriterion("user_num =", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotEqualTo(String value) {
            addCriterion("user_num <>", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumGreaterThan(String value) {
            addCriterion("user_num >", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumGreaterThanOrEqualTo(String value) {
            addCriterion("user_num >=", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumLessThan(String value) {
            addCriterion("user_num <", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumLessThanOrEqualTo(String value) {
            addCriterion("user_num <=", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumLike(String value) {
            addCriterion("user_num like", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotLike(String value) {
            addCriterion("user_num not like", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumIn(List<String> values) {
            addCriterion("user_num in", values, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotIn(List<String> values) {
            addCriterion("user_num not in", values, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumBetween(String value1, String value2) {
            addCriterion("user_num between", value1, value2, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotBetween(String value1, String value2) {
            addCriterion("user_num not between", value1, value2, "userNum");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIsNull() {
            addCriterion("transaction_type is null");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIsNotNull() {
            addCriterion("transaction_type is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeEqualTo(Byte value) {
            addCriterion("transaction_type =", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotEqualTo(Byte value) {
            addCriterion("transaction_type <>", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeGreaterThan(Byte value) {
            addCriterion("transaction_type >", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("transaction_type >=", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLessThan(Byte value) {
            addCriterion("transaction_type <", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLessThanOrEqualTo(Byte value) {
            addCriterion("transaction_type <=", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIn(List<Byte> values) {
            addCriterion("transaction_type in", values, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotIn(List<Byte> values) {
            addCriterion("transaction_type not in", values, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeBetween(Byte value1, Byte value2) {
            addCriterion("transaction_type between", value1, value2, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("transaction_type not between", value1, value2, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountIsNull() {
            addCriterion("transaction_account is null");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountIsNotNull() {
            addCriterion("transaction_account is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountEqualTo(String value) {
            addCriterion("transaction_account =", value, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountNotEqualTo(String value) {
            addCriterion("transaction_account <>", value, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountGreaterThan(String value) {
            addCriterion("transaction_account >", value, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_account >=", value, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountLessThan(String value) {
            addCriterion("transaction_account <", value, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountLessThanOrEqualTo(String value) {
            addCriterion("transaction_account <=", value, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountLike(String value) {
            addCriterion("transaction_account like", value, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountNotLike(String value) {
            addCriterion("transaction_account not like", value, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountIn(List<String> values) {
            addCriterion("transaction_account in", values, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountNotIn(List<String> values) {
            addCriterion("transaction_account not in", values, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountBetween(String value1, String value2) {
            addCriterion("transaction_account between", value1, value2, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountNotBetween(String value1, String value2) {
            addCriterion("transaction_account not between", value1, value2, "transactionAccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeIsNull() {
            addCriterion("transaction_account_type is null");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeIsNotNull() {
            addCriterion("transaction_account_type is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeEqualTo(Byte value) {
            addCriterion("transaction_account_type =", value, "transactionAccountType");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeNotEqualTo(Byte value) {
            addCriterion("transaction_account_type <>", value, "transactionAccountType");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeGreaterThan(Byte value) {
            addCriterion("transaction_account_type >", value, "transactionAccountType");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("transaction_account_type >=", value, "transactionAccountType");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeLessThan(Byte value) {
            addCriterion("transaction_account_type <", value, "transactionAccountType");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeLessThanOrEqualTo(Byte value) {
            addCriterion("transaction_account_type <=", value, "transactionAccountType");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeIn(List<Byte> values) {
            addCriterion("transaction_account_type in", values, "transactionAccountType");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeNotIn(List<Byte> values) {
            addCriterion("transaction_account_type not in", values, "transactionAccountType");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeBetween(Byte value1, Byte value2) {
            addCriterion("transaction_account_type between", value1, value2, "transactionAccountType");
            return (Criteria) this;
        }

        public Criteria andTransactionAccountTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("transaction_account_type not between", value1, value2, "transactionAccountType");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountIsNull() {
            addCriterion("previous_amount is null");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountIsNotNull() {
            addCriterion("previous_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountEqualTo(BigDecimal value) {
            addCriterion("previous_amount =", value, "previousAmount");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountNotEqualTo(BigDecimal value) {
            addCriterion("previous_amount <>", value, "previousAmount");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountGreaterThan(BigDecimal value) {
            addCriterion("previous_amount >", value, "previousAmount");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("previous_amount >=", value, "previousAmount");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountLessThan(BigDecimal value) {
            addCriterion("previous_amount <", value, "previousAmount");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("previous_amount <=", value, "previousAmount");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountIn(List<BigDecimal> values) {
            addCriterion("previous_amount in", values, "previousAmount");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountNotIn(List<BigDecimal> values) {
            addCriterion("previous_amount not in", values, "previousAmount");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("previous_amount between", value1, value2, "previousAmount");
            return (Criteria) this;
        }

        public Criteria andPreviousAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("previous_amount not between", value1, value2, "previousAmount");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNull() {
            addCriterion("direction is null");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNotNull() {
            addCriterion("direction is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionEqualTo(Byte value) {
            addCriterion("direction =", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotEqualTo(Byte value) {
            addCriterion("direction <>", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThan(Byte value) {
            addCriterion("direction >", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThanOrEqualTo(Byte value) {
            addCriterion("direction >=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThan(Byte value) {
            addCriterion("direction <", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThanOrEqualTo(Byte value) {
            addCriterion("direction <=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionIn(List<Byte> values) {
            addCriterion("direction in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotIn(List<Byte> values) {
            addCriterion("direction not in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionBetween(Byte value1, Byte value2) {
            addCriterion("direction between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotBetween(Byte value1, Byte value2) {
            addCriterion("direction not between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumIsNull() {
            addCriterion("third_transaction_num is null");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumIsNotNull() {
            addCriterion("third_transaction_num is not null");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumEqualTo(String value) {
            addCriterion("third_transaction_num =", value, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumNotEqualTo(String value) {
            addCriterion("third_transaction_num <>", value, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumGreaterThan(String value) {
            addCriterion("third_transaction_num >", value, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumGreaterThanOrEqualTo(String value) {
            addCriterion("third_transaction_num >=", value, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumLessThan(String value) {
            addCriterion("third_transaction_num <", value, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumLessThanOrEqualTo(String value) {
            addCriterion("third_transaction_num <=", value, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumLike(String value) {
            addCriterion("third_transaction_num like", value, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumNotLike(String value) {
            addCriterion("third_transaction_num not like", value, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumIn(List<String> values) {
            addCriterion("third_transaction_num in", values, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumNotIn(List<String> values) {
            addCriterion("third_transaction_num not in", values, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumBetween(String value1, String value2) {
            addCriterion("third_transaction_num between", value1, value2, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andThirdTransactionNumNotBetween(String value1, String value2) {
            addCriterion("third_transaction_num not between", value1, value2, "thirdTransactionNum");
            return (Criteria) this;
        }

        public Criteria andBizIdIsNull() {
            addCriterion("biz_id is null");
            return (Criteria) this;
        }

        public Criteria andBizIdIsNotNull() {
            addCriterion("biz_id is not null");
            return (Criteria) this;
        }

        public Criteria andBizIdEqualTo(String value) {
            addCriterion("biz_id =", value, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizIdNotEqualTo(String value) {
            addCriterion("biz_id <>", value, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizIdGreaterThan(String value) {
            addCriterion("biz_id >", value, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizIdGreaterThanOrEqualTo(String value) {
            addCriterion("biz_id >=", value, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizIdLessThan(String value) {
            addCriterion("biz_id <", value, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizIdLessThanOrEqualTo(String value) {
            addCriterion("biz_id <=", value, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizIdLike(String value) {
            addCriterion("biz_id like", value, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizIdNotLike(String value) {
            addCriterion("biz_id not like", value, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizIdIn(List<String> values) {
            addCriterion("biz_id in", values, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizIdNotIn(List<String> values) {
            addCriterion("biz_id not in", values, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizIdBetween(String value1, String value2) {
            addCriterion("biz_id between", value1, value2, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizIdNotBetween(String value1, String value2) {
            addCriterion("biz_id not between", value1, value2, "bizId");
            return (Criteria) this;
        }

        public Criteria andBizNumIsNull() {
            addCriterion("biz_num is null");
            return (Criteria) this;
        }

        public Criteria andBizNumIsNotNull() {
            addCriterion("biz_num is not null");
            return (Criteria) this;
        }

        public Criteria andBizNumEqualTo(String value) {
            addCriterion("biz_num =", value, "bizNum");
            return (Criteria) this;
        }

        public Criteria andBizNumNotEqualTo(String value) {
            addCriterion("biz_num <>", value, "bizNum");
            return (Criteria) this;
        }

        public Criteria andBizNumGreaterThan(String value) {
            addCriterion("biz_num >", value, "bizNum");
            return (Criteria) this;
        }

        public Criteria andBizNumGreaterThanOrEqualTo(String value) {
            addCriterion("biz_num >=", value, "bizNum");
            return (Criteria) this;
        }

        public Criteria andBizNumLessThan(String value) {
            addCriterion("biz_num <", value, "bizNum");
            return (Criteria) this;
        }

        public Criteria andBizNumLessThanOrEqualTo(String value) {
            addCriterion("biz_num <=", value, "bizNum");
            return (Criteria) this;
        }

        public Criteria andBizNumLike(String value) {
            addCriterion("biz_num like", value, "bizNum");
            return (Criteria) this;
        }

        public Criteria andBizNumNotLike(String value) {
            addCriterion("biz_num not like", value, "bizNum");
            return (Criteria) this;
        }

        public Criteria andBizNumIn(List<String> values) {
            addCriterion("biz_num in", values, "bizNum");
            return (Criteria) this;
        }

        public Criteria andBizNumNotIn(List<String> values) {
            addCriterion("biz_num not in", values, "bizNum");
            return (Criteria) this;
        }

        public Criteria andBizNumBetween(String value1, String value2) {
            addCriterion("biz_num between", value1, value2, "bizNum");
            return (Criteria) this;
        }

        public Criteria andBizNumNotBetween(String value1, String value2) {
            addCriterion("biz_num not between", value1, value2, "bizNum");
            return (Criteria) this;
        }

        public Criteria andTransactionDescIsNull() {
            addCriterion("transaction_desc is null");
            return (Criteria) this;
        }

        public Criteria andTransactionDescIsNotNull() {
            addCriterion("transaction_desc is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionDescEqualTo(String value) {
            addCriterion("transaction_desc =", value, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andTransactionDescNotEqualTo(String value) {
            addCriterion("transaction_desc <>", value, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andTransactionDescGreaterThan(String value) {
            addCriterion("transaction_desc >", value, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andTransactionDescGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_desc >=", value, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andTransactionDescLessThan(String value) {
            addCriterion("transaction_desc <", value, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andTransactionDescLessThanOrEqualTo(String value) {
            addCriterion("transaction_desc <=", value, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andTransactionDescLike(String value) {
            addCriterion("transaction_desc like", value, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andTransactionDescNotLike(String value) {
            addCriterion("transaction_desc not like", value, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andTransactionDescIn(List<String> values) {
            addCriterion("transaction_desc in", values, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andTransactionDescNotIn(List<String> values) {
            addCriterion("transaction_desc not in", values, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andTransactionDescBetween(String value1, String value2) {
            addCriterion("transaction_desc between", value1, value2, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andTransactionDescNotBetween(String value1, String value2) {
            addCriterion("transaction_desc not between", value1, value2, "transactionDesc");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNull() {
            addCriterion("province_id is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNotNull() {
            addCriterion("province_id is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdEqualTo(Integer value) {
            addCriterion("province_id =", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotEqualTo(Integer value) {
            addCriterion("province_id <>", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThan(Integer value) {
            addCriterion("province_id >", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("province_id >=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThan(Integer value) {
            addCriterion("province_id <", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThanOrEqualTo(Integer value) {
            addCriterion("province_id <=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIn(List<Integer> values) {
            addCriterion("province_id in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotIn(List<Integer> values) {
            addCriterion("province_id not in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdBetween(Integer value1, Integer value2) {
            addCriterion("province_id between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("province_id not between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("city_id is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("city_id is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(Integer value) {
            addCriterion("city_id =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(Integer value) {
            addCriterion("city_id <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(Integer value) {
            addCriterion("city_id >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("city_id >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(Integer value) {
            addCriterion("city_id <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(Integer value) {
            addCriterion("city_id <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<Integer> values) {
            addCriterion("city_id in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<Integer> values) {
            addCriterion("city_id not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(Integer value1, Integer value2) {
            addCriterion("city_id between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("city_id not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(Integer value) {
            addCriterion("area_id =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(Integer value) {
            addCriterion("area_id <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(Integer value) {
            addCriterion("area_id >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("area_id >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(Integer value) {
            addCriterion("area_id <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(Integer value) {
            addCriterion("area_id <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<Integer> values) {
            addCriterion("area_id in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<Integer> values) {
            addCriterion("area_id not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(Integer value1, Integer value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transaction_detail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transaction_detail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}