package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.FansMerchantDO;
import com.lawu.eshop.user.srv.domain.FansMerchantDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FansMerchantDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    int countByExample(FansMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    int deleteByExample(FansMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    int insert(FansMerchantDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    int insertSelective(FansMerchantDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    List<FansMerchantDO> selectByExampleWithRowbounds(FansMerchantDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    List<FansMerchantDO> selectByExample(FansMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    FansMerchantDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FansMerchantDO record, @Param("example") FansMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FansMerchantDO record, @Param("example") FansMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FansMerchantDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_merchant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FansMerchantDO record);
}