package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.FansInviteResultDO;
import com.lawu.eshop.user.srv.domain.FansInviteResultDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FansInviteResultDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    int countByExample(FansInviteResultDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    int deleteByExample(FansInviteResultDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    int insert(FansInviteResultDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    int insertSelective(FansInviteResultDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    List<FansInviteResultDO> selectByExampleWithRowbounds(FansInviteResultDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    List<FansInviteResultDO> selectByExample(FansInviteResultDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    FansInviteResultDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FansInviteResultDO record, @Param("example") FansInviteResultDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FansInviteResultDO record, @Param("example") FansInviteResultDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FansInviteResultDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FansInviteResultDO record);
}