package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.MerchantStoreImageDO;
import com.lawu.eshop.user.srv.domain.MerchantStoreImageDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MerchantStoreImageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    int countByExample(MerchantStoreImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    int deleteByExample(MerchantStoreImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    int insert(MerchantStoreImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    int insertSelective(MerchantStoreImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    List<MerchantStoreImageDO> selectByExampleWithRowbounds(MerchantStoreImageDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    List<MerchantStoreImageDO> selectByExample(MerchantStoreImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    MerchantStoreImageDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    int updateByExampleSelective(@Param("record") MerchantStoreImageDO record, @Param("example") MerchantStoreImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    int updateByExample(@Param("record") MerchantStoreImageDO record, @Param("example") MerchantStoreImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    int updateByPrimaryKeySelective(MerchantStoreImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_image
     *
     * @mbg.generated 2017-03-29 13:19:21
     */
    int updateByPrimaryKey(MerchantStoreImageDO record);
}