package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.MerchantStoreDO;
import com.lawu.eshop.user.srv.domain.MerchantStoreDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MerchantStoreDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    int countByExample(MerchantStoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    int deleteByExample(MerchantStoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    int insert(MerchantStoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    int insertSelective(MerchantStoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    List<MerchantStoreDO> selectByExampleWithRowbounds(MerchantStoreDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    List<MerchantStoreDO> selectByExample(MerchantStoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    MerchantStoreDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MerchantStoreDO record, @Param("example") MerchantStoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MerchantStoreDO record, @Param("example") MerchantStoreDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MerchantStoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MerchantStoreDO record);
}