package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.QqLoginMemberDO;
import com.lawu.eshop.user.srv.domain.QqLoginMemberDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface QqLoginMemberDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    int countByExample(QqLoginMemberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    int deleteByExample(QqLoginMemberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    int insert(QqLoginMemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    int insertSelective(QqLoginMemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    List<QqLoginMemberDO> selectByExampleWithRowbounds(QqLoginMemberDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    List<QqLoginMemberDO> selectByExample(QqLoginMemberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    QqLoginMemberDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QqLoginMemberDO record, @Param("example") QqLoginMemberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QqLoginMemberDO record, @Param("example") QqLoginMemberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QqLoginMemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QqLoginMemberDO record);
}