package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.UserGradeDetailDO;
import com.lawu.eshop.user.srv.domain.UserGradeDetailDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserGradeDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    int countByExample(UserGradeDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    int deleteByExample(UserGradeDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    int insert(UserGradeDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    int insertSelective(UserGradeDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    List<UserGradeDetailDO> selectByExampleWithRowbounds(UserGradeDetailDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    List<UserGradeDetailDO> selectByExample(UserGradeDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    UserGradeDetailDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserGradeDetailDO record, @Param("example") UserGradeDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserGradeDetailDO record, @Param("example") UserGradeDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserGradeDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserGradeDetailDO record);
}