package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.WxLoginMerchantDO;
import com.lawu.eshop.user.srv.domain.WxLoginMerchantDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WxLoginMerchantDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    long countByExample(WxLoginMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    int deleteByExample(WxLoginMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    int insert(WxLoginMerchantDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    int insertSelective(WxLoginMerchantDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    List<WxLoginMerchantDO> selectByExampleWithRowbounds(WxLoginMerchantDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    List<WxLoginMerchantDO> selectByExample(WxLoginMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    WxLoginMerchantDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxLoginMerchantDO record, @Param("example") WxLoginMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxLoginMerchantDO record, @Param("example") WxLoginMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxLoginMerchantDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_merchant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxLoginMerchantDO record);
}