package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class FansInviteResultDO implements Serializable {
    /**
     *
     * 主键
     * fans_invite_result.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 商家id
     * fans_invite_result.merchant_id
     *
     * @mbg.generated
     */
    private Long merchantId;

    /**
     *
     * 会员id
     * fans_invite_result.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * 消息编号
     * fans_invite_result.message_id
     *
     * @mbg.generated
     */
    private Long messageId;

    /**
     *
     * 处理结果:0--拒绝，1--同意
     * fans_invite_result.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 修改时间
     * fans_invite_result.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * fans_invite_result.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fans_invite_result
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_invite_result.id
     *
     * @return the value of fans_invite_result.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_invite_result.id
     *
     * @param id the value for fans_invite_result.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_invite_result.merchant_id
     *
     * @return the value of fans_invite_result.merchant_id
     *
     * @mbg.generated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_invite_result.merchant_id
     *
     * @param merchantId the value for fans_invite_result.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_invite_result.member_id
     *
     * @return the value of fans_invite_result.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_invite_result.member_id
     *
     * @param memberId the value for fans_invite_result.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_invite_result.message_id
     *
     * @return the value of fans_invite_result.message_id
     *
     * @mbg.generated
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_invite_result.message_id
     *
     * @param messageId the value for fans_invite_result.message_id
     *
     * @mbg.generated
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_invite_result.status
     *
     * @return the value of fans_invite_result.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_invite_result.status
     *
     * @param status the value for fans_invite_result.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_invite_result.gmt_modified
     *
     * @return the value of fans_invite_result.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_invite_result.gmt_modified
     *
     * @param gmtModified the value for fans_invite_result.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_invite_result.gmt_create
     *
     * @return the value of fans_invite_result.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_invite_result.gmt_create
     *
     * @param gmtCreate the value for fans_invite_result.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}