package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class FavoriteMerchantDO implements Serializable {
    /**
     *
     * 主键
     * favorite_merchant.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 会员
     * favorite_merchant.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * 收藏
     * favorite_merchant.merchant_id
     *
     * @mbg.generated
     */
    private Long merchantId;

    /**
     *
     * 创建日期
     * favorite_merchant.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * 1-普通店铺 2-实体店铺
     * favorite_merchant.manage_type
     *
     * @mbg.generated
     */
    private Byte manageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table favorite_merchant
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite_merchant.id
     *
     * @return the value of favorite_merchant.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite_merchant.id
     *
     * @param id the value for favorite_merchant.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite_merchant.member_id
     *
     * @return the value of favorite_merchant.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite_merchant.member_id
     *
     * @param memberId the value for favorite_merchant.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite_merchant.merchant_id
     *
     * @return the value of favorite_merchant.merchant_id
     *
     * @mbg.generated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite_merchant.merchant_id
     *
     * @param merchantId the value for favorite_merchant.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite_merchant.gmt_create
     *
     * @return the value of favorite_merchant.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite_merchant.gmt_create
     *
     * @param gmtCreate the value for favorite_merchant.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite_merchant.manage_type
     *
     * @return the value of favorite_merchant.manage_type
     *
     * @mbg.generated
     */
    public Byte getManageType() {
        return manageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite_merchant.manage_type
     *
     * @param manageType the value for favorite_merchant.manage_type
     *
     * @mbg.generated
     */
    public void setManageType(Byte manageType) {
        this.manageType = manageType;
    }
}