package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class QqLoginMemberDO implements Serializable {
    /**
     *
     * 主键
     * qq_login_member.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 用户编号
     * qq_login_member.user_num
     *
     * @mbg.generated
     */
    private String userNum;

    /**
     *
     * openid
     * qq_login_member.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * 昵称
     * qq_login_member.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * 性别
     * qq_login_member.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * 大小为100×100像素的QQ空间头像URL
     * qq_login_member.figureurl
     *
     * @mbg.generated
     */
    private String figureurl;

    /**
     *
     * 错误信息提示
     * qq_login_member.msg
     *
     * @mbg.generated
     */
    private String msg;

    /**
     *
     * 更新时间
     * qq_login_member.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * qq_login_member.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qq_login_member
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_login_member.id
     *
     * @return the value of qq_login_member.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_login_member.id
     *
     * @param id the value for qq_login_member.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_login_member.user_num
     *
     * @return the value of qq_login_member.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_login_member.user_num
     *
     * @param userNum the value for qq_login_member.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_login_member.openid
     *
     * @return the value of qq_login_member.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_login_member.openid
     *
     * @param openid the value for qq_login_member.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_login_member.nickname
     *
     * @return the value of qq_login_member.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_login_member.nickname
     *
     * @param nickname the value for qq_login_member.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_login_member.gender
     *
     * @return the value of qq_login_member.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_login_member.gender
     *
     * @param gender the value for qq_login_member.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_login_member.figureurl
     *
     * @return the value of qq_login_member.figureurl
     *
     * @mbg.generated
     */
    public String getFigureurl() {
        return figureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_login_member.figureurl
     *
     * @param figureurl the value for qq_login_member.figureurl
     *
     * @mbg.generated
     */
    public void setFigureurl(String figureurl) {
        this.figureurl = figureurl == null ? null : figureurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_login_member.msg
     *
     * @return the value of qq_login_member.msg
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_login_member.msg
     *
     * @param msg the value for qq_login_member.msg
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_login_member.gmt_modified
     *
     * @return the value of qq_login_member.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_login_member.gmt_modified
     *
     * @param gmtModified the value for qq_login_member.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq_login_member.gmt_create
     *
     * @return the value of qq_login_member.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq_login_member.gmt_create
     *
     * @param gmtCreate the value for qq_login_member.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}