package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class UserGradeDetailDO implements Serializable {
    /**
     *
     * 主键
     * user_grade_detail.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 会员编号
     * user_grade_detail.user_num
     *
     * @mbg.generated
     */
    private String userNum;

    /**
     *
     * 资产模块交易明细主键
     * user_grade_detail.transaction_detail_id
     *
     * @mbg.generated
     */
    private Long transactionDetailId;

    /**
     *
     * 资产模块交易明细表交易类型
     * user_grade_detail.transaction_detail_type
     *
     * @mbg.generated
     */
    private Byte transactionDetailType;

    /**
     *
     * 参与成长值业务记录表主键
     * user_grade_detail.biz_id
     *
     * @mbg.generated
     */
    private String bizId;

    /**
     *
     * 成长值记录
     * user_grade_detail.growth_value
     *
     * @mbg.generated
     */
    private Integer growthValue;

    /**
     *
     * 操作前会员等级
     * user_grade_detail.grade_before
     *
     * @mbg.generated
     */
    private Byte gradeBefore;

    /**
     *
     * 操作后会员等级
     * user_grade_detail.grade_after
     *
     * @mbg.generated
     */
    private Byte gradeAfter;

    /**
     *
     * 操作前成长值
     * user_grade_detail.growth_value_before
     *
     * @mbg.generated
     */
    private Integer growthValueBefore;

    /**
     *
     * 操作后成长值
     * user_grade_detail.growth_value_after
     *
     * @mbg.generated
     */
    private Integer growthValueAfter;

    /**
     *
     * 创建时间
     * user_grade_detail.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_grade_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade_detail.id
     *
     * @return the value of user_grade_detail.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade_detail.id
     *
     * @param id the value for user_grade_detail.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade_detail.user_num
     *
     * @return the value of user_grade_detail.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade_detail.user_num
     *
     * @param userNum the value for user_grade_detail.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade_detail.transaction_detail_id
     *
     * @return the value of user_grade_detail.transaction_detail_id
     *
     * @mbg.generated
     */
    public Long getTransactionDetailId() {
        return transactionDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade_detail.transaction_detail_id
     *
     * @param transactionDetailId the value for user_grade_detail.transaction_detail_id
     *
     * @mbg.generated
     */
    public void setTransactionDetailId(Long transactionDetailId) {
        this.transactionDetailId = transactionDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade_detail.transaction_detail_type
     *
     * @return the value of user_grade_detail.transaction_detail_type
     *
     * @mbg.generated
     */
    public Byte getTransactionDetailType() {
        return transactionDetailType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade_detail.transaction_detail_type
     *
     * @param transactionDetailType the value for user_grade_detail.transaction_detail_type
     *
     * @mbg.generated
     */
    public void setTransactionDetailType(Byte transactionDetailType) {
        this.transactionDetailType = transactionDetailType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade_detail.biz_id
     *
     * @return the value of user_grade_detail.biz_id
     *
     * @mbg.generated
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade_detail.biz_id
     *
     * @param bizId the value for user_grade_detail.biz_id
     *
     * @mbg.generated
     */
    public void setBizId(String bizId) {
        this.bizId = bizId == null ? null : bizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade_detail.growth_value
     *
     * @return the value of user_grade_detail.growth_value
     *
     * @mbg.generated
     */
    public Integer getGrowthValue() {
        return growthValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade_detail.growth_value
     *
     * @param growthValue the value for user_grade_detail.growth_value
     *
     * @mbg.generated
     */
    public void setGrowthValue(Integer growthValue) {
        this.growthValue = growthValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade_detail.grade_before
     *
     * @return the value of user_grade_detail.grade_before
     *
     * @mbg.generated
     */
    public Byte getGradeBefore() {
        return gradeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade_detail.grade_before
     *
     * @param gradeBefore the value for user_grade_detail.grade_before
     *
     * @mbg.generated
     */
    public void setGradeBefore(Byte gradeBefore) {
        this.gradeBefore = gradeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade_detail.grade_after
     *
     * @return the value of user_grade_detail.grade_after
     *
     * @mbg.generated
     */
    public Byte getGradeAfter() {
        return gradeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade_detail.grade_after
     *
     * @param gradeAfter the value for user_grade_detail.grade_after
     *
     * @mbg.generated
     */
    public void setGradeAfter(Byte gradeAfter) {
        this.gradeAfter = gradeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade_detail.growth_value_before
     *
     * @return the value of user_grade_detail.growth_value_before
     *
     * @mbg.generated
     */
    public Integer getGrowthValueBefore() {
        return growthValueBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade_detail.growth_value_before
     *
     * @param growthValueBefore the value for user_grade_detail.growth_value_before
     *
     * @mbg.generated
     */
    public void setGrowthValueBefore(Integer growthValueBefore) {
        this.growthValueBefore = growthValueBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade_detail.growth_value_after
     *
     * @return the value of user_grade_detail.growth_value_after
     *
     * @mbg.generated
     */
    public Integer getGrowthValueAfter() {
        return growthValueAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade_detail.growth_value_after
     *
     * @param growthValueAfter the value for user_grade_detail.growth_value_after
     *
     * @mbg.generated
     */
    public void setGrowthValueAfter(Integer growthValueAfter) {
        this.growthValueAfter = growthValueAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade_detail.gmt_create
     *
     * @return the value of user_grade_detail.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade_detail.gmt_create
     *
     * @param gmtCreate the value for user_grade_detail.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}