package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class UserGradeDO implements Serializable {
    /**
     *
     * 主键
     * user_grade.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 等级名称
     * user_grade.grade_name
     *
     * @mbg.generated
     */
    private String gradeName;

    /**
     *
     * 等级值
     * user_grade.grade_value
     *
     * @mbg.generated
     */
    private Byte gradeValue;

    /**
     *
     * 等级权值
     * user_grade.grade_weight
     *
     * @mbg.generated
     */
    private Integer gradeWeight;

    /**
     *
     * 最小成长值
     * user_grade.min_growth_value
     *
     * @mbg.generated
     */
    private Integer minGrowthValue;

    /**
     *
     * 免费抽奖次数
     * user_grade.free_lottery_count
     *
     * @mbg.generated
     */
    private Integer freeLotteryCount;

    /**
     *
     * 下次免费抽奖次数
     * user_grade.next_free_lottery_count
     *
     * @mbg.generated
     */
    private Integer nextFreeLotteryCount;

    /**
     *
     * 抽奖活动兑换积分
     * user_grade.lottery_activity_point
     *
     * @mbg.generated
     */
    private Integer lotteryActivityPoint;

    /**
     *
     * 修改时间
     * user_grade.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * user_grade.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_grade
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade.id
     *
     * @return the value of user_grade.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade.id
     *
     * @param id the value for user_grade.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade.grade_name
     *
     * @return the value of user_grade.grade_name
     *
     * @mbg.generated
     */
    public String getGradeName() {
        return gradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade.grade_name
     *
     * @param gradeName the value for user_grade.grade_name
     *
     * @mbg.generated
     */
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName == null ? null : gradeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade.grade_value
     *
     * @return the value of user_grade.grade_value
     *
     * @mbg.generated
     */
    public Byte getGradeValue() {
        return gradeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade.grade_value
     *
     * @param gradeValue the value for user_grade.grade_value
     *
     * @mbg.generated
     */
    public void setGradeValue(Byte gradeValue) {
        this.gradeValue = gradeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade.grade_weight
     *
     * @return the value of user_grade.grade_weight
     *
     * @mbg.generated
     */
    public Integer getGradeWeight() {
        return gradeWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade.grade_weight
     *
     * @param gradeWeight the value for user_grade.grade_weight
     *
     * @mbg.generated
     */
    public void setGradeWeight(Integer gradeWeight) {
        this.gradeWeight = gradeWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade.min_growth_value
     *
     * @return the value of user_grade.min_growth_value
     *
     * @mbg.generated
     */
    public Integer getMinGrowthValue() {
        return minGrowthValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade.min_growth_value
     *
     * @param minGrowthValue the value for user_grade.min_growth_value
     *
     * @mbg.generated
     */
    public void setMinGrowthValue(Integer minGrowthValue) {
        this.minGrowthValue = minGrowthValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade.free_lottery_count
     *
     * @return the value of user_grade.free_lottery_count
     *
     * @mbg.generated
     */
    public Integer getFreeLotteryCount() {
        return freeLotteryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade.free_lottery_count
     *
     * @param freeLotteryCount the value for user_grade.free_lottery_count
     *
     * @mbg.generated
     */
    public void setFreeLotteryCount(Integer freeLotteryCount) {
        this.freeLotteryCount = freeLotteryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade.next_free_lottery_count
     *
     * @return the value of user_grade.next_free_lottery_count
     *
     * @mbg.generated
     */
    public Integer getNextFreeLotteryCount() {
        return nextFreeLotteryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade.next_free_lottery_count
     *
     * @param nextFreeLotteryCount the value for user_grade.next_free_lottery_count
     *
     * @mbg.generated
     */
    public void setNextFreeLotteryCount(Integer nextFreeLotteryCount) {
        this.nextFreeLotteryCount = nextFreeLotteryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade.lottery_activity_point
     *
     * @return the value of user_grade.lottery_activity_point
     *
     * @mbg.generated
     */
    public Integer getLotteryActivityPoint() {
        return lotteryActivityPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade.lottery_activity_point
     *
     * @param lotteryActivityPoint the value for user_grade.lottery_activity_point
     *
     * @mbg.generated
     */
    public void setLotteryActivityPoint(Integer lotteryActivityPoint) {
        this.lotteryActivityPoint = lotteryActivityPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade.gmt_modified
     *
     * @return the value of user_grade.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade.gmt_modified
     *
     * @param gmtModified the value for user_grade.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_grade.gmt_create
     *
     * @return the value of user_grade.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_grade.gmt_create
     *
     * @param gmtCreate the value for user_grade.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}