package com.lawu.eshop.order.srv.mapper;

import com.lawu.eshop.order.srv.domain.ShoppingRefundProcessDO;
import com.lawu.eshop.order.srv.domain.ShoppingRefundProcessDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ShoppingRefundProcessDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    long countByExample(ShoppingRefundProcessDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    int deleteByExample(ShoppingRefundProcessDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    int insert(ShoppingRefundProcessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingRefundProcessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    List<ShoppingRefundProcessDO> selectByExampleWithRowbounds(ShoppingRefundProcessDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    List<ShoppingRefundProcessDO> selectByExample(ShoppingRefundProcessDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    ShoppingRefundProcessDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShoppingRefundProcessDO record, @Param("example") ShoppingRefundProcessDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShoppingRefundProcessDO record, @Param("example") ShoppingRefundProcessDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingRefundProcessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_refund_process
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingRefundProcessDO record);
}