package com.lawu.eshop.statistics.srv.mapper;

import com.lawu.eshop.statistics.srv.domain.ReportEarningsDailyDO;
import com.lawu.eshop.statistics.srv.domain.ReportEarningsDailyDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReportEarningsDailyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    long countByExample(ReportEarningsDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    int deleteByExample(ReportEarningsDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    int insert(ReportEarningsDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    int insertSelective(ReportEarningsDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    List<ReportEarningsDailyDO> selectByExampleWithRowbounds(ReportEarningsDailyDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    List<ReportEarningsDailyDO> selectByExample(ReportEarningsDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    ReportEarningsDailyDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportEarningsDailyDO record, @Param("example") ReportEarningsDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportEarningsDailyDO record, @Param("example") ReportEarningsDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportEarningsDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_earnings_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportEarningsDailyDO record);
}