package com.lawu.eshop.statistics.srv.mapper;

import com.lawu.eshop.statistics.srv.domain.ReportUserActiveAreaDailyDO;
import com.lawu.eshop.statistics.srv.domain.ReportUserActiveAreaDailyDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReportUserActiveAreaDailyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    int countByExample(ReportUserActiveAreaDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    int deleteByExample(ReportUserActiveAreaDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    int insert(ReportUserActiveAreaDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    int insertSelective(ReportUserActiveAreaDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    List<ReportUserActiveAreaDailyDO> selectByExampleWithRowbounds(ReportUserActiveAreaDailyDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    List<ReportUserActiveAreaDailyDO> selectByExample(ReportUserActiveAreaDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    ReportUserActiveAreaDailyDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportUserActiveAreaDailyDO record, @Param("example") ReportUserActiveAreaDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportUserActiveAreaDailyDO record, @Param("example") ReportUserActiveAreaDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportUserActiveAreaDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportUserActiveAreaDailyDO record);
}