package com.lawu.eshop.statistics.srv.mapper;

import com.lawu.eshop.statistics.srv.domain.ReportAreaUserRegDailyDO;
import com.lawu.eshop.statistics.srv.domain.ReportAreaUserRegDailyDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReportAreaUserRegDailyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    int countByExample(ReportAreaUserRegDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    int deleteByExample(ReportAreaUserRegDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    int insert(ReportAreaUserRegDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    int insertSelective(ReportAreaUserRegDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    List<ReportAreaUserRegDailyDO> selectByExampleWithRowbounds(ReportAreaUserRegDailyDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    List<ReportAreaUserRegDailyDO> selectByExample(ReportAreaUserRegDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    ReportAreaUserRegDailyDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportAreaUserRegDailyDO record, @Param("example") ReportAreaUserRegDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportAreaUserRegDailyDO record, @Param("example") ReportAreaUserRegDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportAreaUserRegDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_user_reg_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportAreaUserRegDailyDO record);
}