package com.lawu.eshop.statistics.srv.mapper;

import com.lawu.eshop.statistics.srv.domain.ReportAreaRechargeDailyDO;
import com.lawu.eshop.statistics.srv.domain.ReportAreaRechargeDailyDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReportAreaRechargeDailyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    int countByExample(ReportAreaRechargeDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    int deleteByExample(ReportAreaRechargeDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    int insert(ReportAreaRechargeDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    int insertSelective(ReportAreaRechargeDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    List<ReportAreaRechargeDailyDO> selectByExampleWithRowbounds(ReportAreaRechargeDailyDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    List<ReportAreaRechargeDailyDO> selectByExample(ReportAreaRechargeDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    ReportAreaRechargeDailyDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportAreaRechargeDailyDO record, @Param("example") ReportAreaRechargeDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportAreaRechargeDailyDO record, @Param("example") ReportAreaRechargeDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportAreaRechargeDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_recharge_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportAreaRechargeDailyDO record);
}