package com.lawu.eshop.statistics.srv.mapper;

import com.lawu.eshop.statistics.srv.domain.ReportPointConsumeMonthDO;
import com.lawu.eshop.statistics.srv.domain.ReportPointConsumeMonthDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReportPointConsumeMonthDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    int countByExample(ReportPointConsumeMonthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    int deleteByExample(ReportPointConsumeMonthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    int insert(ReportPointConsumeMonthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    int insertSelective(ReportPointConsumeMonthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    List<ReportPointConsumeMonthDO> selectByExampleWithRowbounds(ReportPointConsumeMonthDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    List<ReportPointConsumeMonthDO> selectByExample(ReportPointConsumeMonthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    ReportPointConsumeMonthDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportPointConsumeMonthDO record, @Param("example") ReportPointConsumeMonthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportPointConsumeMonthDO record, @Param("example") ReportPointConsumeMonthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportPointConsumeMonthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_point_consume_month
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportPointConsumeMonthDO record);
}