package com.lawu.eshop.statistics.srv.mapper;

import com.lawu.eshop.statistics.srv.domain.ReportWithdrawDailyDO;
import com.lawu.eshop.statistics.srv.domain.ReportWithdrawDailyDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReportWithdrawDailyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    int countByExample(ReportWithdrawDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    int deleteByExample(ReportWithdrawDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    int insert(ReportWithdrawDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    int insertSelective(ReportWithdrawDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    List<ReportWithdrawDailyDO> selectByExampleWithRowbounds(ReportWithdrawDailyDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    List<ReportWithdrawDailyDO> selectByExample(ReportWithdrawDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    ReportWithdrawDailyDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportWithdrawDailyDO record, @Param("example") ReportWithdrawDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportWithdrawDailyDO record, @Param("example") ReportWithdrawDailyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportWithdrawDailyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_withdraw_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportWithdrawDailyDO record);
}