package com.lawu.eshop.game.srv.mapper;

import com.lawu.eshop.game.srv.domain.GameRobotAccountDO;
import com.lawu.eshop.game.srv.domain.GameRobotAccountDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GameRobotAccountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    long countByExample(GameRobotAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    int deleteByExample(GameRobotAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    int insert(GameRobotAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    int insertSelective(GameRobotAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    List<GameRobotAccountDO> selectByExampleWithRowbounds(GameRobotAccountDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    List<GameRobotAccountDO> selectByExample(GameRobotAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    GameRobotAccountDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GameRobotAccountDO record, @Param("example") GameRobotAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GameRobotAccountDO record, @Param("example") GameRobotAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GameRobotAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_robot_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GameRobotAccountDO record);
}