package com.lawu.eshop.game.srv.mapper;

import com.lawu.eshop.game.srv.domain.GameDialRecordDO;
import com.lawu.eshop.game.srv.domain.GameDialRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GameDialRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    long countByExample(GameDialRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    int deleteByExample(GameDialRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    int insert(GameDialRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    int insertSelective(GameDialRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    List<GameDialRecordDO> selectByExampleWithRowbounds(GameDialRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    List<GameDialRecordDO> selectByExample(GameDialRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    GameDialRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GameDialRecordDO record, @Param("example") GameDialRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GameDialRecordDO record, @Param("example") GameDialRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GameDialRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GameDialRecordDO record);
}