package com.lawu.eshop.game.srv.mapper;

import com.lawu.eshop.game.srv.domain.GameMindConfigDO;
import com.lawu.eshop.game.srv.domain.GameMindConfigDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GameMindConfigDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    long countByExample(GameMindConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    int deleteByExample(GameMindConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    int insert(GameMindConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    int insertSelective(GameMindConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    List<GameMindConfigDO> selectByExampleWithRowbounds(GameMindConfigDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    List<GameMindConfigDO> selectByExample(GameMindConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    GameMindConfigDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GameMindConfigDO record, @Param("example") GameMindConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GameMindConfigDO record, @Param("example") GameMindConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GameMindConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GameMindConfigDO record);
}