package com.lawu.eshop.game.srv.mapper;

import com.lawu.eshop.game.srv.domain.GameAccountDO;
import com.lawu.eshop.game.srv.domain.GameAccountDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GameAccountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    long countByExample(GameAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    int deleteByExample(GameAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    int insert(GameAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    int insertSelective(GameAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    List<GameAccountDO> selectByExampleWithRowbounds(GameAccountDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    List<GameAccountDO> selectByExample(GameAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    GameAccountDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GameAccountDO record, @Param("example") GameAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GameAccountDO record, @Param("example") GameAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GameAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GameAccountDO record);
}