package com.lawu.eshop.game.srv.mapper;

import com.lawu.eshop.game.srv.domain.GameMindAttendRecordDO;
import com.lawu.eshop.game.srv.domain.GameMindAttendRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GameMindAttendRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    long countByExample(GameMindAttendRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    int deleteByExample(GameMindAttendRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    int insert(GameMindAttendRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    int insertSelective(GameMindAttendRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    List<GameMindAttendRecordDO> selectByExampleWithRowbounds(GameMindAttendRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    List<GameMindAttendRecordDO> selectByExample(GameMindAttendRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    GameMindAttendRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GameMindAttendRecordDO record, @Param("example") GameMindAttendRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GameMindAttendRecordDO record, @Param("example") GameMindAttendRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GameMindAttendRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mind_attend_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GameMindAttendRecordDO record);
}