package com.lawu.eshop.game.srv.mapper;

import com.lawu.eshop.game.srv.domain.GameInformDO;
import com.lawu.eshop.game.srv.domain.GameInformDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GameInformDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    long countByExample(GameInformDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    int deleteByExample(GameInformDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    int insert(GameInformDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    int insertSelective(GameInformDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    List<GameInformDO> selectByExampleWithRowbounds(GameInformDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    List<GameInformDO> selectByExample(GameInformDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    GameInformDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GameInformDO record, @Param("example") GameInformDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GameInformDO record, @Param("example") GameInformDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GameInformDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_inform
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GameInformDO record);
}