package com.lawu.eshop.game.srv.mapper;

import com.lawu.eshop.game.srv.domain.GameDialPrizeDO;
import com.lawu.eshop.game.srv.domain.GameDialPrizeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GameDialPrizeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    long countByExample(GameDialPrizeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    int deleteByExample(GameDialPrizeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    int insert(GameDialPrizeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    int insertSelective(GameDialPrizeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    List<GameDialPrizeDO> selectByExampleWithRowbounds(GameDialPrizeDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    List<GameDialPrizeDO> selectByExample(GameDialPrizeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    GameDialPrizeDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GameDialPrizeDO record, @Param("example") GameDialPrizeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GameDialPrizeDO record, @Param("example") GameDialPrizeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GameDialPrizeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_dial_prize
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GameDialPrizeDO record);
}