package com.lawu.eshop.order.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ShoppingOrderItemDO implements Serializable {
    /**
     *
     * 主键
     * shopping_order_item.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 订单id
     * shopping_order_item.shopping_order_id
     *
     * @mbg.generated
     */
    private Long shoppingOrderId;

    /**
     *
     * 商品id
     * shopping_order_item.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * 商品名称
     * shopping_order_item.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * 商品型号id
     * shopping_order_item.product_model_id
     *
     * @mbg.generated
     */
    private Long productModelId;

    /**
     *
     * 活动商品型号id
     * shopping_order_item.activity_product_model_id
     *
     * @mbg.generated
     */
    private Long activityProductModelId;

    /**
     *
     * 商品型号名称
     * shopping_order_item.product_model_name
     *
     * @mbg.generated
     */
    private String productModelName;

    /**
     *
     * 商品特征图片
     * shopping_order_item.product_feature_image
     *
     * @mbg.generated
     */
    private String productFeatureImage;

    /**
     *
     * 原价
     * shopping_order_item.regular_price
     *
     * @mbg.generated
     */
    private BigDecimal regularPrice;

    /**
     *
     * 现价
     * shopping_order_item.sales_price
     *
     * @mbg.generated
     */
    private BigDecimal salesPrice;

    /**
     *
     * 抵扣积分
     * shopping_order_item.deduction_points
     *
     * @mbg.generated
     */
    private BigDecimal deductionPoints;

    /**
     *
     * 积分抵扣金额
     * shopping_order_item.deduction_points_amount
     *
     * @mbg.generated
     */
    private BigDecimal deductionPointsAmount;

    /**
     *
     * 小计
     * shopping_order_item.subtotal
     *
     * @mbg.generated
     */
    private BigDecimal subtotal;

    /**
     *
     * 数量
     * shopping_order_item.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * 运费信息json({"defaultPieceNumber":"默认运费，多少件","defaultPieceMoney":"默认运费，多少件内多少钱","addPieceNumber":"每加多少件","addPieceMoney":"每加多少件，加多少钱"})
     * shopping_order_item.freight
     *
     * @mbg.generated
     */
    private String freight;

    /**
     *
     * 是否评价(0-未评价|1-已评价)
     * shopping_order_item.is_evaluation
     *
     * @mbg.generated
     */
    private Boolean isEvaluation;

    /**
     *
     * 是否支持退换货(0-否1-是)
     * shopping_order_item.is_allow_refund
     *
     * @mbg.generated
     */
    private Boolean isAllowRefund;

    /**
     *
     * 订单项状态(0-待处理|1-待付款|2-待发货|3-待收货|4-交易成功|5-交易关闭|6-退款中)
     * shopping_order_item.order_status
     *
     * @mbg.generated
     */
    private Byte orderStatus;

    /**
     *
     * 退款状态(0-待商家确认|1-填写退货地址|2-待退货|3-待退款|4-退款成功|5-退款失败|6-平台介入)
     * shopping_order_item.refund_status
     *
     * @mbg.generated
     */
    private Byte refundStatus;

    /**
     *
     * 发送提醒的次数
     * shopping_order_item.send_time
     *
     * @mbg.generated
     */
    private Integer sendTime;

    /**
     *
     * 创建时间
     * shopping_order_item.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * 修改时间
     * shopping_order_item.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopping_order_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.id
     *
     * @return the value of shopping_order_item.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.id
     *
     * @param id the value for shopping_order_item.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.shopping_order_id
     *
     * @return the value of shopping_order_item.shopping_order_id
     *
     * @mbg.generated
     */
    public Long getShoppingOrderId() {
        return shoppingOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.shopping_order_id
     *
     * @param shoppingOrderId the value for shopping_order_item.shopping_order_id
     *
     * @mbg.generated
     */
    public void setShoppingOrderId(Long shoppingOrderId) {
        this.shoppingOrderId = shoppingOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.product_id
     *
     * @return the value of shopping_order_item.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.product_id
     *
     * @param productId the value for shopping_order_item.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.product_name
     *
     * @return the value of shopping_order_item.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.product_name
     *
     * @param productName the value for shopping_order_item.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.product_model_id
     *
     * @return the value of shopping_order_item.product_model_id
     *
     * @mbg.generated
     */
    public Long getProductModelId() {
        return productModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.product_model_id
     *
     * @param productModelId the value for shopping_order_item.product_model_id
     *
     * @mbg.generated
     */
    public void setProductModelId(Long productModelId) {
        this.productModelId = productModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.activity_product_model_id
     *
     * @return the value of shopping_order_item.activity_product_model_id
     *
     * @mbg.generated
     */
    public Long getActivityProductModelId() {
        return activityProductModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.activity_product_model_id
     *
     * @param activityProductModelId the value for shopping_order_item.activity_product_model_id
     *
     * @mbg.generated
     */
    public void setActivityProductModelId(Long activityProductModelId) {
        this.activityProductModelId = activityProductModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.product_model_name
     *
     * @return the value of shopping_order_item.product_model_name
     *
     * @mbg.generated
     */
    public String getProductModelName() {
        return productModelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.product_model_name
     *
     * @param productModelName the value for shopping_order_item.product_model_name
     *
     * @mbg.generated
     */
    public void setProductModelName(String productModelName) {
        this.productModelName = productModelName == null ? null : productModelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.product_feature_image
     *
     * @return the value of shopping_order_item.product_feature_image
     *
     * @mbg.generated
     */
    public String getProductFeatureImage() {
        return productFeatureImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.product_feature_image
     *
     * @param productFeatureImage the value for shopping_order_item.product_feature_image
     *
     * @mbg.generated
     */
    public void setProductFeatureImage(String productFeatureImage) {
        this.productFeatureImage = productFeatureImage == null ? null : productFeatureImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.regular_price
     *
     * @return the value of shopping_order_item.regular_price
     *
     * @mbg.generated
     */
    public BigDecimal getRegularPrice() {
        return regularPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.regular_price
     *
     * @param regularPrice the value for shopping_order_item.regular_price
     *
     * @mbg.generated
     */
    public void setRegularPrice(BigDecimal regularPrice) {
        this.regularPrice = regularPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.sales_price
     *
     * @return the value of shopping_order_item.sales_price
     *
     * @mbg.generated
     */
    public BigDecimal getSalesPrice() {
        return salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.sales_price
     *
     * @param salesPrice the value for shopping_order_item.sales_price
     *
     * @mbg.generated
     */
    public void setSalesPrice(BigDecimal salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.deduction_points
     *
     * @return the value of shopping_order_item.deduction_points
     *
     * @mbg.generated
     */
    public BigDecimal getDeductionPoints() {
        return deductionPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.deduction_points
     *
     * @param deductionPoints the value for shopping_order_item.deduction_points
     *
     * @mbg.generated
     */
    public void setDeductionPoints(BigDecimal deductionPoints) {
        this.deductionPoints = deductionPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.deduction_points_amount
     *
     * @return the value of shopping_order_item.deduction_points_amount
     *
     * @mbg.generated
     */
    public BigDecimal getDeductionPointsAmount() {
        return deductionPointsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.deduction_points_amount
     *
     * @param deductionPointsAmount the value for shopping_order_item.deduction_points_amount
     *
     * @mbg.generated
     */
    public void setDeductionPointsAmount(BigDecimal deductionPointsAmount) {
        this.deductionPointsAmount = deductionPointsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.subtotal
     *
     * @return the value of shopping_order_item.subtotal
     *
     * @mbg.generated
     */
    public BigDecimal getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.subtotal
     *
     * @param subtotal the value for shopping_order_item.subtotal
     *
     * @mbg.generated
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.quantity
     *
     * @return the value of shopping_order_item.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.quantity
     *
     * @param quantity the value for shopping_order_item.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.freight
     *
     * @return the value of shopping_order_item.freight
     *
     * @mbg.generated
     */
    public String getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.freight
     *
     * @param freight the value for shopping_order_item.freight
     *
     * @mbg.generated
     */
    public void setFreight(String freight) {
        this.freight = freight == null ? null : freight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.is_evaluation
     *
     * @return the value of shopping_order_item.is_evaluation
     *
     * @mbg.generated
     */
    public Boolean getIsEvaluation() {
        return isEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.is_evaluation
     *
     * @param isEvaluation the value for shopping_order_item.is_evaluation
     *
     * @mbg.generated
     */
    public void setIsEvaluation(Boolean isEvaluation) {
        this.isEvaluation = isEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.is_allow_refund
     *
     * @return the value of shopping_order_item.is_allow_refund
     *
     * @mbg.generated
     */
    public Boolean getIsAllowRefund() {
        return isAllowRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.is_allow_refund
     *
     * @param isAllowRefund the value for shopping_order_item.is_allow_refund
     *
     * @mbg.generated
     */
    public void setIsAllowRefund(Boolean isAllowRefund) {
        this.isAllowRefund = isAllowRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.order_status
     *
     * @return the value of shopping_order_item.order_status
     *
     * @mbg.generated
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.order_status
     *
     * @param orderStatus the value for shopping_order_item.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.refund_status
     *
     * @return the value of shopping_order_item.refund_status
     *
     * @mbg.generated
     */
    public Byte getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.refund_status
     *
     * @param refundStatus the value for shopping_order_item.refund_status
     *
     * @mbg.generated
     */
    public void setRefundStatus(Byte refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.send_time
     *
     * @return the value of shopping_order_item.send_time
     *
     * @mbg.generated
     */
    public Integer getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.send_time
     *
     * @param sendTime the value for shopping_order_item.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Integer sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.gmt_create
     *
     * @return the value of shopping_order_item.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.gmt_create
     *
     * @param gmtCreate the value for shopping_order_item.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order_item.gmt_modified
     *
     * @return the value of shopping_order_item.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order_item.gmt_modified
     *
     * @param gmtModified the value for shopping_order_item.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}